### ISSUE TITLE
cursor displays on line below when using centered text

### ISSUE THREAD

**Issue by finetype** [mattboldt/typed.js#100]
am I missing something? deciding just not to use it for now.

Thanks, great little library. :)

**Comment by mattboldt** [comment]
Depending on how your CSS is setup, it should work fine with centered text. Here's how I have my code setup:
```
<div style="text-align:center;">
     <span id="typed" style="white-space:pre;"></span>
</div>
```

**Comment by wenweih** [comment]
@mattboldt thx for your answer ! in addition , the typed id should add display:inline style , and it work for me . 💐
