### ISSUE TITLE
typed.cursor is actually an ID. CSS animation needs update from class

### ISSUE THREAD

**Issue by Kiyakou** [mattboldt/typed.js#101]
When using typed.js in my code example on codepen http://codepen.io/Kiyakou/pen/qOWQJq. The animation selecting typed-cursor as a class did not work, upon inspecting the pip character element I discovered it was an ID. The animation example provides the pipe character as a class. This may need to be checked for those who fork this project.
![cursor](https://cloud.githubusercontent.com/assets/14007151/9606809/727fbaa6-507a-11e5-9bf7-7fbcfcdb4d54.png)

**Comment by mattboldt** [comment]
I looked at your demo and it appears you're using an older version of the code. Please update and you'll get the cursor with a class!
