### ISSUE TITLE
Handling an ampersand "&amp;" inside string in static HTML.

### ISSUE THREAD

**Issue by evolross** [mattboldt/typed.js#103]
I'm noticing in all browsers that when I try to use an ampersand inside of a string in static HTML in `contentType: text` mode like so:

    <div id="typed-strings-1">
       <p>Upcoming Q & A</p><p>Future Conference</p><p>Keynote Speaker</p>
    </div>

or like:

    <div id="typed-strings-1">
       <p>Upcoming Q &amp; A</p><p>Future Conference</p><p>Keynote Speaker</p>
    </div>

Typed.js always displays it on my site as `Upcoming Q &amp; A` (sorry had to use a code block to get it to show the `&amp;`).  Am I missing something?  I don't want to use `contentType: "html"` because my content is only text.

**Comment by AndriusZid** [comment]
This issue is similar to #55 

The only solution for right now I believe is to use contentType: "html" property and update string with replaced html symbols like text.replace("&", "&amp;");

**Comment by mattboldt** [comment]
should be fixed now
