### ISSUE TITLE
Mobile compatible?

### ISSUE THREAD

**Issue by nitroale** [mattboldt/typed.js#104]
Sorry, I am a real noob. I can't understand if typed.js works on mobile. On Opera and Safari, it doesn't work. I just get the list of strings instead of the animation. But somehow it worked on a Galaxy S2.
Tryed the demo at mattboldt.com with opera mini, and it works, just my implementation don't work?
for reference here there is my implementation mio.webatu.com

**Comment by jimulle** [comment]
Typed.js words fine on mobile for me.

Your implementation is throwing an error when I try to access the page:

    SCRIPT438: Object doesn't support property or method 'typed' 
    main.js, line 4 character 9
