### ISSUE TITLE
stringsElement doesn't work

### ISSUE THREAD

**Issue by tianhengzhou** [mattboldt/typed.js#105]
I had a hard time to get stringElements you showed in the ReadMe working. I have code like this.

$("#blog").typed({
                 stringsElement: $('#title'),
                 showCursor: false,
                 callback: function(){
                     $('.content').fadeIn('slow')}
             })

```
<div id="title" style="display: none"><p>Blog</p></div>
<h1 id="blog"></h1>
```

It keeps just display the words: it's default value, please try your own have a nice day.

**Comment by palmiak** [comment]
It works - look at https://github.com/mattboldt/typed.js/issues/112

I assume You used bower to install typed.js
