### ISSUE TITLE
Typing speed less than 0 ?

### ISSUE THREAD

**Issue by devkhan** [mattboldt/typed.js#106]
Can I make the typing speed even slower than the default zero('0')?

Or is there any other way to do it?

**Comment by mrwbsn** [comment]
have yo ever tried typeSpeed > 0? when i set to more than 0 the typewrite become slower.

```javascript
   typeSpeed: 100,
```

I hope it will help you.

**Comment by devkhan** [comment]
Thanks @mrwbsn . It worked.
