### ISSUE TITLE
Make jquery optional

### ISSUE THREAD

**Issue by kof** [mattboldt/typed.js#107]
Can we rewrite it so that it can be used without jquery?

jQuery plugin can be still a separate file, which uses the main lib, I think most dependencies can be replaced by lodash like "assign" function or pure DOM.

The benefit is that it can be used in non-jquery projects.

**Comment by nblackburn** [comment]
While I agree with this 100%, you are suggesting to replace one dependency with another when it would be better to have zero dependencies.

**Comment by kof** [comment]
With proper build tool, you just require specific functions from lodash, not entire lib.

**Comment by nblackburn** [comment]
True, didn't really think about that.

**Comment by mattboldt** [comment]
at the moment it's a jQuery plugin. Maybe in the future it will be vanilla JS

**Comment by sobolevn** [comment]
Making JQuery optional is really a good idea.

**Comment by buob** [comment]
I'd be willing to work on this if you're interested in considering it @mattboldt.

Great tool, by the way!

**Comment by mattboldt** [comment]
This thread is a little stale, but it's now jquery-less!
