### ISSUE TITLE
Alertbox when finished.

### ISSUE THREAD

**Issue by Jumperlow** [mattboldt/typed.js#109]
Hello,

I'm working on a site, and I want an alertbox to appear once it has written 3 sentences. Does anyone know how to do this?

**Comment by lwm** [comment]
If you check the [customisation section](https://github.com/mattboldt/typed.js#customization), you can find that there is the option:

```
...
// starting callback function before each string
preStringTyped: function() {},
...
```

Show the alert box on the third call of this ?

**Comment by GeorgioWan** [comment]
Take a look, a little example when your sentences typed done.
https://jsfiddle.net/GeorgioWan/gyp4t70w/

You can use the **callback function** like @lwm give you [Customisation section](https://github.com/mattboldt/typed.js#customization) =D

**Comment by Jumperlow** [comment]
Sorry for being inactive. It worked with @lwm's solution.

**Comment by lwm** [comment]
:rocket:
