### ISSUE TITLE
Text disorientated on Safari.

### ISSUE THREAD

**Issue by karam94** [mattboldt/typed.js#110]
Hi,

When using the Safari browser on numerous devices, I've noticed the text (when being typed out) displaying in a very disorientated fashion. I've attached some images of how the text looks during the typing out period.
Once the final sentence being typed out is reached, the text goes normal and displays normally again.

https://www.yogile.com/w1imyexv/41m/share/?vt=hXfQOcV

Any idea what is causing this?

**Comment by mattboldt** [comment]
hrm. not seeing any problems with safari
