### ISSUE TITLE
Something about the stop function  

### ISSUE THREAD

**Issue by driant** [mattboldt/typed.js#111]
Hi Matt,
I was checking the stop function that you have commented and added something like this to make it stop on element click,

, stops: function() {
            var self = this;
            self.strings = [];
            clearInterval(self.timeout);
         }
and at element click called $('element').typed('stops');
It may be not be the best solution but it worked for me.
Thanks

**Comment by brianhankins** [comment]
Sample Code To Use alert("spoiler"):

To give this a scroll feature to start at a certain element (usually a div works best) and also to clear up any confusion. This pause feature by @driant  is on a button created. 

This will also work with long paragraphs using the stringsElement option.

After typed.js runs or the 'skip' button is clicked, it will remove the div and replace it with another div

All of #yourDiv need to be the same throughout. The same goes for #paragraphText and ##yourNewDivToReplace!

//This is the scroll feature which will start the typed.js at that location of the page
```
function start_type(){
 $(function() {
    $('**#yourDiv**').typed({
      stringsElement: $('**#paragraphText**'),
      typeSpeed: 40, //_this is set to slowly write out text for long paragraphs_
      backSpeed: -1000, //_this is set to quickly delete long paragraphs_
      callback: function() {
        $('**#yourDiv**').remove();
        $('**#yourNewDivToReplace**').show();
      },
    }); 
    
      $('.stops').on('click', function() {
        $('**#paragraphText**').typed('stops');
        $('**yourDiv**t').remove();
        $('**#yourNewDivToReplace**').show();
      });
  });
}
```
