### ISSUE TITLE
tag 1.1.1 and master are different

### ISSUE THREAD

**Issue by palmiak** [mattboldt/typed.js#112]
Hi

Just saw that tag 1.1.1 has older js files than master - there is not stringsElement support.

It's important for bower, which by default uses 1.1.1

**Comment by Eraldo** [comment]
Same issue here..
Any plans on getting bower up to date?
Any way I can help?

**Comment by danielfeelfine** [comment]
Fixed with ```bower install typedjs-bower --save``` and load script from ```typedjs-bower``` path instead of ```typed.js```.

**Comment by pratheekhegde** [comment]
When will the bower get the update ?

**Comment by mplunkett5** [comment]
As an interim measure you can install the master branch via bower directly rather than relying on the v1.1.1 specified in the existing bower.json.

Just use the following command:
`bower install typed.js#master --save`
