### ISSUE TITLE
unable to only backspace some words in a string

### ISSUE THREAD

**Issue by kevinxh** [mattboldt/typed.js#113]
In typed.js, line 268, there are several lines of comment, where says we can use self.stopNum to preserve characters in arrayPos.

But when I try it, it replaces the previous string.

How can I delete only several characters and continue typing?

**Comment by kevinxh** [comment]
If I only have one word, and I want to do that, it was ok. But it failed when I have multiple words.

**Comment by kevinxh** [comment]
if I set the stopNum really big. it is expecting to not backspace anything and continue to type. however, the actual behavior was it just replaced the old string with new string.

**Comment by lyziane** [comment]
Still not working
