### ISSUE TITLE
Placeholder stop animation

### ISSUE THREAD

**Issue by tukera** [mattboldt/typed.js#114]
How can I change the settings to stop the animation and clear the text from the placeholder to be able to type in.

At the moment I can type but the animation is running and if I stop the animation I have part of the text inside the input.

**Comment by jdtzmn** [comment]
+1

**Comment by ronpearl** [comment]
I actually wrote a quick spin-off to this plugin that allows for starting and stopping.   It hasn't been tested too much but for what I put together it seems to be working.  I too got a little frustrated that I couldn't start/stop on command.

Here is a link to it:
https://github.com/ronpearl/typeforme

There are a bunch of samples if you follow the links in the description.   Good luck!
