### ISSUE TITLE
Ampersant (&) breaks script

### ISSUE THREAD

**Issue by FrDH** [mattboldt/typed.js#115]
The scripts stops working (and crashes the browser) when an ampersant is used in a string:
````javascript
$("h1").typed({
    strings: [ "dogs & cats" ]
});
````

**Comment by pratiksolim** [comment]
Use following code. It worked for me.
```
$("h1").typed({
    strings: [ "dogs &amp; cats" ],
    contentType: "html"
});
```

**Comment by kimkha** [comment]
Using `&amp;` works, but it will be appear `&am` when back... Should be fix the bug...
