### ISSUE TITLE
Wrong word wrap

### ISSUE THREAD

**Issue by Ashald** [mattboldt/typed.js#117]
Hi, I'm not a pro in front-end development though I'm not sure that it's an issue with `typed.js` or with html/css. Though if you don't mind I'd like to ask you to check it out so I will know what should be fixed.

I just created a new blog with Ghost CMS and installed Minto theme that uses `typed.js`. Now if you go to  https://ashald.ghost.io the front page is supposed to show 'Travel, slice of life development'. Though at least in Safari and Chrome on Mac OS sometimes text is trimmed instead being word-wrapped. The easiest way to reproduce that I found so far is to open the page in Safari in responsive design mode, select 1366x768 screen size and reload the page. Though the same effect could be achieved with regular mode and browser window of similar or smaller size.
![screen shot 2015-11-30 at 02 19 44](https://cloud.githubusercontent.com/assets/397987/11465750/50c062dc-9709-11e5-8a97-725ec017495d.png)

Thanks!

**Comment by Ashald** [comment]
This is fixed or won't fix?

**Comment by mattboldt** [comment]
sorry, your demo site is no longer there. But, the issue is due to the HTML element the text is being typed into, as well as the `word-wrap` settings. Make sure the element doesn't extend past your window's size.
