### ISSUE TITLE
types js for arabic langauge

### ISSUE THREAD

**Issue by ismaelhaider** [mattboldt/typed.js#120]
Hello, can we write arabic text using typed js ?

**Comment by lwm** [comment]
@ismaelhaider - sure, you just do the following (along with the usual [setup steps](https://github.com/mattboldt/typed.js#installation))

```
$(".typed").typed({ strings: ["اللا الشتاء فصل"] });
```

PS. I don't speak arabic, so I have no idea what I just pasted, so you will have to excuse me ;)
