### ISSUE TITLE
option to cancel the backtyping?

### ISSUE THREAD

**Issue by deostroll** [mattboldt/typed.js#122]
Is there an option for the end-user to opt for no-backtyping animation?

**Comment by roymap** [comment]
yes, that would be great.

**Comment by mahieddine** [comment]
I've added an option for this in this fork https://github.com/mahieddine/typed.js
....
 backDelete:false,
.....
And you're done

**Comment by Stroncod** [comment]
Doesn't work for me the adding backDelete:False, still delete all the first sentence.
