### ISSUE TITLE
Why it deletes the whole line ?

### ISSUE THREAD

**Issue by dajy** [mattboldt/typed.js#123]
Hello Matt,

I have this script and am trying to figure out why it deletes the whole line instead of deleting just the last word? Can you help me out ?

$(function(){
  $(".typeeffect").typed({
    strings: ["Witch look realistic and awesome", "Witch look realistic and proffessional"],
    typeSpeed: 50
  });
});

**Comment by dajy** [comment]
I think i just figured it out i used a callback to initialize another function and hided the cursor for the first animation.

<span class="typeeffect">witch look realistic and</span> 
<span class="typeeffect2"></span>

	  $(function(){
	      $(".typeeffect").typed({
	        strings: ["Witch look realistic and"],
	        typeSpeed: 50,
	        callback: function(){
	          shift();
	        }
	      });
	  });

	  function shift(){
	  	  $('.typed-cursor').hide();
	      $(".typeeffect2").typed({
	        strings: ["awesome", "proffessional"],
	        typeSpeed: 50,
	      });
	  }

**Comment by JordyCR** [comment]
Hi @dajy few hours I was looking a way to get the same. I hope this answer helps you.
First, as @mattboldt says in README file, you need to set this in the code

**Get Super Custom** Section
```javascript
...
, backspace: function(curString, curStrPos){
  ...

  setTimeout(function() {

		  // check string array position
		  // on the first string, only delete one word
		  // the stopNum actually represents the amount of chars to
		  // keep in the current string. In my case it's 3.
		  if (self.arrayPos == 1){
			  self.stopNum = 3;
		  }
		  //every other time, delete the whole typed string
		  else{
			  self.stopNum = 0;
		  }
...
```

But this is kind of tricky because is **inside** Typed.js code, so you need to open teped.js and look for this part:
```javascript
self.timeout = setTimeout(function() {

	// ----- this part is optional ----- //
	// check string array position
	// on the first string, only delete one word
	// the stopNum actually represents the amount of chars to
	// keep in the current string. In my case it's 14.
	// if (self.arrayPos == 1){
	//  self.stopNum = 14;
	// }
	//every other time, delete the whole typed string
	// else{
	//  self.stopNum = 0;
	// }
```

I found it on line 266. Then, to get what are you asking just uncomment that if-else statement and modify `self.arrayPos = 0` and `self.stopNum = 25`

Regards

**Comment by dayj** [comment]
@JordyCR looks like you meant to mention @dajy :)

**Comment by dajy** [comment]
@JordyCR Thanks!

**Comment by dsiglin** [comment]
hey @JordyCuan I found this conversation looking for more explanation as to what the author meant about not deleting the whole phrase. I've uncommented the if / else part but all the characters are still deleted. Here's what the code looks like in typed.js

` backspace: function(curString, curStrPos) {
            // exit when stopped
            if (this.stop === true) {
                return;
            }

            // varying values for setTimeout during typing
            // can't be global since number changes each time loop is executed
            var humanize = Math.round(Math.random() * (100 - 30)) + this.backSpeed;
            var self = this;

            self.timeout = setTimeout(function() {

                // ----- this part is optional ----- //
                // check string array position
                // on the first string, only delete one word
                // the stopNum actually represents the amount of chars to
                // keep in the current string. In my case it's 14.
                if (self.arrayPos == 0){
                self.stopNum = 5;
                }
                //every other time, delete the whole typed string
                else{
                self.stopNum = 5;
                }`

Here's what the wording looks like (using the html option)

`	<div id="typed-strings">
	<p><span class="maintag_text">I&#39;M A FULL&ndash;STACK DESIGNER</span></p>
	<p><span class="maintag_text">N UX FIEND</span></p>
	<p><span class="maintag_text"> HUMAN BEING</span></p>
	</div>`

You can see everything NOT working here:
http://davidsiglin.com/Test2/


Thanks for your help!

**Comment by Axladrian** [comment]
Having the same issue.

**Comment by JordyCuan** [comment]
@dsiglin I hope it is not too late

I do not know well how are you doing that but let me try (by the way, I can not access to your link):

`self.arrayPos == 0` in `if (self.arrayPos == 0){` line means what "string element" is going to be "partial deleted". For example I have this in my personal blog

`
<span class="typed_element">
    <div class="typed_sub-element">Hello!^1500</div>
    <div class="typed_sub-element">Welvcome t</div>
    <div class="typed_sub-element">Welcome to my blog.^1000</div>
    <div class="typed_sub-element">Feel free to Read and Learn :)</div>
</span>
`

In my case `self.arrayPos` should be `self.arrayPos == 1`

And the characters that should to be not deleted are 3 (In "Welvcome" it deletes until "Wel" and starts to type again).

I do not know if it explains what you want. I hope it does, if not let me know or you can see my version [here](https://github.com/JordyCuan/jordycuan.github.io/blob/master/js/typed.js)

@Axladrian can you give us more details?

Cheers!
