### ISSUE TITLE
Write string, move cursor back and remove word?

### ISSUE THREAD

**Issue by realph** [mattboldt/typed.js#124]
Is it possible to write a string, move the cursor back to a previous position in that string and then backspace on that text?

Like so:

> This is a word I want to remove|
> This is a word| I want to remove
> This is a wo| I want to remove
> This is a | I want to remove

Is something like this possible with typed.js?

Any help is appreciated. Thanks in advance!

**Comment by JordyCR** [comment]
I think you are trying to do this:


	<span class="typeeffect"></span>
	

	$(function(){
			$(".typeeffect").typed({
				strings: ["This is a <span class="word">word</span> I want to remove"],
				typeSpeed: 50,
				contentType: 'html',
				callback: function(){
					remove();
				}
			});
	});

	function remove(){
			$('.typed-cursor').hide();
			$(".word").typed({
				strings: ["part", "segment"],
				typeSpeed: 50,
			});
	}

**Comment by jryanhaber** [comment]
This is great. 

I find myself either wanting to speed up the backspacing more then it does, or to just delete the text and start typing the next string.  Any ideas for this?

I did try jquery's empty() and text(), but the text reappears and is backspaced out...

**Comment by jryanhaber** [comment]
I should definitely mention that I am creating the beginnings of an AI life coach with this software, demos of various versions of this are available in my portfolio under AIBots, and I will get a gitHub link up soon  http://synthesisrecruiting.com/Package-HTML/HTML/Synthesis_2.html#
