### ISSUE TITLE
Compatible on iOS Safari?

### ISSUE THREAD

**Issue by SuttJ** [mattboldt/typed.js#126]
The demo site works on my iPhone, yet when I load my site that uses it, it doesn't work.

**Comment by mattboldt** [comment]
yep it works. double check your code.

**Comment by tetreault** [comment]
@mattboldt Love the library, thanks for the cool work. 

I'm having a problem on mobile safari on an **iphone 6 running ios 10.3.1.** When the typing animation starts it glitches out in the top 1/3 part of the word before eventually un-glitching the text. 

![image uploaded from ios](https://cloud.githubusercontent.com/assets/5934354/25239772/03ea62a0-25bf-11e7-8383-ef1b070df2d9.jpg)

**Comment by tetreault** [comment]
NVM @mattboldt I resolved this. Bootstrap CSS had the h1 `line-height` set too small and it was the reason for the clipping.
