### ISSUE TITLE
how can i put link in strings text?

### ISSUE THREAD

**Issue by finduk** [mattboldt/typed.js#128]
Sample:
strings: ["", " Lipsum 1, ^1000 Lipsum 2, ^2000 Lipsum 3,   Lipsum 4 "],
contentType: 'html',

Need: <a href=""> Lipsum 4</a>
Problem: Function does not work when I text link.

**Comment by BaxleyAldworth** [comment]
Instead of using the strings param, use the stringsElement to set your text. This will make it easier to add html tags to your text.

Example:
```html
<div id="typed-strings>
    <p><a href="http://www.google.com">Test <strong>Link</strong></a>. ^2000 More Text</p>
</div>

<script>
 $(function () {
            $(".bubblewords").typed({
                stringsElement: $('#typed-strings'),
                typeSpeed: 0,
            });
        });
</script>

```

**Comment by chumack** [comment]
this one really work?

  stringsElement: $('#typed-strings')

copied your example but still no work.
no any error in console.

===js
$(function(){
        $("#typed").typed({
            stringsElement: $('#typed-strings'),
            loop: true,
            contentType: 'html'
        });
    });

===html

<span id="typed"></span>
<div id="typed-strings">
        <p>Typed.js is a <strong>jQuery</strong> plugin.</p>
       <p>It <em>types</em> out sentences.</p>
</div>

**Comment by builtbylane** [comment]
+1

**Comment by mplunkett5** [comment]
Currently the master version js file and tag v1.1.1 our out of sync: #112 

Best option until the bower.js is updated is to download the typed.js from master. You can always double check the .js file and ensure stringsElement is present in the file.
