### ISSUE TITLE
Can't seem to get the plugin to type.

### ISSUE THREAD

**Issue by leadoffsundew1** [mattboldt/typed.js#132]
I have the plugin linked with a `<script>` tag in my HTML, and I have the jQuery function in _my_ script file. But I can't get it to type, and I have no clue why. As far as I can tell I'm not doing anything wrong, but I am very new to JavaScript so I very well might be. I bet it's something super obvious that I'm missing...

Here is my code:
HTML
`            <h1 class="hero-text">The most <span class="creative"></span><span class="typed-cursor">|</span> designs<br> on the net.</h1>`

jQuery
`    $(function(){`
`        $(".creative").typed({`
`          strings: ["creative", "innovative", "inspiring", "creative"],`
`          typeSpeed: 0`
`        });`
  
Your help is greatly appreciated.

**Comment by cielmoni** [comment]
I think you forgot the closing on the `<span class="creative"</span>`.

**Comment by leadoffsundew1** [comment]
Good eye, but that was just a typo from when I created the issue.

**Comment by cielmoni** [comment]
Check your links to jquery.js and typed.js file.  Make sure they are in that order (jquery.js first than typed.js).  I was able to get it to work. Here is the HTML:

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="js/typed.js" type="text/javascript"></script>
    <script>
    $(function(){
        $(".creative").typed({
        strings: ["creative", "innovative", "inspiring", "creative"],
        typeSpeed: 0
    });

    });

    </script>
</head>
<body>

<h1 class="hero-text">The most <span class="creative"></span><span class="typed-cursor"></span> designs<br> on the net.</h1>

</body>
</html>
```

**Comment by leadoffsundew1** [comment]
Thank you so much! This stumped me for days!
