### ISSUE TITLE
Start with a sentences already written - then delete it and write a new one

### ISSUE THREAD

**Issue by G-Wiz** [mattboldt/typed.js#134]
@mattboldt 
Current Behaviour:
The plugin starts with a typing and the waits, continue with back deleting and writes an new sentence

Desired Behaviour: 
A sentence should already be written, then deleted and then replaced with a new one.

Many thxs!

**Comment by lwm** [comment]
FWIW, you can already kinda do this, albeit missing the type back on the already typed sentence.

```
<span>I like to <span class="element">x</span> </span>
```

Then `x` will be already typed, will get removed and then the usual `strings` will be written out.

**Comment by G-Wiz** [comment]
@lwm thank you for your response!
I'm using the wordpress Plugin, hence i just got a shortcode to put in my theme/code etc... I can adopt all the basic, but don't know how to put in your code in the plugin.
Maybe you can help me once again... cheers

**Comment by lwm** [comment]
I am not quite sure about the Wordpress plugin, perhaps [the support](https://wordpress.org/support/plugin/typed) is a good place to start? Otherwise, you'd have to wait for this to implemented, if it will be ?

**Comment by G-Wiz** [comment]
Ok, many thxs anyway for you help!:)

**Comment by lwm** [comment]
:+1:
