### ISSUE TITLE
basic stringsElement example doesn't work

### ISSUE THREAD

**Issue by zackhall** [mattboldt/typed.js#136]
Hi,

I tried out the basic case using the `stringsElement` example from the README and it just types the default values every time. 

See jsbin example:
http://jsbin.com/pigesikoxu/edit?html,css,js,output

**Comment by GeorgioWan** [comment]
There is no any problem in codeopen and jsfiddle...so weird :fearful: 

https://jsfiddle.net/GeorgioWan/y8wzyt4w/1/

**Comment by zackhall** [comment]
Hey, @GeorgioWan. Thanks for your reply. Upon inspecting it it just looks like the cdnjs version of typed is outdated. Do you know what the current release is?

**Comment by GeorgioWan** [comment]
Hi, I checked that **cdnjs version** and the **latest release version** is the same, but I think there is a lot of changes till now!
The release tag(v1.1.1) was on `12 May 2015`, but the latest commit of master is on `13 Sep 2015`, so maybe you should download the latest version in master :smiley:

**Comment by mplunkett5** [comment]
Downloading the Master js as opposed to the tagged v1.1.1 version file solved my issue :) #112

**Comment by mattboldt** [comment]
sorry about that. There's an up to date tag added now
