### ISSUE TITLE
Empty HTML-tag in string is causing display problem

### ISSUE THREAD

**Issue by denbue** [mattboldt/typed.js#138]
If you are using an empty HTML-tag in a string like this:

`strings: ["This is a string<span></span>"],`

It will cause a display problem. The output is `This is a string</`, then it dissapears and will correctly displayed.

If you put a single space to the HTML-tag:

`strings: ["This is a string<span> </span>"],`

The output is correct.

**Comment by geesen** [comment]
I can confirm this issue. 
This also occurs, when using static HTML. Using e.g. fontawesome with the following snippet, also produces this issue:


`<div id="typed-strings">
                                <p>We <i class="fa fa-heart color-pasific"></i> it!^1000</p>                               
                            </div>`

With a single space between the tag, really helps (thanks for the hint)
