### ISSUE TITLE
Start with backspace

### ISSUE THREAD

**Issue by moitorrijos** [mattboldt/typed.js#142]
Hello everyone, I would like to start the animation with the backspace animation. How would I go about doing that?

**Comment by moitorrijos** [comment]
To anyone who might be attempting to do this. What I did was I created a function to replicate the backspace and run it before the typed.js. There is probably a better way but it works. :)
`function backspace() {
  var word = $('.typed-text').html();
  var wordLength = word.length;
  var newWordLength = wordLength - 1;
  var newWord = word.slice(0, newWordLength);
  $('.typed-text').html(newWord);
  if (newWordLength === 0) {
    clearInterval(intrvl);
  } else {
    newWordLength = wordLength;
  }
}`

**Comment by chrisamsterdam1986** [comment]
Hello @moitorrijos, @mattboldt ,

I am trying to do exactly the same, however, I want to write something again as soon as it is deleted. And this should all be triggered by a mouseover/hover event in jQuery.

However, I'm not a very experienced JS developer, and I don't really know how to do it. I did manage to understand how you remove the text in your Codepen (Thank you for that!), but wrapping a click/mouseover event around it and making new text appear again is a bit too difficult for me. 

So I was hoping if you would like to give me some advice and push me in the right direction? 

I really hope to hear back from you,

Cheers,
Chris

**Comment by moitorrijos** [comment]
Hi @chrisamsterdam1986, that is absolutely possible. Simply create a function (I called it typewrite, but you can call it whatever you want) that has the typed method on it. Then you just run this new function on a click event anywhere you want. Check out the same codepen to see how I did it. http://codepen.io/moitorrijos/pen/QNwdLj

**Comment by chrisamsterdam1986** [comment]
Hi @moitorrijos,

Thank you very much for your help! It gave me a great first start, and I feel like I'm very close to what I want to achieve... However, I'm not yet fully there. I hope you can give me a last push in the right direction.

So what I have now is that, as soon as the user hovers over the text, it will remove the text that is now there (100 day challenge) and writes the new text (view project). This works perfect.

However, what I didn't manage to fix is the following: as soon as the user's mouse leaves the the text, it should remove the text: 'view project' again, and re-write the text '100 day challenge' again. 

Please check out my CodePen here: http://codepen.io/chrisamsterdam1986/pen/pbNPQx

I very much hope to hear back from you!

Cheers,
Chris

**Comment by moitorrijos** [comment]
Hi @chrisamsterdam1986, I am taking a look at the pen and I think is working fine.

**Comment by chrisamsterdam1986** [comment]
Hoi @moitorrijos,

I just finished it a second ago! Great timing, I would say :-D

Btw, now that you're looking at it, do you have an idea on how to force the animation to finish? Because if you move the mouse of the title before the animation ends, it all gets kind of messed up ;-)

Cheers!

**Comment by moitorrijos** [comment]
Hey, yes I see what you mean. I tried using jquery's off method, but I couldn't get it to work. But I believe that is the best approach.

**Comment by mattboldt** [comment]
Added on 2.0 https://github.com/mattboldt/typed.js/pull/264

**Comment by pratyushpoddar** [comment]
@mattboldt How do I enable this? I am not able to prefill my div with some text and then start with backspacing the whole text and then typing down the new one.

Any help is appreciated.
