### ISSUE TITLE
Typed does not 'retype'

### ISSUE THREAD

**Issue by raimondi1337** [mattboldt/typed.js#150]
I'm trying to use Typed to print various strings in a box based on which button you click ie
```javascript
function type(str){
	$("#right").typed({
		strings: [str],
		typeSpeed: 0
	});
};

$("#one").click(function(){type("Now this is a story all about how"}));
$("#two").click(function(){type("My life got flipped turned upside down"}));
```

Typed only ever fires once, I can not 'retype' the div.

**Comment by raimondi1337** [comment]
Fixed using `$("#right").typed('reset');`

**Comment by mattboldt** [comment]
should be fixed now

**Comment by dougfabris** [comment]
Hey @mattboldt! I tried to use $("element").type('reset'); but this returned an error for me. I did an search in your plugin documentation an found "reset()". Using element.reset(); works like a charm!
