### ISSUE TITLE
Responsive Help!

### ISSUE THREAD

**Issue by cosmicAsymmetry** [mattboldt/typed.js#151]
Hello I'm trying to use typed.js on a responsive website. The problem that I'm facing is that when I move to a smaller screen the cursor moves to the bottom and isn't inline with the text.

**Comment by ralphbolliger** [comment]
Don't use a block element (like a div) as .element. Then the cursor will be inline with the typed text.

**Comment by katsos** [comment]
Or use whatever element you want with style="display:inline".

**Comment by cosmicAsymmetry** [comment]
Thank you. I used it on http://sidhant.me/.

**Comment by katsos** [comment]
Seems nice, but a little fast for my taste.  Well Done!

@mattboldt I think this issue must be closed.
