### ISSUE TITLE
Callback after typing ended

### ISSUE THREAD

**Issue by Jones-S** [mattboldt/typed.js#152]
Hi there
I see there is a callback function I can pass. Unfortunately it seems to trigger at the moment, when it starts typing. I'd rather have a callback , when the typewriter finished writing. Is there a possibility to get that? Otherwise it's no real callback function for me...

Thanks for any help

Cheers

**Comment by ahmedsafadii** [comment]
i also need that :(

**Comment by mattboldt** [comment]
Make sure your code is up to date. The callback does fire at the end.

**Comment by bartolsthoorn** [comment]
Just in case anyone ends up on this page through Google (it is the first hit on typed.js callback):

Currently you need to use one of the following options instead of `callback`: https://github.com/mattboldt/typed.js/blob/master/index.html#L54-L63

**Comment by kcamcam** [comment]
thanks for that @bartolsthoorn
