### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by rajunarwade** [mattboldt/typed.js#154]
Hi,

I have been trying to implement the RTL support but I could only move the cursor from right to left but the actual characters are typed from LTR but that's not the correct effect that I want could you please help me out. The [example](http://jsbin.com/qawop/1/edit?html,output) is not the correct RTL effect because that does not add character in right to left direction.

**Comment by Muhnad** [comment]
the example you attached is correct, you should use any language typed from right to left Arabic example to know the different, all thing is okay if you used the right language in the right position.

 try it do see the difference : 
strings: ["الكلمة الاولي", "الكلمة الثانية"]
