### ISSUE TITLE
Specify selection of string elements instead of single element

### ISSUE THREAD

**Issue by vwochnik** [mattboldt/typed.js#155]
Currently `typed.js` allows one to specify a string element as a source of strings. But, here is the issue: Internally, the library selects all child `p` elements for string retrieval. This is not flexible enough for my case.

I propose another option: Let the user specify a jQuery selection of elements and `typed.js` retrieves one string per element.

```
$("#typed").typed({
    stringsElements: $('#typed-strings > p')
});
```

**Comment by Martin-Nyaga** [comment]
Hi @vwochnik, see my pull request #141

**Comment by mattboldt** [comment]
Master now just uses the children of the `stringsElement` HTML el, instead of just `<p>`
