### ISSUE TITLE
Option to delay initial typing

### ISSUE THREAD

**Issue by ryangallen** [mattboldt/typed.js#16]
It would be nice to include an option for a delayed start to the typing (just show a blinking cursor for a few seconds).

**Comment by akash-d** [comment]
Start delay is not working fine for me.
$("#typed").typed({
                stringsElement: $('#typed-strings'),
                startDelay: 100,
                typeSpeed: 80,
                backDelay: 500,
                backSpeed: 40
            });

**Comment by Oceantidote** [comment]
I would like to add a delay to the second string type, so that the first typed section stays for a while before the second string gets typed. Any ideas on how I would do that?

**Comment by TriDEntApollO** [comment]
> I would like to add a delay to the second string type, so that the first typed section stays for a while before the second string gets typed. Any ideas on how I would do that?

use backDelay attribute

**Comment by nordseo** [comment]
The problem is using the startDelay is useless because the text will display before the function executes. Is there any documentation for this issue? (We've tried all the CSS possible, this is a typed.js bug)

**Comment by nordseo** [comment]
Please let us know if we are missing some secret feature about Typed.js to prevent the text from showing before the function calls.
