### ISSUE TITLE
Disable delete function

### ISSUE THREAD

**Issue by Stroncod** [mattboldt/typed.js#174]
I'm trying to replicate [this](http://www.jeffweisbein.com) website with typed.js but I can't find the way to disable the "re-write" effect. There is no such option ?

**Comment by tamoxin** [comment]
@Stroncod Did you changed the loop property to false?
`$("#yourElement").typed({
strings: [string],
loop: false
});`

**Comment by tamoxin** [comment]
@Stroncod I made an example for you.
http://codepen.io/tamoxin/pen/mEzdvJ

**Comment by Stroncod** [comment]
Works perfect !! Thank you very much
