### ISSUE TITLE
1.Infinite loop   2.start typing when it is visible (for long page with scroll)

### ISSUE THREAD

**Issue by daria-zadorozhna** [mattboldt/typed.js#176]
1.How make infinite loop? If i paste in script loop: infinite; instead loop: false; it doesn`t work.
2. div with this code is in section, which is not on the top of page. how to check if this section is visible on screen and then start typing

**Comment by XtremePlayzCODE** [comment]
1. loop: true;

**Comment by XtremePlayzCODE** [comment]
2. not good enough grammar, cant help

**Comment by daniktheboss** [comment]
Or
running = True 
While true:
     'Whatever'
