### ISSUE TITLE
How to display on wordpress

### ISSUE THREAD

**Issue by Caibiy** [mattboldt/typed.js#178]
hi guy,i am Chinese student ,my english is poor 
Can you help me, I need your help very much. 
my site is base on Wordpress,i want use typed.js
![wg r6 7 vlbluok3zqin v](https://cloud.githubusercontent.com/assets/16449809/17763016/31598546-6548-11e6-9d54-58af1f34be0b.png)
![nywka_w8adk9w8fm29tb z0](https://cloud.githubusercontent.com/assets/16449809/17763017/31609e62-6548-11e6-9ac5-25bc36714cd9.png)
![a gwhrvn2o 8uv02pidb](https://cloud.githubusercontent.com/assets/16449809/17763042/65409e44-6548-11e6-8aae-6a10ad617b3b.png)

If you know the problem, please explain in detail. 
thank you very much

**Comment by flackjap** [comment]
You need to assign jQuery function object to the $ var.
Either change $ to jQuery in your screenshoted code part (e.g. _$(document).ready_... will be _jQuery(document).ready_...) or wrap that whole part with a self invoking anonymous function expression and provide a global jQuery as a parameter to it _(function($){ ...your code... })(jQuery);_
