### ISSUE TITLE
HTML tags not functioning within typed content

### ISSUE THREAD

**Issue by rchliu** [mattboldt/typed.js#183]
HTML tags don't currently display their proper effects when they are placed inside the strings for the typing function, as provided in the sample code:

```
$(".element").typed({
    strings: ["Typed.js is a <strong>jQuery</strong> plugin."],
    contentType: 'html' // or 'text'
});
```

Despite `contentType` being set to `html`, the above snippet outputs the string

> Typed.js is a <strong>jQuery</strong> plugin.

instead of

> Typed.js is a **jQuery** plugin.

**Comment by BokaBokaWeb** [comment]
Same problem...

**Comment by amitsingh9thjan** [comment]
I have used <b> tag and it works fine. You can check here http://simplemetrics.cloud/

**Comment by atgeorgekary** [comment]
What do you mean by "proper effects"?
Is the <strong> tag missing from the markup?
