### ISSUE TITLE
Variable typeSpeed

### ISSUE THREAD

**Issue by NoooneyDude** [mattboldt/typed.js#190]
Currently, we can indicate the typing to pause with ^[delay] midsentence.

How can it be done such that the typing speed is variable?

As an example:

`strings: [
    "^1000This standard typing speed as indicated per typeSpeed property.<br>" +
    "^1000~50This is a slower typing speed as expressed after the ~~ key.<br>" +
    "^1000~-50This is a faster typing speed.<br>" 
],`

**Comment by dgramop** [comment]
Could you try concat-ing strings with a separate variable?
