### ISSUE TITLE
Awesome tool bro, but i have a problem "preStringTyped not working - need help"

### ISSUE THREAD

**Issue by pallu87** [mattboldt/typed.js#192]
Hi,
       I am using your tool to make a nice feature. However the preStringTyped  call is not working. onStringTyped is working perfectly fine. Can you please help, its urgent

Please check the code here, its a simple html and javascript.
http://mypeacefulcorner.com/index_test.html

- Regards
- Palash

**Comment by pallu87** [comment]
Hi Matt, I think i found out the problem. when the string is 

 <p><span class="">welcome to</span><br/><span class="color-light1">your peaceful corner.^2000</span></p>

curStrPos starts with 14 instead of 0. no idea why. when I remove the span, it begins with 0 as usual.

**Comment by pallu87** [comment]
`i mean <span class="">welcome to<`

**Comment by pallu87** [comment]
Ya i got the issue, when the element is html , it takes the curStrPos  as the first element ty type, but preStringType already takes current position as 0.

```
if (curStrPos === 0) {
							self.options.preStringTyped(self.arrayPos);
						}
```
so it does not kick off. 

**workaround: this is resolved by adding a small space at the start before the html tag.** 

anyway, bro, nice work ! keep it up !

**Comment by untzstudio** [comment]
Hey Pallu! I just wanted to know what you mean by "adding a small space before the HTML tag", because I have the same issue and your solution was not evident to me in your code. Could you elaborate a bit on how you worked around this issue, please? I would greatly appreciate it!

Thanks!

**Comment by pallu87** [comment]
Sure, check out - http://mypeacefulcorner.com/ source. 

basically define your content with one additional space if u r using html right off the bat 

`<p line="5"> <span class="control" imageSlide="" ><span class="">so do you...</span></span></p> `
 can u see the single space before the first span tag ? That lets the framework know that content has started. Hope this helps. :)

**Comment by marabesi** [comment]
#96
