### ISSUE TITLE
Something weird with cdnjs' minified-typed.js

### ISSUE THREAD

**Issue by initbar** [mattboldt/typed.js#194]
Using typed.js resting on [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/typed.js/1.1.4/typed.min.js) to run my configuration (below) causes 100% cpu usage in Google Chrome. Although other browsers have not been tested, I reckon the outcome will remain the same. Moreover using the [1.1.4 release](https://github.com/mattboldt/typed.js/releases/tag/v1.1.4) on GitHub only terminates the loop but cpu resource remains stable.

At this moment, I'm not sure if there is a bug with the javascript minifier,  the typed.js, or just my browser setting, but loop does not occur with `<<` string and cdnjs' version causes hangup.
### Problematic Configuration

``` javascript
$(function(){
  $('#test a').typed({
    contentType: 'html',
    strings: [
      'test',
      "<<"  // bug?
    ],
    shuffle: false,
    typeSpeed: 50,
    backSpeed: 50,
    backDelay: 1000,
    showCursor: false,
    loop: true
  });
});
```
### Demo

The typed.js configuration is same for both demos but first one uses `1.1.4` from cdnjs and latter uses from GitHub release.

https://initbar.surge.sh/test/typedjs-cdnjs/ (100% cpu usage)
https://initbar.surge.sh/test/typedjs-original/ (loop never occurs)

**Comment by Orlandster98** [comment]
@initbar Does it still happen?

**Comment by initbar** [comment]
@Orlandster98 I'll verify it tonight (but it was probably local setting).
