### ISSUE TITLE
Can Someone tell me what am I doing wrong. Please I need help with this.

### ISSUE THREAD

**Issue by Beninegoita** [mattboldt/typed.js#196]
I am trying to get my website work with this awesome feature but it is not working. Could someone please tell me what am I doing wrong? Greatly appreciated! https://www.groupeverest.com/contact-us/
![2016-10-09 2](https://cloud.githubusercontent.com/assets/22717179/19216915/dac12c2c-8dc7-11e6-8cde-dd87c661016b.png)
![2016-10-09 1](https://cloud.githubusercontent.com/assets/22717179/19216916/dac668a4-8dc7-11e6-93e5-336460dd79d6.png)
![2016-10-09](https://cloud.githubusercontent.com/assets/22717179/19216917/dacbd44c-8dc7-11e6-89f8-21cb3f7137d3.png)

Benjamin,

**Comment by atgeorgekary** [comment]
Hey Benjamin, your typed function seems fine at first glance. However, a onePageNav function breaks (not defined) for your sticky header (?). Which results in returning a jQuery error.

Uncaught TypeError: $(...).onePageNav is not a function
onetone.js?ver=0e32adf…:324
