### ISSUE TITLE
Stop the typing when textbox is clicked on

### ISSUE THREAD

**Issue by mawebgeek** [mattboldt/typed.js#202]
I'm wondering if there is a better way to accomplish what I'm trying to do.

I'm using typed.js to have a few suggestions in the search box, but I need it to stop and disappear if the visitor clicks in the box to do a real search.

Here's what I am using right now...

`<script>
$(document).ready(function() {
    $('#search').on('click', function() {
		$('#search').typed({
		strings: ["",""],
		backSpeed: -1000
		});
	});
	$("#search").typed({
		strings: ["wiseacre", "ice box", "dungarees", "sawbuck", ""],
		typeSpeed: 40,
		backSpeed: -20,
		shuffle: false,
		showCursor: true,
		contentType: 'text',
		cursorChar: "|"
	});
	
});
</script>`

This seems like a bit of a hack, is there a more elegant solution?

**Comment by guidoferreyra** [comment]
I have a related question. I want to stop/pause on click but not erase the content. Just stop typing.

**Comment by mattboldt** [comment]
Added on https://github.com/mattboldt/typed.js/pull/264

**Comment by Binternet** [comment]
@mattboldt is it possible for typing to finish in 1 batch once the user clicks it? (like really fast-forward)
