### ISSUE TITLE
v1.1.4 is not published on npm

### ISSUE THREAD

**Issue by FrankFang** [mattboldt/typed.js#207]
https://www.npmjs.com/package/typed.js
1.1.1 is the latest release

But the .reset() API is buggy.

**Comment by joejordanbrown** [comment]
@FrankFang

For v1.1.4 
npm install mattboldt.typed.js
https://www.npmjs.com/package/mattboldt.typed.js

**Comment by FrankFang** [comment]
It's another package, I think.

**Comment by joejordanbrown** [comment]
It's the latest version. I published it awhile back because the other one is not getting updated to the latest version.

**Comment by FrankFang** [comment]
I got it.
It's nice if the author @mattboldt  pushes the latest version to npm.
