### ISSUE TITLE
Type pausing and SEO friendly?

### ISSUE THREAD

**Issue by EzraLopez** [mattboldt/typed.js#212]
Is it possible to get strings from static HTML (SEO Friendly) and also do type pausing?

**Comment by altafhpatel** [comment]
HTML from static Content. By default typed-string has display none. Use CSS to make it display block and then small fonts. 

**HTML**

` <div id="typed-strings">
    <p>Sometimes</p>
    <p>You just Gotta Stay <strong>Silent</strong></p>
</div>
<span id="typed" class="h1 text-center center-block stringer"></span>`

**Js**

`<script>
	document.addEventListener('DOMContentLoaded', function(){
		Typed.new('#typed', {
			stringsElement: document.getElementById('typed-strings'),
			contentType: 'html',
		});
	});
</script>`

Hope it will help

**Comment by EzraLopez** [comment]
Not sure how this is related @altafhpatel

**Comment by altafhpatel** [comment]
@EzraLopez  you can read the documentation the above example i write is SEO friendly. 

[https://github.com/mattboldt/typed.js#strings-from-static-html-seo-friendly]

**Comment by EzraLopez** [comment]
@altafhpatel can you do type pausing and have it SEO friendly as well?

**Comment by altafhpatel** [comment]
@EzraLopez  where are u using this ? mention the address of website

**Comment by yairpe** [comment]
You can try using several spaces for a pause that will not show weird in the html

**Comment by dgramop** [comment]
Maybe a noscript?

**Comment by clkdigital** [comment]
Also would like to know the answer to this...

**Comment by erayerdin** [comment]
@yairpe's method is good, but this is only applicable for spaces. It *naturally* will not give the same experience when you want to pause in the middle of a word.
