### ISSUE TITLE
Displaying text before animation started

### ISSUE THREAD

**Issue by prezenta** [mattboldt/typed.js#213]
Hi,

I'm using typed.js (strings from static HTML) on Wordpress theme. It works, but I have one issue;  when the page is loaded, the text is first visible (for about half a second), than dissaperes when animation of writing text starts.
I could add "display: none;" or "opacity: 0;" to the element, but probably this won't be good for SEO.
Is there any other solution, that text would be hidden before animation starts?

Thank you,
Ales

**Comment by mattboldt** [comment]
The text is hidden w/ display:none anyway, so you could just hide it off the bat. Detect if the client is a search crawler and hide it if not.
