### ISSUE TITLE
Html a link aren't clickable until typing ends

### ISSUE THREAD

**Issue by Larsss** [mattboldt/typed.js#214]
I have an issue where links are not clickable until the string is finished typing, I also noticed they have the same error over at https://envato.com/
My site: http://laenken.dk

**Comment by antonk52** [comment]
Did you try it in different browsers? Worked for me in chrome 55, safari 10 and firefox 50

**Comment by Larsss** [comment]
Hmm strange, It doesn't work for me in firefox 50.1.0 or chrome 55.0.2883.87 m on windows 7

**Comment by mubaris** [comment]
I have the same problem. [Here](http://mubaris.me)

**Comment by tclauzier** [comment]
It looks like a browser/DOM issue (tested Firefox 56 + Chromium 62 on ubuntu). It behaves like the tag content's update temporarily blocks click events.

typeSpeed < 60 is impossible to click.
typeSpeed == 70 is _possible_ (if you click like a maniac)
The slower the typing speed (higher typeSpeed) the better clicks will be caught.

https://jsfiddle.net/tclauzier/jcbqtgrd/3/ (just try to run with different values for the typeSpeed value).

**Comment by angeliski** [comment]
I have the same problem :cry:

**Comment by mattwaler** [comment]
Hey peeps, just in case anybody finds this and wants to implement a fix like I have done, I was able to fix this by writing some JS to create 2 divs, a clickable div with all your content underneath that can be clicked, and an absolute positioned div overlaid on top of it that animates the typing effect to solve this. This can all be implemented via simple data-attributes as well to ensure the typing effect only happens once per element based on an ID. It requires TailwindCSS to work but could easily be adjusted to just use style attributes if you are not using it!

Usage:
```html
<div class="example" data-typed="example">
  <!-- html content -->
</div>
```
Here's the code:

CSS:
```css
[data-typed] {
  opacity: 0;
}
```

JS:
```js
// Add Typing Animation
const typedDivs = document.querySelectorAll('[data-typed]')
typedDivs.forEach(div => {
  const id = div.getAttribute('data-typed')
  const reduced = window.matchMedia("(prefers-reduced-motion: reduce)")

  if (!reduced.matches && !sessionStorage.getItem(id)) {
    // Get div attributes
    const attr = div.attributes

    // Create clickable opaque div
    const clickableDiv = document.createElement('div')
    clickableDiv.innerHTML = div.innerHTML
    for (let i = 0; i < attr.length; i++) {
      const attribute = attr[i];
      clickableDiv.setAttribute(attribute.name, attribute.value);
    }
    clickableDiv.setAttribute('data-clickable', '')
    clickableDiv.removeAttribute('data-typed')
    clickableDiv.classList.add('opacity-0', 'relative', 'z-[1]')

    // Create non-clickable visible div overtop
    const typedDiv = document.createElement('div')
    for (let i = 0; i < attr.length; i++) {
      const attribute = attr[i];
      typedDiv.setAttribute(attribute.name, attribute.value);
    }
    typedDiv.setAttribute('data-typing', '')
    typedDiv.removeAttribute('data-typed')
    typedDiv.setAttribute('role', 'presentation')
    typedDiv.classList.add('absolute!', 'inset-0!', 'size-full!', 'z-[2]!', 'pointer-events-none!')

    // Clean out parent div and insert new divs
    div.innerHTML = ""
    div.appendChild(clickableDiv)
    div.appendChild(typedDiv)
    div.setAttribute('class', 'relative')
    div.removeAttribute('data-typed')

    // Initiate typing effect
    new Typed(typedDiv, {
      strings: [clickableDiv.innerHTML],
      showCursor: false,
      typeSpeed: 1,
      loop: false,
      onComplete() {
        typedDiv.classList.add('hidden!')
        clickableDiv.classList.remove('opacity-0')
      }
    })
    sessionStorage.setItem(id, 'DONE')
  } else {
    div.removeAttribute('data-typed')
  }
})
```
