### ISSUE TITLE
Is there a way to have a static underscore?

### ISSUE THREAD

**Issue by m4ttr33d** [mattboldt/typed.js#219]
I want to be able to have the Typed.js strings type into a static blank. Kind of like a fill in the blank type of thing where the blank is static and the string types into the blank. Thanks!

**Comment by 18zehn** [comment]
I had the same "problem" but I fixed it within my markup. 

`<h1>_ <span class="headline"></span></h1>`

Typed.js fills the headline span and so the underscore is static.

**Comment by mattboldt** [comment]
More of a CSS thing
