### ISSUE TITLE
How to hide the cursor once you're done typing? 

### ISSUE THREAD

**Issue by bexcore7** [mattboldt/typed.js#220]
Have repeat set to false, and I want the cursor to disappear once the strings are done being typed out.
Is there a way to make it visible while typing, and hidden **when done all strings at the end**?

**Comment by MonsterDeveloper** [comment]
use `callback: function() {}`. And hide `span` with class `typed-cursor` using jQuery

**Comment by bexcore7** [comment]
@MonsterDeveloper 

```    
<script>
   $(function () {
            $(".element").typed({
                strings: ["Retailers.", "Property Managers."."],
                typeSpeed: 100
            });

        });`
</script>
```

So what does that look like in here? I am new to JavaScript trying to get this to work.

**Comment by MonsterDeveloper** [comment]
No, no, like that:
```javascript
<script>
    $(function(){
        $(".element").typed({
            strings: ["First sentence.", "Second sentence."],
            typeSpeed: 0,
            callback: function () {
                $(".typed-cursor").hide();
            }
        });
    });
</script>
```

**Comment by bexcore7** [comment]
Thank you!

**Comment by bexcore7** [comment]
Thanks @MonsterDeveloper

**Comment by MonsterDeveloper** [comment]
@bexcore7 You are always welcome:smile:

**Comment by dennisaskeland** [comment]
Or document.querySelectorAll(".typed-cursor")[0].style.display = "none"; for non jQuery solution

**Comment by onetrev** [comment]
Or if using the latest version of the plugin and the recommended setup, you'd do something like this and take advantage of the `onComplete` callback.

```
import Typed from 'typed.js';

var options = {
  strings: ["<i>First</i> sentence.", "&amp; a second sentence."],
  typeSpeed: 40,
  onComplete: function () {
      $(".typed-cursor").hide();
  }
}

var typed = new Typed(".element", options);
```
