### ISSUE TITLE
How to change position and hieght of the cursor

### ISSUE THREAD

**Issue by MonsterDeveloper** [mattboldt/typed.js#221]
I got something like this:

<img width="122" alt="cursor" src="https://cloud.githubusercontent.com/assets/16190582/22893484/dfe06c36-f226-11e6-8617-d04fd6429a35.png">

I want to change height and position of the cursor so it is like this

<img width="163" alt="cursor2" src="https://cloud.githubusercontent.com/assets/16190582/22893567/161d2c94-f227-11e6-98c0-f63f31b9fc68.png">

And matches text's height and position

**Comment by AmirBraham** [comment]
Hi , you can do change the size of the cursor by simply selecting it and changing it using jQuery 
`$(".typed-cursor").css("font-size","xx-large")
`
make sure you place this inside the typed function

**Comment by MonsterDeveloper** [comment]
Thanks!
