### ISSUE TITLE
How to use Supercustom ? (with example)

### ISSUE THREAD

**Issue by Adarsh777** [mattboldt/typed.js#231]

**Comment by Adarsh777** [comment]
Please anyone help me..

**Comment by the94air** [comment]
try http://stackoverflow.com/questions/27985591/typed-js-restrict-first-element-from-backspace
or https://github.com/mattboldt/typed.js/issues/123#issuecomment-166018272

**Comment by Adarsh777** [comment]
Thank you. It help me a lot.
