### ISSUE TITLE
Use of "&" halts progress

### ISSUE THREAD

**Issue by Naoto-Ida** [mattboldt/typed.js#232]
There's a bug where using `&` in your text halts progress of the typing.
Right now I worked around it by just writing it out, but is there a fix for this?

**Comment by dgramop** [comment]
Try escaping the character for javascript: http://www.freeformatter.com/javascript-escape.html
If that doesn't work, try escaping with HTML

**Comment by mattboldt** [comment]
You gotta use `&amp;` because it supports HTML chars, which start with `&`;
