### ISSUE TITLE
Page height problem

### ISSUE THREAD

**Issue by lucaswxp** [mattboldt/typed.js#236]
Hey guys.

I have a weird bug, where the page height is far above the actual content. I traced back to typed.js script. If I remove it from my assets, the page loads with normal height.

http://frontend-v3.doare.org/home.html

I'm still unsure what properties, exactly, typed.js is messing around to do this. Any ideas?

**Comment by mattboldt** [comment]
Your CSS is setting the typed-cursor's line-height to `9999999em`
