### ISSUE TITLE
1.1.6 version on NPM

### ISSUE THREAD

**Issue by demyan1411** [mattboldt/typed.js#237]
Please add 1.1.6 version to NPM.
Now there is only 1.1.1 version =(

**Comment by mattboldt** [comment]
Looks like @byoth is the one that posted Typed.js to npm, so I don't have access to it. Any idea how to gain ownership of the package?

**Comment by nickjvm** [comment]
@mattboldt NPM has documentation on resolving disputes. Though this isn't really a "dispute," this may help you get in touch with the owner of the package: https://docs.npmjs.com/misc/disputes

**Comment by alexdevero** [comment]
Yes, it would be great if the latest version of Typed.js was on npm. Now, the version on npm is very old and requires jQuery to run.

**Comment by mattboldt** [comment]
I've emailed the owner of the NPM project!

**Comment by dmitrykiselyov** [comment]
@byoth @mattboldt Thanks!
The version on NPM is latest (1.1.7) now.
