### ISSUE TITLE
typeSpeed not working

### ISSUE THREAD

**Issue by IsaacHub** [mattboldt/typed.js#238]
`typeSpeed:0` and `typeSpeed:5` are exactly typing at the same speed. What am I missing? Is this a bug?
Same with the `startDelay` and `backSpeed`.

**Comment by bpcoxjr** [comment]
I'm having the same issue.

**Comment by jsilveira** [comment]
The problem seems to be that the speed of each type is determined by:

`Math.round(Math.random() * (100 - 30)) + this.typeSpeed;`

Basically, there is a random 0-70ms delay no matter what the typespeed was set to.

**Comment by Orlandster98** [comment]
I have the same problem on one of my installations. I will try to reproduce it.

@jsilveira This is not causing the error.  It's just used to "humanize" the typing. So it takes the `this.typeSpeed` and adds a random number to it. So the delay is little bit different for each letter. (like a real human)

The error seems to come from `this.typeSpeed`, but as I said I have to check it.

**Comment by jsilveira** [comment]
@Orlandster98 Yes, that is exactly what I understood from the source code. When your typing speed has  a random addition of 0-70ms, an average addition of 45ms, for example, makes (0+45)ms VERY similar to (5+45)ms, reducing the impact typeSpeed has for small values.

**Comment by mattboldt** [comment]
Perhaps I can convert the times to some kind of words per minute format. Right now to get really fast typing, you could `typeSpeed: -100`, which isn't very intuitive. I'll look into that on https://github.com/mattboldt/typed.js/pull/264

**Comment by alin262** [comment]
is there any fix for this

**Comment by rohanashik** [comment]
what is the fix?
