### ISSUE TITLE
Click on input field to type

### ISSUE THREAD

**Issue by victorngkp** [mattboldt/typed.js#246]
I have the following input and script:

`<input type="search" name="term" id="term" class="search--input" placeholder="" autocomplete="off">`

```
document.addEventListener("DOMContentLoaded", function(){
    Typed.new(".search--input", {
      strings: ["where ^150do ^150you ^150want ^150to ^150go?", "new ^150york ^150city", "thailand", "france"],
      typeSpeed: 60,
      backSpeed: 50,
      startDelay: 200,
      backDelay: 400,
      loop: true
    });
  });
```

The `loop` is set to `true`. When I click on the input field, I don't want the `Typed` to keep typing, but stop it, so that I can enter my own values to the input field. A callback like on click the input element, then clears the value or stops the typing would be great.

**Comment by Orlandster98** [comment]
@victorngkp I'm looking forward to create a pr for a `stopTyping` function, which can be triggered individually.

**Comment by mattboldt** [comment]
You can use `attr: 'placeholder'` to achieve this. However, on https://github.com/mattboldt/typed.js/pull/264 I'm adding focus and blur event handlers for inputs so the typing will pause on focus and continue on blur.
