### ISSUE TITLE
Add partial delete of the sentence

### ISSUE THREAD

**Issue by macmladen** [mattboldt/typed.js#248]
As you have noticed yourself, it should be possible to delete just a part of the sentence, not the whole line. Something similar is suggested by #156 and you made a **patch** yourself by hacking the JS for your own site.

The question is how is it best done?

There is approach by @Zhouzi **TheaterJS** where he uses many arguments to control rendering of one line (check here: http://codepen.io/Zhouzi/pen/JoRazP/ )

```
.addScene('luke:Nooo...', -3, '!!! ', 600, 'No! ', 600)
```
Essentially,

- **string** is just typed
- **negative number** is the number of characters deleted
- **positive number** is the number of milliseconds wait

In that library **bonus option** is the ability to generate _mistakes_, when typing you can control how often it makes typos that it also corrects (`accuracy` variable).

**Comment by Orlandster98** [comment]
@macmladen I will do a pr for this. There's already `^` this identifier for the delay between words. I think a similar approach would be great. 

Something like this.
`strings: ["First ^1000 sentence.", "-9 Second sentence."]`

At the beginning of the string you have the option to specify how much characters of the last word will be deleted. What do you think?

**Comment by mattboldt** [comment]
@Orlandster98 I like that design a lot! However there would need to be a protected character. If someone were to intend `-9` to be printed, it would break. Perhaps a `~9 => only delete 9 chars`

**Comment by Orlandster98** [comment]
@mattboldt great! yes `~9` this is a very good approach. 
I have to do it like this: `strings: ["First ^1000 sentence. ~9", "Second sentence."]`. To call the `backspace` function with an extra argument which includes the number of characters to remove. You will see it in the pr in the next few days.

**Comment by mattboldt** [comment]
This is getting added on #264
