### ISSUE TITLE
How to reinitiate the plugin?

### ISSUE THREAD

**Issue by nisar5071** [mattboldt/typed.js#25]
Hi there,
  I am using the plugin in multiple sections of my page,and each section has a different text and it works fine on load.Now user can see each section at a time in the page and on scroll next or previous section is shown to user. and I have to show typing effect when each section is shown but I am not able to reinitiate it.
  Can you please help me out for how to reinitiate the plugin ?

Cheers
Nisar

**Comment by ZeeCoder** [comment]
There's a reset function hidden in the code. `$().typed('reset')`.

**Comment by mattboldt** [comment]
My bad, that should be in the Readme

**Comment by metaarts** [comment]
The function `$().typed('reset')` throws an error if the option `showCursor` is `false`. I had to comment out the line 327 (`this.cursor.remove();`) for me.

**Comment by ZeeCoder** [comment]
I patched that some days ago. There's a pending pull request.

**Comment by lambdamusic** [comment]
Hi - thanks for this fantastic plugin. So much fun :-) 

Just to clarify though: the `reset` keyword removes the html element completely right? 

So if at page load I run this code (a)

```
$(".element").typed({
            strings: ["First sentence.", "Second sentence."],
            typeSpeed: 100
        });
```
And then do `$(".element").typed('reset')` - when I run again (a) nothing happens. 

My `<span class="element>` needs to be recreated...

**Comment by saviourofdp** [comment]
I had a similar issue where the plugin stopped when applied to an element which had already been used - my solution was to use `$.removeData()`, ie `$(element).removeData();  $(element).typed({ ... })`.

I think this is caused in `$.fn.typed()` at `data = $this.data('typed'), ... if (!data) $this.data('typed', (data = new Typed(this, options)));` so `new Typed()` doesn't get called if the element already has the `data` attribute.

**Comment by introvert** [comment]
The same issue here.. please fix this, thanks

**Comment by Chalks** [comment]
I know this is an old issue, but...

using saviourofdp's solution worked, but I wanted it to stop mid-loop if it was currently processing, so I had to stop the interval manually.  like so:

        clearInterval($('.element').data("typed").timeout);
        $('.element').removeData('typed');

otherwise the callbacks kept getting triggered even after the old typed instance was "removed".

**Comment by mattboldt** [comment]
this should be fixed with the `reset` method

**Comment by iamchriswick** [comment]
@mattboldt you closed this, but is it fixed?
