### ISSUE TITLE
loop is not working properly with fadeOut set to true

### ISSUE THREAD

**Issue by monospaceberlin** [mattboldt/typed.js#254]
Hi!

I could not find any documentation about the following issue:

When the option "fadeOut" is set to "true",  the whole scene is not starting from the beginning. While set to false it is using the normal backspace appearance and it starts from the beginning.

Error in the console is:
`undefined is not an object (evaluating 't.substr')`
found: typed.min.js:1:2167

using current version of typed.js

**Comment by Orlandster98** [comment]
@monospaceberlin can you create a plunkr with the issue? I will have a look on it. Just with `fadeOut` to `true` I can't reproduce it.

**Comment by monospaceberlin** [comment]
Thanks for the quick response. You could have a look on mll.mono-space.com to examine the code. Forgot to post that.

**Comment by Orlandster98** [comment]
@monospaceberlin Thanks for the code snippet. Ok, now I got it. The `infinite` loop is not working with `fadeOut: true`. This is definitely a bug. I will have a look on it in the next few days and submit a pr referenced to this issue. THX for the bug report.

**Comment by monospaceberlin** [comment]
@Orlandster98 This issue isn't just limited to the infinite loop. Any 'loopCount' will cause this behaviour.
Thank you for attending to this matter.

**Comment by Orlandster98** [comment]
@monospaceberlin I've created a pr. Would be great if you could check the result: https://jsfiddle.net/1dL5xb32/ THX in advance!

**Comment by monospaceberlin** [comment]
@Orlandster98 Perfect. That seems to work fine. Thanks for the quick fix!

**Comment by frankmoshe** [comment]
The proposed solutions is not working when showCursor: false
https://jsfiddle.net/1x4s8jaa/
