### ISSUE TITLE
Change Text Programatically

### ISSUE THREAD

**Issue by aayusharyan** [mattboldt/typed.js#257]
Allow the Script to change the values of the text defined in the Strings Array, and thus allowing the code to run asynchronously with texts which can be changed programatically.

**Comment by Orlandster98** [comment]
@aayusharyan Sounds interesting. Is definitely possible to implement. I think we just have to overwrite the existing array. The thing is when should it affect? any idea about this? In my oppinion it makes sence to allow these changes before a word's getting typed. I'm sure it's not the wanted behavior to change the current array field?

**Comment by mattboldt** [comment]
This is being added to https://github.com/mattboldt/typed.js/pull/264 and will work w/ the `onStringTyped` style callbacks.
Example:
```
      onStringTyped: function(i, self){
        self.strings[2] = 'My new string for array position 3';
      },
```
I'll possibly also add adding strings, but that's tbd.

**Comment by mledwards** [comment]
Shouldn't this be on preStringTyped, so you can change it before rendering? I'm still struggling to try and change the content after an asynchronous event.

**Comment by mattboldt** [comment]
> Shouldn't this be on preStringTyped, so you can change it before rendering? I'm still struggling to try and change the content after an asynchronous event.

Could be either. `onStringTyped` could be used for updating strings just after the previous line has been typed.
