### ISSUE TITLE
Need help to make my TypedJS strings appear coherently

### ISSUE THREAD

**Issue by tonystaark** [mattboldt/typed.js#260]
I have few strings of different length each needs to be shown with typedJS on my website. Below are just a small sample of a big pool of strings I need to output.

If there is a string which is extremely long(as shown by $("#apple), it takes a lot more time to be typed out than other strings that are shorter.

Previously I put a set timing as below, which did not produce the desired output.

     $("#apple").typed({
        strings: ["I love to eat pizza because it is tasty", strB1, strC1, ...],
        typeSpeed: 0,
        loop: true
     })

     $("#orange").typed({
        strings: ["^3000 orange", strB2, strC2,...],
        typeSpeed: 0,
        loop: true
     })

     and many more...
It is not possible for me to manually change the timing of each typedJS as the strings are taken from a huge data file. In typedJS, is there anyway for me to have all strings(for e.g."I love to eat pizza because it is tasty" and orange to be typed out, before they are all cleared at the same time. Then the next set of string, setB (with strB1, strB2, strB3) to be rendered and cleared at the same pace, before setC's turn (with strC1,strC2, strC3 ...), and so on and so forth ?

To provide an analogical explanation:

Suppose the first group of horses, group A is set for racing. Though each one has different speed and arrive at different timing, all horses have to obey the rules: They are only allowed to leave the checkpoint after everyone has gathered. Next, it's turn for another group of horses (group B) for racing, and the same rule applies. After the last group of horses (let say group Z) has done racing, group A will resume racing again, and the process keeps on looping.

**Comment by Orlandster98** [comment]
@tonystaark is it possible to create a plunkr. I will have a look on it.

**Comment by mattboldt** [comment]
You could probably hook this up w/ the `onStringTyped` and `preStringTyped` callbacks to do something like this. I don't see how it could be added as a built in feature though.
