### ISSUE TITLE
Issue using Loop

### ISSUE THREAD

**Issue by ptums** [mattboldt/typed.js#262]
Hello,

I am looking for some assistance on how to use ``` loop: false ``` I set it to true and now I get an error after it loops through my array of text once. The error I get is this:

```
typed.min.js:1 Uncaught TypeError: Cannot read property 'substr' of undefined
    at typed.min.js:1
```

Am I initializing  the loop properly? This is my code its pretty much boilerplate.

```
  document.addEventListener('DOMContentLoaded', function(){
      Typed.new('#target-headlines', {
        strings:[
        'I ',
        'Like',
        'Eggs',
        ],
        typeSpeed: 30,
        fadeOut: true,
        fadeOutClass: 'typed-fade-out',
        fadeOutDelay: 200, // milliseconds
        showCursor: true,
        shuffle: true,
        loop:true,

      });
  });
```

Any help or advice will be greatly appreciated.

Thank you

**Comment by Orlandster98** [comment]
@ptums Hey, try to use the latest version directly from Github. I've fixed this some weeks ago.

**Comment by igorA53** [comment]
@Orlandster98 : are you sure this fix is merged in the master branch?  I've got the same error and tried it with the plain source of typed.js (not minified), but still the same error.

**Comment by Clebiez** [comment]
Hi all

I have the same issue, it's due to the smart backspace, pass it to false like this in your options object :
`{
   smartBackspace: false
}`

**Comment by mattboldt** [comment]
This is fixed on v2.0.1!

**Comment by Clebiez** [comment]
Ahah yeah you have been faster than me on fixes for that and for the cursor. Thank you.

**Comment by ptums** [comment]
Thank you for your help trying it now!
