### ISSUE TITLE
Uncaught ReferenceError: Typed is not defined

### ISSUE THREAD

**Issue by medicsteven** [mattboldt/typed.js#266]
I am getting the following error on my website this morning: Uncaught ReferenceError: Typed is not defined. I am using the RAW GIT link here https://cdn.rawgit.com/mattboldt/typed.js/master/js/typed.js.

My Code:
`var typed = new Typed('.element', {
	    stringsElement: '#typed-strings'
	  });`

Any ideas?

**Comment by mattboldt** [comment]
That rawgit link is old & empty. Here's a new rawgit link
https://cdn.rawgit.com/mattboldt/typed.js/master/lib/typed.min.js

**Comment by Ramsz** [comment]
When I use the new one I keep getting:

```
Uncaught TypeError: Cannot read property 'tagName' of null
    at t.value (typed.js:sourcemap:10)
    at new t (typed.js:sourcemap:10)
    at (index):201
```

Instead of Typed is not defined

**Comment by mattboldt** [comment]
Could you make a jsfiddle using your config and the latest typed.js build?
Thanks

**Comment by rohanxh** [comment]
I have put the cdn link to my wordpress website it is showing  "Uncaught TypeError: Cannot read property 'tagName' of null" Error

**Comment by seanfrasure** [comment]
I am having the same issue.

**Comment by rohanxh** [comment]
Hi,

Sorry for very late reply. I have found the error and cleared the issue let
me know if you need my help.

Thanks
Muhammad Rohan

**Comment by CreaRo** [comment]
Please do mention how you solved it!

**Comment by rohanxh** [comment]
Please share link of your website or send me your code I will check and
guide you through it
