### ISSUE TITLE
Clear or complete partial placeholder on focus

### ISSUE THREAD

**Issue by guillermovs** [mattboldt/typed.js#269]
### Description

When using typed.js on an input field (attr:placeholder) the typewriting stops (as it should, on focus), but the placeholder isn't cleared.

This means that the user might start typing with half a word or sentence showing as a placeholder 

### Demo

https://jsfiddle.net/oashkptL/

**Expected behavior:**

Clear placeholder on focus. If on blur input is empty or has not been changed, resume typed.js loop.

**Actual behavior:**

Input field placeholder does not clear.

### Additional Information

I have tried manually clearing the placeholder both "on focus" and with the "onStop" method, but it misbehaves and keeps on typing at least one letter (might be due to the typing delay).

**Comment by mattboldt** [comment]
Hm. I purposely left the placeholder text visible because that's what placeholders are there for. Once you start typing, it gets hidden automatically.

It should behave just like any placeholder:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder

Perhaps the UX would be better if the sentence completed its typing on focus, so the input isn't left with a half-completed word?

**Comment by guillermovs** [comment]
If the string is visible or being written it should probably complete it, you're right; but if it is being deleted maybe it's best if it is cleared, rather than half written or rewritten.

For the time being I'm clearing the placeholder by invoking `typed.reset(restart=false)` onFocus. This, however uncovered another issue, which is that if your strings are shuffled, `onStringTyped` does not give you the right `arrayPos` for the current string.

**Comment by iamdubx** [comment]
you can use CSS to make placeholder invisible

**Comment by cyrilchapon** [comment]
Some working workaround to "finish sentence" manually ? :)

**Comment by cyrilchapon** [comment]
With https://github.com/mattboldt/typed.js/issues/335 in mind, we should define here a behavior when initial static html placeholder is set (maybe resetting it to that state ?)
