### ISSUE TITLE
Getting backspace cursor in front of string.

### ISSUE THREAD

**Issue by Adarsh777** [mattboldt/typed.js#271]
As my below code on excuting iam getting a backspace cursor fixed in front of string. i tried some way but it didn't work. Is anyone aware of how to remove it from the front of the string. Please Help me
(https://codepen.io/Codehunt/details/gRKQOW/)

**Comment by Adarsh777** [comment]
Whats wrong with my post ?

**Comment by mattboldt** [comment]
- You deleted all the template issue code I wrote that requires you to provide details about your issue
- You're using code directly from my personal website `https://www.mattboldt.com/demos/typed-js/js/typed.custom.js`
- Related to the above, that code is very out of date. Use the latest release on GitHub / NPM / Bower
- You need to detail the effect you're going for. It looks like you want to type "Hello", keep that word shown, and type more sentences after. This can be achieved using `smartBackspace` which can be found in the readme.

**Comment by Adarsh777** [comment]
Ok.
I really apologize for that.
Sorry
