### ISSUE TITLE
preStringTyped might not be fired if smartBackspace is true

### ISSUE THREAD

**Issue by orensol** [mattboldt/typed.js#272]
### Description

preStringTyped fired only for first string, if smartBackspace is true, and strings have the same characters in the beginning, because curStrPos never reaches 0.

### Steps to Reproduce
1. Have two typed strings with same initial characters at their beginning. 
2. Have a callback function to preStringTyped
3. preStringTyped would fire only on the initial string typing once, and would not fire again, even if looping.

**Expected behavior:** preStringTyped should fire when each string is typed.

**Actual behavior:** preStringTyped fires only once

**Reproduces how often:** 100% if strings have same character beginning.
### Additional Information

To solve: should consider different mechanism to fire this event, independently of curStrPos.

**Comment by hrishabh23** [comment]
Will it be okay if preStringTyped is called when the cursor just starts typing the "not common part" of next string?
Because this can be done very easily by calling preStringTyped when we set stopNum in case  smartBackspace is enabled.

**Comment by blunket** [comment]
Ran into this problem myself. Frustrating. Fortunately it's ok for me to turn off smartbackspace.

**Comment by marabesi** [comment]
#96  related?
