### ISSUE TITLE
typed.js is not available from rawgit

### ISSUE THREAD

**Issue by maxneat** [mattboldt/typed.js#273]
Hi, the typed.js file is not available from rawgit
https://cdn.rawgit.com/mattboldt/typed.js/master/js/typed.js respond with a 404

Just wanted to know if this is a temporary issue or the file has been moved somewhere else.

Max

**Comment by mattboldt** [comment]
Sorry! new path is in `/lib`
https://cdn.rawgit.com/mattboldt/typed.js/master/lib/typed.min.js

**Comment by maxneat** [comment]
Thank you Matt!
