### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by sixfootjames** [mattboldt/typed.js#274]
### Description

I have loaded the JS from your RAWGIT file @mattboldt  in the head of my WordPress header.php

`<script src="https://cdn.rawgit.com/mattboldt/typed.js/master/lib/typed.min.js"></script>`

I have tried multiple ways next to implement the Text typing but this is the last one I tried.

> <script>

> !function($){
>     "use strict";
>     var typed = new Typed('.element', {
>         stringsElement: '#typed-strings'
>     });
>  }(window.jQuery);
> </script>

>  [div id="typed-strings"]
>     [p]Typed.js is an <strong>Awesome</strong> library.[/p]
>     [p]It <em>types</em> out sentences.[/p]
> [/div]
> [span id="typed"][/span]

I have loaded the JS in the footer and the header to see where I might be going wrong but I keep getting this error in my Console

typed.min.js:10 Uncaught TypeError: Cannot read property 'tagName' of null
    at t.value (typed.min.js:10)
    at new t (typed.min.js:10)
    at sitename.isamazing.co.za/:299
    at sitename.isamazing.co.za/:302

Many thanks

**Comment by sixfootjames** [comment]
Managed to come right, thanks @mattboldt

**Comment by robtesch** [comment]
@sixfootjames may I ask what you did to fix this?

**Comment by fabienpinel** [comment]
@sixfootjames I'm interested by the answer too ;)

**Comment by luisgraterol** [comment]
Would you please explain how you fixed it?? Been struggling for at least an hour now! @sixfootjames @mattboldt @fabienpinel

**Comment by saifat29** [comment]
After being stuck for a while I figured it out.
```<script>
  var typed = new Typed('.element', {
    stringsElement: '#typed-strings'
  });
</script>```
In the Typed constructor you need to replace the .element by your own element ID or CLASS name.

example:-
```
<div id="typed-strings">
    <p>Typed.js is a <strong>JavaScript</strong> library.</p>
    <p>It <em>types</em> out sentences.</p>
</div>
<span id="typed"></span>

```
```
<script>
  var typed = new Typed('#typed-strings', {
    stringsElement: '#typed-strings'
  });
</script>
```

**Comment by shaansheikh** [comment]
@saifat29 Didn't work for me. Still getting the error. Anyone figure it out?

**Comment by neeraj92144** [comment]
@saifat29, Thanks bro, it worked for me

**Comment by LucasMatuszewski** [comment]
I had the same problem, and it started to work for me when I moved the <script> after html element (firstly I tried to put <script> on <header>). Maybe its because of Bootstrap.js? I don't know, but it works for me :)

My code:
```
 			          <div id="content">
	 				<h1>Personalized Training</h1>
	 				<h3>Learn <span id="typed"></span> with best Lecturers</h3>
	 				<hr>
	 				<button class="btn btn-danger btn-lg">Start Now! <i class="fa fa-mouse-pointer" aria-hidden="true"></i></button>

					<div id="typed-strings">
					    <p>Typed.js is a <strong>JavaScript</strong> library.</p>
					    <p>It <em>types</em> out sentences.</p>
					</div>

					<script>
					  var typed = new Typed('#typed', {
					    stringsElement: '#typed-strings'
					  });
					</script>
	 			</div>
```

**Comment by dougfabris** [comment]
I was trying to solve the error "Uncaught TypeError: Can not read property 'tagName' of null". It was happening because I was using an external script and was calling the type.js only on home page, so the jquery plugin was looking for my typed elements throughout my document. What I did was simply add an if loop for it to just execute on home. I hope it helps someone.
```
if( $('body.home').length ){
    //TYPED ELEMENTS
    var typed = new Typed(".type span", {
      // Waits 1000ms after typing "First"
      strings: ["land^500", "sea^500", "air^500"],
      typeSpeed: 100,
      backSpeed: 100,
      smartBackspace: true,
      loop: true
    });
  }
```

**Comment by TillKoch** [comment]
I solved this by waiting for the document to be fully loaded (without jQuery) :

window.onload = function () {
    new Typed('#typed', {
         strings: ["First sentence.", "Second sentence."],
	typeSpeed: 30,
	fadeOut: true,
	});
}

**Comment by hassan-dev** [comment]
> $(document).ready(function() {

thanks man, it worked

**Comment by Deevoid** [comment]
Anyone tried it on React js??
Please share how you did it.

**Comment by dougfabris** [comment]
@Deevoid he is an example: https://jsfiddle.net/mattboldt/ovat9jmp/
Found in documentation

**Comment by IZUNA894** [comment]
> Anyone tried it on React js??
> Please share how you did it.
> @mattboldt I can't find the tutorial helpful for me.

i also got this error on react.js

**Comment by william-ch3n** [comment]
Hello guys, I also got the same problem a while ago when I tried using it with _React._

And here is the point like @tannker said:
It seems the instance of Typed needs to be initialized within **componentDidMount(),** so if you are using functional component, **make sure the instance is initialized within useEffect() hook**.

And here is the official code sample provided by the author for functional component:
https://jsfiddle.net/mattboldt/60h9an7y/

Hopefully this can help you!

**Comment by walkingkindle** [comment]
Not sure if this is helpful, but try to put the typed.js script at the end of the page, footer part, so that all the dependecies can be loaded BEFORE the typed.js script initializes.
