### ISSUE TITLE
Backspace/back-type is deleting whole words rather than character-by-character

### ISSUE THREAD

**Issue by Shelim-S** [mattboldt/typed.js#275]
Hey, not sure why it's behaving like this. Possible bug?

**Comment by Shelim-S** [comment]
Further analysis indicates the backspace/back-type is too fast. How can I slow down the process?

**Comment by Shelim-S** [comment]
Never mind - found the respective variable! 👍

**Comment by Taewa** [comment]
@Shelim-S I will be appreciated if you can tell me how you solved.

I could solve by adding an empty string in `strings` option.
```
strings: ['some text', , ''],
backSpeed: 30,
backDelay: 2500
```
I don't know if this is the best way.
