### ISSUE TITLE
 t.el is null

### ISSUE THREAD

**Issue by Syltan-Adam** [mattboldt/typed.js#276]
### Description
I'm using Typed.JS on rawgit. I've tried direct sourcing your code using <script> and using src. 
Whenever I try to use it, I usually get a console error.

**Expected behavior:** No logged error

**Actual behavior:** No output. Console records - TypeError: t.el is null[Learn More]

**Reproduces how often:** 100%
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
The site is on TOR on a internal part of the page. I can send screenshots, but am unwilling to reproduce credentials for testing.

```
<head>
<!-- ... -->
<script src="https://cdn.rawgit.com/mattboldt/typed.js/master/lib/typed.min.js"></script>
<!-- ... -->
</head>
<body>
<!-- ... -->
<script>
var typed = new Typed('.element', {
  strings: ["First sentence.", "Second sentence."],
  typeSpeed: 30
});
</script>
<span id="element"></span>
</body>
```

**Comment by Syltan-Adam** [comment]
After attempting to use the same code on Github, it is still no good.
http://i.imgur.com/9jgBEry.png -- My code
http://i.imgur.com/OnnbhaC.png -- The page

**Comment by mattboldt** [comment]
You're using a `<span class="element">` however in the Typed config you're specifying an ID with `new Typed('#element', ...)`

**Comment by Syltan-Adam** [comment]
TypeError: this.el.tagName is undefined.
This is still an issue. I fixed the tag error and it's still there.

**Comment by mattboldt** [comment]
Here's a fiddle with working code: https://jsfiddle.net/mattboldt/1xs3LLmL/

It may be because your JS is above the HTML element that it's trying to manipulate. JS (that's not in the head) should be at the very bottom of the body.

**Comment by Syltan-Adam** [comment]
http://i.imgur.com/7JBYwWc.png


*-------*

*Adam Hendi,*

*Owner of DEN and postmaster of Mymail.*

*https://Maimail.co/ <https://Maimail.co/>*
*Need a new privacy-oriented email? Email postmaster+signup@maimail.co
<postmaster%2Bsignup@maimail.co> for a lower rate of $3.90 CAD!*

**Comment by mattboldt** [comment]
this screenshot shows Typed.js 1.1.7 from cloudflare

**Comment by Syltan-Adam** [comment]
I've still been trying all of them.


*-------*

*Adam Hendi,*

*Owner of DEN and postmaster of Mymail.*

*https://Maimail.co/ <https://Maimail.co/>*
*Need a new privacy-oriented email? Email postmaster+signup@maimail.co
<postmaster%2Bsignup@maimail.co> for a lower rate of $3.90 CAD!*

**Comment by terryjiang2020** [comment]
I ran into a similar issue (at least the same error log). Any update here?

**Comment by sum1there** [comment]
Here's the solution that worked for me:

Put your `<script>` after the `<span>` instead of before it. Let's use a part of your code as an example.

Here, the script is before the element. Since it's before, the script doesn't know that the `<span>` element exists, therefore it is returned as `null`. To fix this, we change this code from this:
```html
<!-- script BEFORE span -->
<script src="https://cdn.rawgit.com/mattboldt/typed.js/master/lib/typed.min.js"></script>
<script>
var typed = new Typed('.element', {
  strings: ["First sentence.", "Second sentence."],
  typeSpeed: 30
});
</script>
<span id="element"></span>
```
To this:
```html
<!-- script AFTER span -->
<script src="https://cdn.rawgit.com/mattboldt/typed.js/master/lib/typed.min.js"></script>
<span id="element"></span>
<script>
var typed = new Typed('.element', {
  strings: ["First sentence.", "Second sentence."],
  typeSpeed: 30
});
</script>
```

Hope this helps anyone who comes across this problem.

**Comment by netbrothers-tr** [comment]
In case you're using TypeScript: In the type declaration file, the class constructor looks like this,

```ts
constructor(elementId: any, options: TypedOptions)
```

which implies you could pass an element ID, which is not the case. You rather pass a jQuery-like selector (`'#myElement'` for instance). Hence, the type declaration isn't transparent about the following behaviour.

```diff
- const typed = new Typed('myElement', { ... });  // produces error
+ const typed = new Typed('#myElement', { ... }); // works, **if** element exists
```
