### ISSUE TITLE
React support - perhaps add to docs?

### ISSUE THREAD

**Issue by nathanhleung** [mattboldt/typed.js#277]
Hi Matt,

Thanks for this library - the typing looks great. It did take me a good bit of time to get started with it though, since I needed to integrate it with React.

I saw there were a few unanswered React issues with questions from people wanting to integrate Typed.js into React. If it's not out of the scope of the project, it could save people some time if there was a small React demo in the readme (I've posted a quick example below based on my usage).

Let me know what you think/whether this is within the scope of Typed.js. If it looks good to you, I'd be happy to submit a pull request and add it to the readme.

Let me know,
Nathan

```js
import React, { Component, PropTypes } from 'react';
import Typed from 'typed.js';

class Typer extends Component {
  static propTypes = {
    strings: PropTypes.arrayOf(PropTypes.string).isRequired,
  };

  componentDidMount() {
    const { strings } = this.props;
    const options = {
      strings,
      typeSpeed: 40,
    };
    // this.el refers to the <span> in the render() method
    this.typed = new Typed(this.el, options);
  }

  componentWillUnmount() {
    this.typed.destroy();
  }

  render() {
    return (
      <span
        ref={(el) => { this.el = el; }}
      />
    );
  }
}

export default Typer;
```

**Comment by mattboldt** [comment]
Very cool! Is there some way you could create a live demo using React? I'd rather link to it in the readme than have this whole snippet there.

**Comment by nathanhleung** [comment]
Here's a fiddle: https://jsfiddle.net/1xs3LLmL/4/.

On a different note, while making the fiddle I was getting mixed content errors since the Google Fonts URL for Ubuntu in the demo.css file is loaded over http://.

I created a pull request (https://github.com/mattboldt/typed.js/pull/279) to fix this.

If everything looks up to par for you I can push another commit to my branch adding the React demo to the readme and then you can merge everything in one fell swoop.

**Comment by mattboldt** [comment]
Made some edits to the demo (slowed down the speed, made the strings make a little more sense)
https://jsfiddle.net/mattboldt/ovat9jmp/

**Comment by nathanhleung** [comment]
Awesome - thanks for the shoutout in the fiddle!

**Comment by kayleoss** [comment]
Can anyone help me with this error? I basically copy and pasted your code, it works for half a second upon refreshing the page and then this error pops up

Line 13:  'define' is not defined  no-undef
 Line 14:  'define' is not defined  no-undef
