### ISSUE TITLE
Cannot get it to work!

### ISSUE THREAD

**Issue by shaquizzle** [mattboldt/typed.js#278]
### Description
Hey Guys, hoping someone can help me with this problem.

I feel ridiculous, but I can't get the simple example from "[Strings from static HTML (SEO Friendly)](https://github.com/mattboldt/typed.js#strings-from-static-html-seo-friendly)" section in the README to work.

### Steps to Reproduce
My code is as follows:

```<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="js/typed.min.js"></script>

  <script>
    var typed = new Typed('.element', {
      stringsElement: '#typed-strings'
    });
  </script>
</head>

<body>
  <div id="typed-strings">
    <p>Typed.js is an <strong>Awesome</strong> library.</p>
    <p>It <em>types</em> out sentences.</p>
  </div>
  <span id="typed"></span>

</body>
</html>
```

**Expected behavior:** I've tried running this in both chrome and safari but to no avail.

**Actual behavior:** The text is just presented statically with no typewriter effect.
I'm getting the error:

```
Uncaught TypeError: Cannot read property 'tagName' of null
    at t.value (typed.min.js:10)
    at new t (typed.min.js:10)
    at test.html:5
```

**NB**: typed.min.js is the latest version (2.0.2) downloaded directly from github.

**Comment by mattboldt** [comment]
Try putting the `<script>` in the body tag, after all the HTML has been rendered. If it must be in the `<head>`, use something like...
```
document.addEventListener("DOMContentLoaded", function(event) {
    // do typed.js stuff
  });
```

**Comment by shaquizzle** [comment]
I've tried both - no luck.

**Comment by shaquizzle** [comment]
When putting script in the body, I get the error:

```
TypeError: null is not an object (evaluating 't.el.tagName')
```

**Comment by mattboldt** [comment]
Your js says `var typed = new Typed('.element', {` which targets a class named `element`, but your HTML has `<span id="typed"></span>`

**Comment by VladimirDev93** [comment]
First include ``span`` and then the ``script`` like this:

```html
<span id="typed"></span>
<script>
    var options = {
      strings: ["First sentence", "Second sentence"],
      typeSpeed: 40,
    }
    var typed = new Typed("#typed", options);
</script>
```
Your issue occurred because the DOM didn't finished loading and your script is already trying to manipulate with the ``span``

**Comment by DannyErazo** [comment]
I've tried I think everyway that youtube and the github instructions have laid out but still no luck ... 

=( I hope to get it soon! Not really sure whats wrong installs brew and got yarn then used yarn to add typed.js then used the following in the body 

<body>
  

    <span id="typed"></span>
    <script>
        var options = {
            strings: ["First sentence", "Second sentence"],
            typeSpeed: 40,
        }
        var typed = new Typed("#typed", options);

    </script>

    <script type="text/javascript" src="js/typed.js"></script>
</body>

**Comment by DannyErazo** [comment]
nevermind hahahha that did the trick actually !!! It appears to work when I put the js in the head not the body... which is odd because I was always under the impression that we needed to put all query and js at the end of the <body>

**Comment by techadjuvant** [comment]
I think it's a problem with the source file typed.js. 
When I was using cdn version("https://cdn.bootcss.com/typed.js/1.1.4/typed.min.js") it was working fine. But when I was trying the downloaded typed.js from github it was giving error.

To solve this I went to the cdn link and copied the page to my typed.js. It solved my problem.

**Comment by alampana1234** [comment]
![screenshot_1](https://user-images.githubusercontent.com/34006670/37919051-9f6e482c-3144-11e8-877a-251546cae31f.png)
typed.js error

**Comment by techadjuvant** [comment]
Which source are you using, CDN or Downloaded ?

**Comment by alampana1234** [comment]
download

**Comment by alampana1234** [comment]
I used this code

<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8"/>
	<title>sdlkasd</title>
	<link rel="stylesheet" href="style.css" />
	<script type="text/javascript">
		<script type="text/javascript">
	
			var typed = new Typed('.element', {
		  strings: ["sdfgsdsdg.", "dsfsdgs."],
		  typeSpeed: 30
		});
</script>
	</script>
	<script type="text/javascript" src="typed.js"></script>
</head>
<body>
	<span class="element"></span>


	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</body>
</html>

**Comment by techadjuvant** [comment]
Go to this link ("https://cdn.bootcss.com/typed.js/1.1.4/typed.min.js") and copy the whole copy the whole page and paste it to your typed.js file. I think it will solve your problem.

**Comment by alampana1234** [comment]
Error again: How to fix this
![screenshot_2](https://user-images.githubusercontent.com/34006670/37919934-38a1cbac-3147-11e8-96e6-3432a00fd5b3.png)

**Comment by mattboldt** [comment]
The above links are very old versions that still use jquery. Use this new url: https://rawgit.com/mattboldt/typed.js/v2.0.6/lib/typed.min.js

and follow the README for instructions

**Comment by datoybi** [comment]
i think order is important. i had same problem. you can write <span> andthen <script>,  then it works!

    <body>
        <script src="./typed.js"></script>
        <span id="typed"></span>
        <script>
            var options = {
                strings: ["First sentence", "Second sentence"],
                typeSpeed: 40,
                }
            var typed = new Typed("#typed", options);
        </script>
    </body>

**Comment by GeoMukkath** [comment]
Thank-you @datoybi it's working for me now. Took about 2 hours to figure out this mess.

**Comment by dennis-leeyinghui** [comment]
> i think order is important. i had same problem. you should write span tag and then script, then it works!
> 
> ```
> <body>
>     <script src="./typed.js"></script>
>     <span id="typed"></span>
>     <script>
>         var options = {
>             strings: ["First sentence", "Second sentence"],
>             typeSpeed: 40,
>             }
>         var typed = new Typed("#typed", options);
>     </script>
> </body>
> ```

Thanks so much!

**Comment by Sacsam005** [comment]
I had a huge file so writing script after span tag was not a solution for me. I had a frustrating hour and was about to do some other way, but the problem was solved when I moved my script
`  <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
`
inside the head.

**Comment by mattboldt** [comment]
@Sacsam005 

> I had a huge file so writing script after span tag was not a solution for me. I had a frustrating hour and was about to do some other way, but the problem was solved when I moved my script ` <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>` inside the head.

Moving the script tag to the head is fine, but in order for the library to consistently recognize the rendered DOM element you provide it, you must listen for the `DOMContentLoaded` event. More info here: https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event

example:
```html
<html>
  <head>
    <script src="path/to/script/typed.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', (event) => {
        var typed = new Typed("#typed", { strings: ['one', 'two', 'three'] })
      })
    </script>
  </head>
  <body>
    <span id="typed"></span>
  </body>
</html>
```

`<script>` tags inside the `<head>` **_load before the html body content_**, so they are essentially unaware of what else is rendered on the page unless you listen for that event.

Another way to approach this problem is by moving the `<script>` tags below the HTML -- in that scenario, the DOM will be rendered in order, and the scripts will be called afterwards:

```html
<html>
  <head></head>
  <body>
    <span id="typed"></span>

    <script src="path/to/script/typed.js"></script>
    <script>
      var typed = new Typed("#typed", { strings: ['one', 'two', 'three'] })
    </script>
  </body>
</html>
```

Note that I did not need to use the `DOMContentLoaded` event handler in the second example because the order of the script tag in the document takes care of that for me.

## why is this important?

The TypedJS library accepts an identifier of the element you want to use it with. In our case, we're using `id="typed"`, so we pass it like `new Typed("#typed", {...})`. This ID is simply **a reference to a DOM element we expect to be present on the page**. Under the hood, [TypedJS uses `document.querySelector("#typed")`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) to find this element on the DOM. If the page is not fully loaded yet, it cannot find the element!
