### ISSUE TITLE
smartbackspace proplem 

### ISSUE THREAD

**Issue by JohnMagdy** [mattboldt/typed.js#280]
Hello sir, really i love this project but i'am getting an proplem the smartbackspace and its http://i.imgur.com/JL8l1LD.png its showen as noraml '|' symbol not Backspace 

note: iam using latest typed.min.js

**Comment by mattboldt** [comment]
Did you see all of the template code in the issue when creating it?https://github.com/mattboldt/typed.js/blob/master/.github/ISSUE_TEMPLATE.md
