### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by missmigalawes** [mattboldt/typed.js#286]
Hello,

The script works great in Chrome, Firefox, Safari, etc... but doesn't work on IE11, it gives the following error in the console 

_SCRIPT438: Object doesn't support property or method 'assign'
File: typed.min.js, Line: 10, Column: 6403_

What's weird is that your demo does work on IE but the distributed package doesn't, what's the difference?

Cheers

**Comment by mattboldt** [comment]
Just released v2.0.4 which addresses the `Object.assign` issue for older browsers. Thanks for pointing this out!
