### ISSUE TITLE
Event Detect the Animation is Done?

### ISSUE THREAD

**Issue by weilinzung** [mattboldt/typed.js#288]
### Description

Is this plugin has an `EVENT` that could detect all the animations are finished? Then we can run other functions after all the animations are finished?

thanks!

**Comment by weilinzung** [comment]
Also does it has a progress loading feature?

**Comment by mattboldt** [comment]
See the readme for all callback functions. No progress feature.

**Comment by weilinzung** [comment]
Would it added in the future?
