### ISSUE TITLE
[Question] Can the cursor blink using React ?

### ISSUE THREAD

**Issue by damien-monni** [mattboldt/typed.js#289]
### Description

When using React, I can't make the cursor blink.

### Demo
This is the actual behavior of the React Demo that I found in the README: [https://jsfiddle.net/mattboldt/ovat9jmp/](https://jsfiddle.net/mattboldt/ovat9jmp/)

### Steps to Reproduce

Just start the fiddle.

**Expected behavior:** The cursor should blink

**Actual behavior:** The cursor is fixed.

**Reproduces how often:** Everytime.

**Comment by mattboldt** [comment]
Yes the cursor blinks on React. The problem is the CSS is inserted via javascript and that doesn't work in JSFiddle's `<head>` element. I could probably append to the body instead, though.
