### ISSUE TITLE
Cursor does not flash when using backspace mode

### ISSUE THREAD

**Issue by alanosman** [mattboldt/typed.js#291]
### Cursor does not flash when using backspace mode
Using the current build, I have built an text animation with this great tool - many thanks to the contributors and author!  I have a small issue though, when I am using the backspace mode with the cursor set to flash, it does not.  It remains still.  Is anyone aware of the issue because I cannot seem to understand why this would happen?  If I change to fade-out, the cursor flashes. 

Also Once the text animation has completed, the cursor does not get removed.  I think we should have an option to keep it there or remove it.  I managed to remove it by finding the element and hiding it.  

### Demo
Here is the web page I am developing where you can see the animation (warning though as I am working on this): https://wiseyoda.elastc.com/landing/index.html

### Additional Information
This is the code I use to initialize typed
```
const initType = () => {
    const typed = new Typed('#typed', {

        stringsElement: '#typed-strings',
        typeSpeed: 50,
        startDelay: 1300,
        backSpeed: 30,
        smartBackspace: true,
        backDelay: 900,
        contentType: 'html',
        onComplete: (self) => { enableControls() },
    });
};
```

This is the HTML where I embed the text
```
    <div id='typed-strings'>
        <p>A FRESH EXPERIENCE FOR<br/><span class='popText'>PLANNING YOUR SPRINTS</span></p>
        <p>A FRESH EXPERIENCE FOR<br/><span class='popText'>TAMING YOUR BACKLOG</span></p>
        <p>A FRESH EXPERIENCE FOR<br/><span class='popText'>EXECUTING YOUR PROJECT</span></p>
        <p>A FRESH EXPERIENCE FOR<br/><span class='popText'>MANAGING YOUR PROJECT</span></p>
    </div>
```

**Comment by alanosman** [comment]
I did a bit more poking around here trying to understand a bit more how the cursor works, and I see in the code for typed that there are keyframes being assigned to an inner element.  I believe this is being destroyed somewhere when not using fade-out.  

I've worked around it by pasting this into my CSS. 

```

    .typed-cursor {
        opacity: 1;
        animation: typedjsBlink 0.7s infinite;
        animation: typedjsBlink 0.7s infinite;
        animation-name: typedjsBlink;
        animation-duration: 0.7s;
        animation-timing-function: initial;
        animation-delay: initial;
        animation-iteration-count: infinite;
        animation-direction: initial;
        animation-fill-mode: initial;
        animation-play-state: initial;
    }

     @keyframes typedjsBlink{
        50% { opacity: 0.0; }
    }

    @-webkit-keyframes typedjsBlink{
        0% { opacity: 1; }
        50% { opacity: 0.0; }
        100% { opacity: 1; }
    }
```
I'd try to suggest a fix but am on a tight deadline with the project we are working on.

**Comment by beauraF** [comment]
Same issue here :)

**Comment by Kukiwon** [comment]
+1
