### ISSUE TITLE
Using an ampersand (&) makes all following characters jump in without animation

### ISSUE THREAD

**Issue by JPortWebDesign** [mattboldt/typed.js#292]
### Description

Using ampersand and possibly other special characters makes all following text jump straight in without the typing animation. I understand that using the HTML entity code (&amp;) instead makes it work as expected but I feel perhaps documenting this in the readme may be beneficial to a lot of people!

### Steps to Reproduce

1. Run the JS fiddle link
2. change the speed to something like 80 (So you can see clearly)
3. Add in a & into one of the strings and watch it jump

**Comment by mattboldt** [comment]
I've added the use of `&amp;` to the readme.
