### ISSUE TITLE
Broken in IE11 - 'Symbol' is undefined (and Safari older than 9.1)

### ISSUE THREAD

**Issue by mdavoli** [mattboldt/typed.js#293]
### Description

I'm attempting to integrate typed into a slide using slick slider but in ie11 I get the following error. It works fine in other browsers.

IE11 is returning an error: 'Symbol' is undefined typed.js (692,16)

Update - error occurs in any version of safari older than 9.1

### Demo
Here is a demo: https://jsfiddle.net/p41bgh4x/3/

### Steps to Reproduce

1. pull content from html to type out
2. do it on a container using a class (might work with id's not sure)
3. breaks in ie11

**Expected behavior:** 
Expect it to run properly

**Actual behavior:** 
IE11 is returning an error: 'Symbol' is undefined typed.js (692,16)

**Reproduces how often:** 
100%

### Additional Information
See fiddle to easily replicate the bug

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by mattboldt** [comment]
Dammit! I'm using ES6's `for ... of ...` iterator, and it appears to transpile that down to use `Symbol.iterator`, which is not supported in IE11. Gotta change it to the old school way `for ... in ...` in `initializer.js`.

**Comment by jfschaff** [comment]
Yep, same issue for me. I get it with even simpler example available at https://jsfiddle.net/bupamy9f/
Why is it marked "Bug: minor"? Doesn't it make it really broken for IE? Otherwise, thanks for sharing this great piece of code ,-) How come people still use IE...

**Comment by mattboldt** [comment]
It's marked minor because it's only for if you use the stringsElement
feature. You can get around using that, so I don't think it's major. I'll
get a fix in soon, but you're welcome to submit a PR!

**Comment by jfschaff** [comment]
Hi, and thanks for your message. I removed mine from Github because it was
actually inaccurate. Thanks for sharing the workaround.

Kind regards,

*Jean-François Schaff*
+33 6 52 24 68 56
LinkedIn <https://www.linkedin.com/in/jean-fran%C3%A7ois-schaff-b31080b0/>

2017-08-23 19:03 GMT+02:00 Matt Boldt <notifications@github.com>:

**Comment by bensinca** [comment]
definetly not fixed.

**Comment by mattboldt** [comment]
@bensinca could you provide some more info? Browser & version? Version of Typed.js? Error message?
