### ISSUE TITLE
Provide upgrade guide

### ISSUE THREAD

**Issue by romainneutron** [mattboldt/typed.js#297]
When breaking BC, it's important to provide Upgrade guide

BC has been broken between version 1 and 2

**Comment by mattboldt** [comment]
Sorry for the inconvenience! I thought about publishing an upgrade guide, but since the breaking change is very minimal, I assumed the updated readme was enough. Here's the most major difference:

### v1.x.x
```javascript
var typed = Typed.new(".element", {
  strings: ["First sentence.", "Second sentence."]
});
// or...
var typed = $(".element").typed({
  strings: ["First sentence.", "Second sentence."]
});
```

### v2.x.x
```javascript
var typed = new Typed(".element", {
  strings: ["First sentence.", "Second sentence."]
});
```

Is this sufficient for you?
