### ISSUE TITLE
typed function not loading from typed.js

### ISSUE THREAD

**Issue by lunayach** [mattboldt/typed.js#298]
When the typed.js file was taken from other online source , it worked but when it was taken from this GitHub repo itself it didn't!!(With the code of mine unchanged!)

**Comment by frostivus22** [comment]
Whats the answer for this one? since i cant load typed function as well it would only say typed is not a funtion

**Comment by lunayach** [comment]
What I think is that typed.js is not supported by the newest jquery there (3.2.1 I guess!).Try with the older versions.

**Comment by mattboldt** [comment]
Newest Typed.js doesn't use any jquery. Also, read the readme for usage of v2.0.x. There are some minor changes.
