### ISSUE TITLE
SmartBackspace isn't working

### ISSUE THREAD

**Issue by YaddyVirus** [mattboldt/typed.js#299]
A simple bug.
Smart backspace isn't working for me.

I have the following JS - 
$(function(){
$("#typed").typed({
    strings: ['My strings are: <i>strings</i> with', 'My strings are: <strong>HTML</strong>', 'My strings are: Chars &times; &copy;'],
    typespeed: 0,
    backDelay: 2000,
    smartBackspace: true,
    loop: true
    });
 });

Yes its a complete copy of the smartbackspace demo.
It just ain't working. The string gets typed, then the entire string gets backspaced and then the new string comes.

How do I fix this?

**Comment by coleproe** [comment]
Can confirm `smartBackspace: true` does not work for me, either.
