### ISSUE TITLE
Repeat Function (infinite loop)

### ISSUE THREAD

**Issue by wutmikee** [mattboldt/typed.js#3]
Is there any way to create an infinite loop? I opened a discussion on StackOverflow regarding this issue, but can't figure it out.

View here:
http://stackoverflow.com/questions/19071466/repeating-js-function

Cheers,
Mike

**Comment by mitejain** [comment]
Hi Matt,
There is very distinct flicker of screen when this is put in loop. Is there any way that can be fixed, gives a very bad experience to the user.

**Comment by danidee10** [comment]
@mitejain and For anyone that comes across this later, if you notice a flicker in the page...It's most likely the page adjusting when the text is deleted. You can easily solve this by setting a fixed height for the text container (i.e where `Typed js` types)

**Comment by IgorArauj0** [comment]
text never
