### ISSUE TITLE
Feature Request: smartBackspace expected behaviour

### ISSUE THREAD

**Issue by odil-io** [mattboldt/typed.js#304]
### Description

Using Typed.js with `smartBackspace` set to `true`, removes the whole string when `loopCount` is set to `infinite`.

### Demo

http://www.mattboldt.com/typed.js/#smartBack

**Expected behavior:** Only backspace what doesn't match the previous string.

**Actual behavior:** After finishing the last string in array, it backspaces the whole string.

**Reproduces how often:** 100% of the time as its currently *by design*

### Additional Information

I would like to include the option to enable or disable this specific behaviour.
Something like `loopClear: false` to disable this behaviour.

**Comment by mattboldt** [comment]
Try this work around https://github.com/mattboldt/typed.js/issues/313#issuecomment-331685829
