### ISSUE TITLE
How to properly import after install through npm?

### ISSUE THREAD

**Issue by fash97** [mattboldt/typed.js#307]
index.html:26 Uncaught SyntaxError: Unexpected token import

I just use such form to import, is this correct? I am really new to javascript
```
<script type="text/javascript">
		// Can also be included with a regular script tag
		// Can also be included with a regular script tag 
		import Typed from 'typed.js';
		
		var options = {
			strings: ["<i>First</i> sentence.", "Second sentence."],
			typeSpeed: 40
		}
		
		var typed = new Typed(".element", options);
	</script>
```

**Comment by mattboldt** [comment]
if you're not using ES6 modules, you just need to load the script from a `<script>` tag.

**Comment by lohiaumang** [comment]
Hi, 
I am getting the same error, and can't figure out why. I just do something like - <script src="typed.js/src/typed.js"></script> and get the error - "Uncaught SyntaxError: Unexpected token import". I am trying to use typed.js with plain old jquery. I am very new to this and any help is appreciated.

**Comment by edoardottt** [comment]
i have the same issue

**Comment by mattboldt** [comment]
If you're using npm and webpack (or some kind of build process), you should be able to `npm install` the library and use it via `import`.

But it sounds like you don't have the above case, so you should just use a script tag to load the library instead. You can place this in the head of your html, or at the bottom of the file. Just be sure the DOM is loaded before trying to initiate Typed.
```html
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.10"></script>
```

**Comment by szczepkacpra** [comment]
Hello Matt, 

I'm building my first non-WP website and trying to take advantage of your library.

```
<head>
  ...
  <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.9"></script>
  <script>
    import Typed from 'typed.js';

    var options = {
      strings: ["String A", "String B", "String C"],
      typeSpeed: 40
    }

    var typed = new Typed(".element", options);
  </script>
</head>
```

generates console error

> Uncaught SyntaxError: Unexpected identifier


on the line

`import Typed from 'typed.js';`


Further down the road I hope to display strings here:

`<h2>...<span id="typed"></span></h2>`

I'm hitting my head against the wall for few hours now and run out of ideas on fixing it. Could you please give me a hand?
