### ISSUE TITLE
How to hide the cursor in onComplete function?

### ISSUE THREAD

**Issue by fash97** [mattboldt/typed.js#309]
### Description

How to stop the cursor blinking after completion?

### Steps to Reproduce

I try to change the property "showCursor" in the onCompletion function, but it doesn't work.
Any advice how to do it?

**Comment by megatommy** [comment]
The blinking cursor has the class `typed-cursor`.
so in the function that you call as the onComplete, you can to something like this `$('.typed-cursor').hide();`
in my example i use jQuery
