### ISSUE TITLE
How to add and change strings dynamically  

### ISSUE THREAD

**Issue by appleansa** [mattboldt/typed.js#312]
Hi! Please help me! I can't understand how to start typed js in slider. I  have a slick carousell. At every slide I having the text, that begin to typing when the slide only was changed.

**Comment by appleansa** [comment]
<div class="slider">
 <h1 id="type" class="typed" style="white-space:pre">
                                some text 1
                            </h1>
 <h1 id="type" class="typed" style="white-space:pre">
                                some text 2
                            </h1>
 <h1 id="type" class="typed" style="white-space:pre">
                                some text 3
                            </h1>
</div>

**Comment by gustawdaniel** [comment]
This is good question. 

I initialized Typed with given strings, but on event I want to change strings to other. 

How to do this?
