### ISSUE TITLE
Issue/Feature Request: Typed,js deletes The whole String after completing 1 loop, even if Smartbackspacing is activated.

### ISSUE THREAD

**Issue by helloplayer1** [mattboldt/typed.js#313]
I think this is more a Feature Request then a Issue, but Ok. So I have managed to create I Typing that looks good for me, but i found a problem that destroys the Harmony of the Typing: I have Smartbackspacing activated and wanted to loop the Typing, but after it completes 1 loop, it deletes the whole String and not just the Changed thing(like Smartbackspacing works).
This doesnt look so good and so I made this feature request.

Jsfiddle:
[https://jsfiddle.net/mwbzocj4/](https://jsfiddle.net/mwbzocj4/)

Steps to Reproduce

1. Create A Typing with more then 1 String that works with Smartbackspacing (Example: "Hello there", "Hello Tom")
2. Apply Smartbackspacing
3. Apply Loop and Loopcount Infinity on it
4.  Watch until the Loop completed

**Expected behavior:** It uses Smartbackspacing which gives the effect of a never ending Loop.

**Actual behavior:** It doenst use Smartbackspacing and Deletes the whole Thing.

**Reproduces how often:** 100% With these Settings applied.

**Comment by mattboldt** [comment]
If you'd like to have a string remain constant for every time it's typed, and then looped, I'd just get rid of smart backspace and add that string in manually in the HTML before the typed element.

**Comment by helloplayer1** [comment]
Will this be SEO-Friendly?:grinning:

**Comment by rijk** [comment]
@mattboldt I think it would be cool to natively support this! The current behaviour feels unintuitive.
