### ISSUE TITLE
Typed 2.0.5 is not working on Jquery 3.2.1.

### ISSUE THREAD

**Issue by MrDioamDev** [mattboldt/typed.js#314]
### Description
I'm trying to use Typed.js with Jquery 3.2.1, but it seems that don't work at all.

### Demo

https://jsfiddle.net/wdevx1o7/

### Steps to Reproduce

1. Put Jquery and Typed
2. Add a document ready.
3. Choose an element and then call Typed Function.

**Expected behavior:** Works.

**Actual behavior:** Don't work.

**Reproduces how often:** 0%.

### Additional Information

It seems 1.1.4 version works..

**Comment by JoshCarey** [comment]
I can verify this... I was actually trying to run Typed 2.0.5 with jQuery 2.1.1, and it wasn't working either.

I had to downgrade Typed to version 1.1.6 to get it to work.

**Comment by mattboldt** [comment]
v2.x.x doesn't use jQuery at all! Check the readme for new usage without jquery.

**Comment by MrDioamDev** [comment]
Oh, sorry. I didn't see that, Now it's working without Jquery!
Thank you for your answer!
