### ISSUE TITLE
Curser is not visible

### ISSUE THREAD

**Issue by omeith** [mattboldt/typed.js#315]
### Description

I dont have any curser , although i used showCursor: true ! 
What am I doing wrong, please help me .

### Demo
https://jsfiddle.net/v0Lj7x2t/2/
### Steps to Reproduce

**Actual behavior:** [What actually happens]
The cursor is positioned in left corner, but is not moving and blinking!

**Comment by mattboldt** [comment]
demo doesn't seem to be working at all
