### ISSUE TITLE
Using the stop() method on onStringTyped event breaks the script

### ISSUE THREAD

**Issue by rtemiuz** [mattboldt/typed.js#318]
### Description

I need use some manipulations with string after is typed (each). So, I use `stop()` method on `onStringTyped ` event for this, and after do my function I want continue script by method `start()`.

### Demo
You can see demo on [JSFiddle](https://jsfiddle.net/qewn8vxz/10/)
In the demo, I use the `setTimeout` in `custom` function, in reality I do not know how long it will take to perform this function.

### Steps to Reproduce

1. Set `typeSpeed` and `backSpeed` options.
2. Use `onStringTyped` event and stoping typed. After that run custom function.
3. In end of custom funcion run typed by `start()` method.

### Additional Information

I found in `start()` method`this.pause.curString` is emty and `this.pause.curStrPos` is 0 in this case. So, I tryed fixed this: [see commit](https://github.com/rteamx/typed.js/commit/fe2022a833db04b659ae0b21c2abb6268c8bcdfd#diff-689563c7d2ad93e77ed0f27e3f4e09c6) and [demo](https://jsfiddle.net/6f4r36sb/1/) but this was not enough.

**Comment by BenMorel** [comment]
Same problem here, when using start/stop in `onStringTyped`, weird behaviour occurs: the typing restarts immediately, instead of waiting for the configured delay, and a lot of flickering occurs.

**Comment by donotfold** [comment]
Same here. Would be nice if there's a setting that plays only one string and can play the next / previous with a specific method. I'm missing that.

**Comment by rbwilcoxon11** [comment]
Don't know if this is exactly what I am seeing, but this fixes the problem for me

``` javascript
var typed = new Typed('.text-output', {
  ...
  onStop: (_, self) => {
    ...
    clearInterval(self.timeout)
   },
  ...
})

I ran into the issue when I put a pause button on the page; spamming it caused the breakage

**Comment by asadakbar** [comment]
> Don't know if this is exactly what I am seeing, but this fixes my problem
> 
> ```js
> var typed = new Typed('.text-output', {
>   ...
>   onStop: (_, self) => {
>     ...
>     clearInterval(self.timeout)
>    },
>   ...
> })
> 
> I ran into the issue when I put a pause button on the page; spamming it caused the breakage
> ```

I think this is working because the default `backDelay` property is cleared. That property is used to define how long the timeout should be set, see here https://github.com/mattboldt/typed.js/blob/master/lib/typed.js#L333-L335. This issue https://github.com/mattboldt/typed.js/issues/420 shows that when the backDelay is set to 0, the flickering issue stops. My problem is that I need the back delay, so unfortunately this solution won't work for me.

**Comment by xididri** [comment]
@rbwilcoxon11 [solution](https://github.com/mattboldt/typed.js/issues/318#issuecomment-370660434) does work but there is still a bug which happens randomly when we try to un-pause the animation (`start()`).

see this codepen => https://codepen.io/xididri/pen/ExELKay
