### ISSUE TITLE
showCursor: False on finish?

### ISSUE THREAD

**Issue by orpheus** [mattboldt/typed.js#321]
Is there a way to fade the cursor out when the animation is done? (Assuming it's not on an infinite loop.

**Comment by Kore-Development** [comment]
Please add this if it's not already added @mattboldt

**Comment by Kore-Development** [comment]
I would also like the cursor to fade out when the animation is done on my work in progress website. [Click here for website](https://brave-coal.glitch.me/).

**Comment by mattboldt** [comment]
There's not currently a built-in way to do this, but here's how I did it on my site:
https://github.com/mattboldt/mattboldt.github.io/blob/master/_includes/nav.html#L53

**Comment by Kore-Development** [comment]
It only seems to stop the animation not fade away.

**Comment by Kore-Development** [comment]
My source code is at https://glitch.com/edit/#!/brave-coal

**Comment by mattboldt** [comment]
Oh right, I made mine just stop. Well you could add a fade out CSS class or something. Or maybe try `style.opacity = "0"`

**Comment by Kore-Development** [comment]
Ok now it works

**Comment by mattboldt** [comment]
```js
  new Typed('#el', {
    strings: ["hello", "welcome"],
    onComplete: function() {
      let cursor = document.querySelector('.typed-cursor');
      setTimeout(function() {
        cursor.style.opacity = 0;
      }, 2000);
    }
  })
```
pasting this here in case someone stumbles on the issue
