### ISSUE TITLE
Calling stop() in preStringTyped doesn't actually stop the animation in time

### ISSUE THREAD

**Issue by sniepoort** [mattboldt/typed.js#324]
### Description

I have a situation where based on the index of the sequence, I need to stop the animation. However, when using preStringTyped, calling stop() on self still allows for one character to be animated before stopping. 

### Demo
https://jsfiddle.net/bqmmkb00/

### Steps to Reproduce

1. Make string sequence of at least 3 strings
2. Start typed.
3. In preStringTyped callback, call stop() on self

**Expected behavior:** 

No characters should be typed after calling stop, in preStringTyped Callback

**Actual behavior:** 
One character is typed

**Reproduces how often:**

100%

**Comment by mattboldt** [comment]
closing in favor of https://github.com/mattboldt/typed.js/issues/325
