### ISSUE TITLE
Calling destroy() in preStringTyped doesn't work 

### ISSUE THREAD

**Issue by sniepoort** [mattboldt/typed.js#325]
### Description

Calling self.destroy() in preStringTyped doesn't stop animation or destroy instance.

### Demo
https://jsfiddle.net/L91qr3w0/

### Steps to Reproduce

1. Start typed
2. Call self.destroy() in preStringTyped callback

**Expected behavior:** 
Animation stops and instance is cleared

**Actual behavior:** 
Nothing happens

**Reproduces how often:**
100%

**Comment by tomm1996** [comment]
The Typed instance does not seem to have a destroy method either

**Comment by SalchiPapa** [comment]
@tomm1996 could you please forward me to the commit that fixed this issue, I'm having the same problem, but I don't understand if this was fixed or simply colsed.

**Comment by SalchiPapa** [comment]
@mattboldt  could you please forward me to the commit that fixed this issue, I'm having the same problem, but I don't understand if this was fixed or simply colsed.
