### ISSUE TITLE
Need help with error: Typed.new is not a function

### ISSUE THREAD

**Issue by prsheth** [mattboldt/typed.js#326]
<script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
                <script type="text/javascript" src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>
                
                <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.6/typed.min.js"></script>
                
                <script type="text/javascript" src="assets/js/main.js"></script>
                <script>
                    document.addEventListener('DOMContentLoaded', function() {
                        Typed.new('#typed', {
                            stringsElement: document.getElementById('typed-strings'),
                            typeSpeed: 0,
                            showCursor: false
                        });
                    });

                </script>

This code is just before the close of the body tag, I see the text but without the typewriter effect

**Comment by DannyErazo** [comment]
I'm literally clueless my brackets keeps giving me errors but all the vids on YouTube show this working  Help!!!!!

**Comment by whimzee** [comment]
The syntax is `new Typed()` and not `Typed.new()`.
