### ISSUE TITLE
Adobe Edge Integration

### ISSUE THREAD

**Issue by NaveedJ53** [mattboldt/typed.js#328]
I'm creating an Edge Animate Animation and want to integrate type.js to give the text typewriter effect.

`Text has ID = textlogo
Included type.js and jquery-2.1.4.min.js`

Created Event on compositionReady

```
Symbol.bindElementAction(compId, symbolName, "document", "compositionReady", function(sym, e) {
         var typed = new Typed('.element', {
            stringsElement: '#textlogo'
         });
});
```
Adobe Edge Screenshot
`https://snag.gy/CkTYFy.jpg`

Don't know why the typing effect is not working. Don't know much about JS

**Comment by mattboldt** [comment]
sorry, not familiar with Adobe Edge
