### ISSUE TITLE
text overflows/overlaps in mobile view

### ISSUE THREAD

**Issue by Better-Boy** [mattboldt/typed.js#329]
![screen shot 2017-11-19 at 8 16 07 pm](https://user-images.githubusercontent.com/19553184/32991700-967a8c68-cd66-11e7-8080-235d89a222c6.png)

### Description
I have a span inside a div. The span is used to show the animated text. Everything works fine in normal desktop view but in mobile view the text overlaps.
Cursor and works fine but the text overlaps over the previous text.

**Expected behavior:**
It should work fine in mobile view aka responsiveness.

**Actual behavior:**
Text Overlapping

**Comment by nikosgatzoulis** [comment]
Hello. Is it possible to provide some code that reproduces the issue above?  I'd like to look into it.

**Comment by nautatva** [comment]
My observations are this happens when you do not set the container height correctly. just adjust the height to get this resolved :)
