### ISSUE TITLE
jQuery hover on input in Firefox browser Problem with typed.js

### ISSUE THREAD

**Issue by mhbayan** [mattboldt/typed.js#331]
### Description

 Mozilla Firefox not work good in input element hover use typed.js "https://github.com/mattboldt/typed.js/" for create typing effect on input placeholder when input hovered it's work very good in all browser but on Firefox not work

### Demo
`var city = new Typed('#city', {
  strings: ['کدوم شهر؟ قم', 'کدوم شهر؟ تهران', 'کدوم شهر؟ مشهد', 'کدوم شهر؟ اصفهان', 'کدوم شهر؟ یزد',
            'کدوم شهر؟ شیراز', 'کدوم شهر؟ کیش', 'کدوم شهر؟ تبریز'
  ],
  typeSpeed: 40,
  backSpeed: 40,
  backDelay: 1000,
  smartBackspace: true,
  loop: true,
  bindInputFocusEvents: true,
    attr: 'placeholder'
  });
  city.destroy();
  $("#city").attr("placeholder", "کدوم شهر؟");
  $("#city").hover(function () {
    city.reset();
  }, function () {
    city.destroy();
    $("#city").attr("placeholder", "کدوم شهر؟");
  });`

  stackoverflow link : 
[https://stackoverflow.com/questions/47413248/jquery-hover-on-input-in-firefox-browser](https://stackoverflow.com/questions/47413248/jquery-hover-on-input-in-firefox-browser)

**Comment by mattboldt** [comment]
not sure what the desired effect is here
