### ISSUE TITLE
Cursor not blinking unless FadeOut is present

### ISSUE THREAD

**Issue by alukach** [mattboldt/typed.js#332]
### Description
I've noticed that the cursor does not automatically blink in the most basic of demos (unless CSS is manually added to ensure the cursor blinks).

However, the [full demo page](https://www.mattboldt.com/typed.js/) works because there is a `fadeOut` example on the page.

### Demo
[Basic demo, broken, no `fadeOut` example included](https://codepen.io/anon/pen/jaoXMW?editors=1010#0)
[Working, after I've added a `fadeOut` example](https://codepen.io/anon/pen/EbzGNw?editors=1010#0)

**Expected behavior:** [What you expect to happen]
Cursor should blink in basic demo.

**Actual behavior:** [What actually happens]
Cursor does not blink.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Additional Information

My guess is that the bug is related to #285 and possible resolved by #306 (I have not tried)

**Comment by peteringram0** [comment]
+1 Will this be fixed soon ?

**Comment by marcelo-ribeiro** [comment]
Temporary solution:

CSS: 
```
@keyframes typedjsBlink {
  50% { opacity: 0; }
}
.typed-cursor {
  animation: typedjsBlink 0.7s infinite;
}
```

**Comment by Mineslu** [comment]
In line 552 of typed.js:
  this.cursor.className = 'typed-cursor';

Change for:
this.cursor.className = 'typed-cursor typed-cursor--blink';
