### ISSUE TITLE
Weird behavior with default placeholder

### ISSUE THREAD

**Issue by cyrilchapon** [mattboldt/typed.js#335]
### Description
When using with `attr: 'placeholder'` with a default html placeholder on the element (`placeholder="example"`). The behavior looks weird.

This disallow use of native placeholder, which basically disallow a nice accessibility / nojs feature on the element.

### Demo
https://jsfiddle.net/vfcpaq8k/

**Expected behavior:** [What you expect to happen]
Dunno what behavior should be adopted, but at least deleting the initial first, then running loop.

**Actual behavior:** [What actually happens]
Weird. First dynamic sentence is ignored, and initial static one is blinked several times

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**Comment by mrfleap** [comment]
I was about to create a new issue but found this.

If anyone else is still experiencing this issue and doesn't mind using jQuery, I made a simple **workaround**: https://jsfiddle.net/mrfleap/y1x3zswn/

Which solves the shown here: https://jsfiddle.net/mrfleap/sgd6eut3/5/
