### ISSUE TITLE
Blink cursor when placeholder

### ISSUE THREAD

**Issue by cyrilchapon** [mattboldt/typed.js#336]
### Description

Actual cursor (blinking or not), can't work with an input placeholder. That's a shame since... cursors actually are commonly inside input elements...

**Expected behavior:** [What you expect to happen]
Cursor working with placeholder

**Actual behavior:** [What actually happens]
Not working

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Additional Information
Why messing with css, transitions and stuff. What about a rough `|` appended to content, and dynamically shown / hidden ?

**Comment by mattboldt** [comment]
> What about a rough | appended to content
very similar to what is already happening

> dynamically shown / hidden
how would you dynamically show / hide something that isn't an HTML element, but rather part of the text itself? That would require deleting the last line of text and adding it back again at the speed of the blinking. Probably possible, but I don't like that approach.

**Comment by cyrilchapon** [comment]
That's a shame this issue was closed because "you don't like the approach".

And that's a shame this great library will miss à feature because "you don't like the approach"

**Comment by simonsterj** [comment]
Unable to find a solution as well. Would really love for this feature
