### ISSUE TITLE
Type out one word once

### ISSUE THREAD

**Issue by felixdorner** [mattboldt/typed.js#338]
I want to write out one simple word once. Do I miss something here?

```
var typed = new Typed('#name', {
  strings: "Name",
  typeSpeed: 30,
  loop: false,
  showCursor: false
});
```

**Comment by seifsg** [comment]
it expects a string array
try:
`
var typed = new Typed('#name', {
  strings: ["Name"],
  typeSpeed: 30,
  loop: false,
  showCursor: false
});
`

**Comment by felixdorner** [comment]
@seifsg yes it expects an array. However, I don't want to put in an array of strings. I need to type out only one word. I tried this already but it didn't work:

```javascript
var typed = new Typed('#name', {
  strings: ["Name"],
  typeSpeed: 20,
  backSpeed: 0,
  loop: false,
  showCursor: false
});
```

**Comment by seifsg** [comment]
@felixdorner here is fiddle with that code https://jsfiddle.net/seifsg/e1o0o8qu/
It should work with provided options. I suggest that you explore the options more until you find what fits your need.

**Comment by seifsg** [comment]
@felixdorner I updated the fiddle for better understanding. I hope it helps.
https://jsfiddle.net/seifsg/e1o0o8qu/
You can experiment further with the options.

**Comment by felixdorner** [comment]
@seifsg thank you. It works now. For the record here is what I did wrong:

In the HTML I did this:

`<span id="name">Name</span>`

instead of this:

`<span id="name" style="white-space:pre;"></span>`

Now it works with this JS which I mentioned already [here](https://github.com/mattboldt/typed.js/issues/338#issuecomment-352727933):

```javascript
var typed = new Typed('#name', {
  strings: ["Name"],
  typeSpeed: 30,
  backSpeed: 0,
  loop: false,
  showCursor: false
});
```
