### ISSUE TITLE
(Request) TypeScript definition file.

### ISSUE THREAD

**Issue by AndresMorelos** [mattboldt/typed.js#340]
### Description

Hi, this isn't a bug, I'm programming in TypeScript language, Do you have the library definition file?, it's helpful for us, thanks you.

**Comment by inunotaisho26** [comment]
@mattboldt Ditto, working on a dotnet/ react-typescript project and I need typings too.

**Comment by mattboldt** [comment]
I'm really not familiar with TypeScript declarations. Could you provide more info, or maybe open a PR to add one?

**Comment by inunotaisho26** [comment]
@mattboldt I actually think you have a PR for this in the que.

**Comment by mattboldt** [comment]
fixed in v2.0.9! 🎉
