### ISSUE TITLE
Issue with onComplete in IE11

### ISSUE THREAD

**Issue by pixelspencil** [mattboldt/typed.js#341]
### Description

I deployed this amazing script to one of my builds and was trying to get a sort of callback check working so when the typing is complete it could then call another function and fire that.

I found the onComplete parameter in the docs and this worked well apart from in IE where it completely broke the page.

It's probably how I set up the parameter but each time I tried to use it it would still break.

**This is the first try - probably not set up correctly**
![screen shot 2018-01-10 at 11 39 26](https://user-images.githubusercontent.com/1231005/34771176-9434ffe8-f5fb-11e7-9c3e-a5ae2fa73d5f.png)

**This is the second try - again probably not set up correctly**
![screen shot 2018-01-10 at 11 41 12](https://user-images.githubusercontent.com/1231005/34771212-afa8ec44-f5fb-11e7-8974-962a199d5075.png)

**This was the one we placed live and it worked and looked valid but was not working in IE11**
![screen shot 2018-01-10 at 11 48 23](https://user-images.githubusercontent.com/1231005/34771469-98953fa2-f5fc-11e7-834e-649eadb9c3ac.png)

### Demo
There is no demo now as the page went live without the offending code after removing the parameter to fix it for IE11

**Comment by pixelspencil** [comment]
Please note: Ignore the **document.addEventListent...** block as that was a testing phase.
The first and last grabs are how it went in to production among a bunch of other script.

**Comment by mattboldt** [comment]
you should use the callbacks as such:
```js
new Typed('#el', {
  onComplete: function() {
    // do some stuff
  }
});
```

or 

```js
function myFunction() {
 // do some stuff
}

new Typed('#el', {
  onComplete: myFunction
});
```
