### ISSUE TITLE
Skip strings?!

### ISSUE THREAD

**Issue by SirPedr** [mattboldt/typed.js#342]
### Description

I'm currently working on a text-based game using HTML, CSS and JS, and at a certain point a text appears explaining some things in the story. For aesthetic purposes, I downloaded typed.min.js and included it in the project. However, it does not type the first string, and then it goes to the second; it is only printed if I loop, but in this case it is not applicable. I searched the internet and found nothing like it. Does anyone know what it is and can solve it?

#### HTML
<div id="containerEnredo">
  < p >This text will not be typed.</p>
  < p >This text will be typed.</p>
  < p >This text will be typed too.</p>
</div>
JS: let digitacao = new Typed('#containerEnredo',{
    stringsElement: '#containerEnredo'
  })

**Expected behavior:** Enter the strings in order and without skipping any.

**Actual behavior:** It is jumping the first string and typing only the remaining ones.

**Reproduces how often:** Nunca vi acontecer com mais ninguém. Tentei usar outros arquivos HTML e JS mas o erro continua.

### Additional Information

Using JQuery 3.2.1 Min 
Using Typed Min Version 2.06

**Comment by kawhatley** [comment]
______________________ CSS___________
```
.wrap {
	min-height:110px;
	/*margin-left:20%;*/
}
#first {
	color:#162349!important;
	font-size: 50px;
	line-height:55px;
	font-weight:700;
	letter-spacing:2px;
}
#next {
	color:#162349!important;
	font-size: 34px;
	padding-top:20px!important;
	line-height: 55px;
	letter-spacing:1px;
}
```
_________________ functions.php
```
// Register Script
function typing_scripts() {
	wp_register_script( 'typed', 'https://rawgit.com/mattboldt/typed.js/v2.0.6/lib/typed.min.js', false, false, false );
	wp_enqueue_script( 'typed' );
}
add_action( 'wp_enqueue_scripts', 'typing_scripts' );
```

_________ Script Shortcode call 
```
<script>
var typed = new Typed('#first', {
			strings: ['YOUR TEXT HERE - FIRST LINE'],
  typeSpeed: 60,
  backSpeed: 0,
  loop: false,
  showCursor: false,
startDelay:300,
});
var typed = new Typed('#next', {
			strings: ['YOUR TEXT HERE - SECOND LINE'],
  typeSpeed: 40,
  backSpeed: 0,
  loop: false,
  showCursor: false,
startDelay:2500,
});
</script>
```

__________________________________________ on page HTML
```
[sc name="Typed"]
<div class="wrap">
  <div class="type-wrap">
    <span id="first" style="white-space:pre;"></span></div>
  <div class="type-wrap">
    <span id="next" style="white-space:pre;"></span></div>
</div>
```

**Comment by SirPedr** [comment]
Thanks!

**Comment by BenQuirk** [comment]
What worked for me is changing my container from a div to a span. 

original: (skips first line)
 <div class="typed-effect-container"></div>

changed to this: (yay now the first line is not skipped!)
 <span class="typed-effect-container"></span>
