### ISSUE TITLE
Issue with mobile device

### ISSUE THREAD

**Issue by mehtaculous** [mattboldt/typed.js#345]
The animation works perfectly fine on a desktop browser, but when I open it on mobile (Google Chrome), the animation seems to lag when it goes to the next line. It seems as though the text is continuing to type behind the scenes, but the only thing that appears is the blinking cursor. Only when I click somewhere on the page does the remaining text appear and the animation continues. Is there anyway to prevent this from happening?

index.html
```
<div class="col-md-8 col-md-offset-2">
    <p><span id="skills-description"></span></p>
</div>
```

main.css
```
.typed-cursor {
  opacity: 1;
  color: #000;
  font-size: 20px;
  -webkit-animation: blink 0.7s infinite;
  -moz-animation: blink 0.7s infinite;
  animation: blink 0.7s infinite;
}

@keyframes blink {
  0% { opacity:1; }
  50% { opacity:0; }
  100% { opacity:1; }
}

@-webkit-keyframes blink {
  0% { opacity:1; }
  50% { opacity:0; }
  100% { opacity:1; }
}

@-moz-keyframes blink {
  0% { opacity:1; }
  50% { opacity:0; }
  100% { opacity:1; }
}
```

main.js
```
var scrollTypedDistance = $('#skills-description').offset().top - $(window).height() + 400;
var animateTypedString = false;
$(window).scroll(function(event) {
    if ($(window).scrollTop() >= scrollTypedDistance && !animateTypedString)  {
      var options = {
        strings: ["^1000I don't know who you are or what you want^300.^300.^300.^300but I can tell you that I have acquired a very particular set of skills over a short span of time.^1000 While I'm always experimenting with new languages,^300 frameworks,^300 and libraries to better my arsenal,^500 the array of icons below are my primary weapons of mass creation."],
        typeSpeed: 35
      }
      var typed = new Typed('#skills-description', options);
      animateTypedString = true;
    }
});
```

**Comment by alexvida89** [comment]
I also have this issue and unfortunately found no solutions yet.

**Comment by carsonbird** [comment]
Also experiencing this issue. Seems to occur sometimes (but not always) when types text wraps to a new line, and the page must adjust height to give room for the new line.

As for some additional information, I do NOT experience this issue on a 2017 Android 8 device running Brave as the browser, and not on a Linux desktop, also running Brave.

I have only experienced this issue on Apple devices, specifically Safari on the iPhone 6, iPhone X, and iPad 2018(ish) models, all running the latest versions of iOS.

Any leads on this issue?
