### ISSUE TITLE
[Feature Request] Working cursor when used as placeholder for `<input type='text'>` 

### ISSUE THREAD

**Issue by simonsterj** [mattboldt/typed.js#352]
### Description

A working, blinking, cursor is currently unavailable as long as Typed objects are instantiated as `<input type='text'>` placeholders 

### Demo
[jsfiddle demo](https://jsfiddle.net/bs3yqL4s/5/)

**Expected behavior:** Cursor, blinking cursor

**Actual behavior:** No cursor

**Reproduces how often:** 100% of the time

### Additional Information
Strange behavior when used in `<input>` has been referenced several times before.  
#269 and #336 attempt to address the issue but reach no conclusion.   

Would it be possible to rekindle an effort in bringing this feature? As Typed seems to be quite popularly and wonderfully paired with `<input type='text'>`

**Comment by cyrilchapon** [comment]
+1
