### ISSUE TITLE
Jumps to completion upon encountering an ampersand "&"

### ISSUE THREAD

**Issue by ZeeCoder** [mattboldt/typed.js#356]
### Description
Typing works up until the & character, but the rest just shown together immediately after. 

### Demo
https://codesandbox.io/s/1oj6w46w3j

**Expected behavior:**
Should continue after the & character.

**Actual behavior:**
Shows the rest of the string at once.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Used the latest version.

**Comment by anisabboud** [comment]
Use `&amp;` instead of `&` (see https://github.com/mattboldt/typed.js/issues/292).

http://rabbit.eng.miami.edu/info/htmlchars.html
