### ISSUE TITLE
Do no destroy previous string

### ISSUE THREAD

**Issue by KrisKnez** [mattboldt/typed.js#358]
### Description

I could not find this feature in the documentation so I would consider this a feature request.

As you can see in this demo https://jsfiddle.net/0fxgfzum/
I am trying to make a virtual console.

What I want is once the user clicks a button that typed.js continues to write the second string without deleting the first string.

I believe that this would be a very useful feature or do you recommend me doing this a different way?

**Comment by xian04** [comment]
@ChrisDoesEverything I am looking as well for this feature. Do you find a solution on this?
