### ISSUE TITLE
Uncaught ReferenceError: Typed is not defined

### ISSUE THREAD

**Issue by redf150flames** [mattboldt/typed.js#361]
### Description

I'm trying to use TypedJS in a Laravel site, so I ran npm install typed.js, then included the script using `require('../../../node_modules/typed.js/lib/typed.min.js');`.

I added my TypedJS script like this:
```
var typed = new Typed('#header-search-input', {
	strings: ["Los Angeles", "90210", "Vans Spinning Away Video"],
  	attr: 'placeholder',
  	typeSpeed: 30
});
```
And when I go to the page I get the error `Uncaught ReferenceError: Typed is not defined`. Am I missing something?

**Comment by marcohanke** [comment]
Same here, the Problem seems to be require. We have to import it like
```require('../../node_modules/typed.js/lib/typed');``` but this dosen't work for me as well. wuick'n'dirty add the script oldschool directly to the website will work.

**Comment by redf150flames** [comment]
@marcohanke I got it fixed doing this:

```
var Typed = require('./typed.min.js');

var typed = new Typed('#header-search-input', {
	strings: [
		"Search by city", 
		"Los Angeles", 
		"Search by zip code", 
		"90210", 
		"Search by video",
		"Vans Spinning Away"
	],
  	attr: 'placeholder',
  	startDelay: 50,
  	typeSpeed: 50,
  	backSpeed: 50,
  	smartBackspace: true,
  	loop: true,
  	loopCount: Infinity
});
```

**Comment by mattboldt** [comment]
I am not familiar with how Laravel includes its js assets, but it looks like you got it working!

**Comment by GanchoDanailov** [comment]
I was getting same error because i did install it 'npm install typed -s' instead 'npm install typed**.js** -s'
