### ISSUE TITLE
observed pain point working with multi lines and centered text

### ISSUE THREAD

**Issue by kylebakerio** [mattboldt/typed.js#362]
When typing centered text, if I remove the cursor, the text shifts a little to re-center without the char there.

This is not desirable, as it's not what would happen when a cursor would move off of a line. (I'm doing multi-line text, so I have to kill the old cursor just before making a new one on the next line to convey hitting 'enter').

I am thinking of injecting empty space at the same second I pull the cursor away. Hacky and painful, but it seems like there isn't another option, other than not using centered text.

Thoughts? I was wondering if this would make sense as a built-in feature, but you'd have to add in enough space to compensate for the cursor character width for it to be effective, which could obviously vary. So then you have to give a "replaceChar" option for them to specify their space holder. Not ideal.

**Comment by finetype** [comment]
On seconf thought, I'm sure there's some clever CSS way to get the cursor character to hang out "after" the line without being compensated for by the centering logic, no?
