### ISSUE TITLE
line break with HTML tag

### ISSUE THREAD

**Issue by eleumas** [mattboldt/typed.js#363]
I have this code (my pen here: https://codepen.io/eleumas/pen/bvJmMx) but i have a problem with the cursor and line break. 
I have read some discussion in github and searched online but i haven't had lucky.

How can i do?

Thanks.
 
```<span id="typed" style="white-space:pre"></span>```
```
var typed2 = new Typed('#typed',
        {
          strings: ['<span class="uk-heading-hero">my text in first line</span> <br /> <span class="uk-heading-primary">my text in second line</span>'],
          typeSpeed: 50,
          startDelay: 0,
          backSpeed: 0,
          smartBackspace: true,
          shuffle: false,
          backDelay: 0,
          fadeOut: true,
          loop: false,
          contentType: 'html',
        });
  ```

### Description

[Description of the issue]

### Demo
[If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jon64digital** [comment]
Typed does not seem to deal well with multiple lines of text. On their own demo page they use \n for new lines but the second and third lines don't get typed out they just get dumped on screen.

**Comment by leafiy** [comment]
`<br>`
works for me
