### ISSUE TITLE
onStart does not fire

### ISSUE THREAD

**Issue by alpipego** [mattboldt/typed.js#365]
### Description

The `onStart` function never fires. 

### Demo
https://jsfiddle.net/1xs3LLmL/42/

### Steps to Reproduce

**Expected behavior:** fire `onStart`

**Actual behavior:** nothing

**Reproduces how often:** all the time

### Additional Information

Since it also happens in jsFiddle I'm confident it's not caused by my environment.

**Comment by RamIyer1998** [comment]
I'm experiencing a similar issue. Has anyone found a solution?

**Comment by JeffJassky** [comment]
Same.
