### ISSUE TITLE
Auto load on mouse click

### ISSUE THREAD

**Issue by rappercodes** [mattboldt/typed.js#366]
### Description

[Description of the issue]

I have text that loads using typed.js

I was wondering if there was a way to autocomplete the text when a customer does a mouse click.

### Demo
[If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/]

https://www.zuppclub.com/

^ This is a website using typed.js

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

When a customer clicks on the background the entire paragraph should be transparent immediately.

**Actual behavior:** [What actually happens]

None yet.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Binternet** [comment]
+1
