### ISSUE TITLE
React reinit on componentDidUpdate

### ISSUE THREAD

**Issue by mrkenng** [mattboldt/typed.js#367]
Hi guys!

I am using componentDidUpdate to check if the prevPros.speed !== this.props.speed to make changes.

How can I reinit with the new data? 

I'm not sure if I am doing it right since all the data values returned are correct. I this.typed.destroy(); if the prevPros is not the same then get data and pass it down again to this.typed = new Typed(this.el,options) again.

```
componentDidUpdate(prevProps, prevState){
		if(prevProps.speed !== this.props.speed ) {
			this.typed.destroy();
			console.log('I destroyed it');

			var speed = this.props.speed;
			console.log('speed:' + speed);
			
			const options = {
			  	strings: ["123","456"],
			 	typeSpeed: speed,
			 	startDelay: 0,
			 	loop: true,
			 	backSpeed: 20
		 	}
		 	this.typed = new Typed(this.el, options);
		}
	}
```

But sometimes the speed is acting funny, I have to put the speed to 0 again then after 10 it is acting like the speed of 100. 

Any advice would be much appreciated !

**Comment by mattboldt** [comment]
You shouldn't need to reinitialize it completely. You can do `this.typed.typeSpeed = 500;` to update the speed.
