### ISSUE TITLE
Stop/Pause typing

### ISSUE THREAD

**Issue by zembrowski** [mattboldt/typed.js#37]
Hi Matt,

is there a way to stop/pause the typing on an event, for example click or mouseover?

Cheers,
Krzysztof

**Comment by fredw** [comment]
+1

**Comment by chodorowicz** [comment]
+1

**Comment by mattboldt** [comment]
Busy with work so I dunno when I'll get to this, but I'd love to see a pull request! Even an incomplete one would be nice to get this going.

**Comment by mattboldt** [comment]
This was added here but has bugs. https://github.com/mattboldt/typed.js/pull/52
