### ISSUE TITLE
Weird type/backspace speed variances and the loops sticks on one word.

### ISSUE THREAD

**Issue by wearelfb** [mattboldt/typed.js#371]
### Description
Using typed.js right out of the box with minimal customization features, I'm seeing drastically different backspace and type speeds and it will eventually get stuck on one word and stop, even though it's supposed to loop. While looking at the inspector it's showing that the selector is "updating" the text, but it's just blinking the same word.

### Demo
https://jsfiddle.net/23m114vk/4/

### Steps to Reproduce
The JSFiddle is a very stripped down version of the live, but still seeing the same results.

**Expected behavior:** Normal typed.js type and backspace with an infinite loop, exactly what it's supposed to do.

**Actual behavior:** Varying type and backspace speeds, sometimes not even typing out or backspacing at all, and getting stuck on one word. 

**Reproduces how often:** Every time, but at different amounts of time before it gets stuck.

**Comment by ruanpetersen** [comment]
Exact same issue on my side, I have three animations running side by side (the same amount of text characters) and have been trying to synchronize them. I noticed the events would fire asynchronously in the beginning but fixed that with a window.onload function. Although after around 10-15 seconds the animations run out of sequence and glitch exactly as you have mentioned.

**Comment by mattboldt** [comment]
It appears to be a bug with `smartBackspace`. Please try to set `smartBackspace: false`.

**Comment by ngouy** [comment]
@mattboldt The problem seems indeed related to smartBackspace. But it's pretty useful.
I engaged a PR before finding the bug on smartBackspace which solved the problem (and potentially others)

**Comment by mattboldt** [comment]
Fixed in https://github.com/mattboldt/typed.js/pull/408 merged to master, awaiting a new release!
