### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by pimmesz** [mattboldt/typed.js#372]
Hi! I get the following error. All seem to originate inside the typed.js file?

```
typed.js:614 Uncaught TypeError: Cannot read property 'tagName' of null
    at Initializer.load (typed.js:614)
    at new Typed (typed.js:92)
    at loadDynamicBannerText (banner.js:4)
    at Object.<anonymous> (application.js:12)
    at __webpack_require__ (bootstrap 8600724e5aa2a02f3f07:19)
    at Object.defineProperty.value (bootstrap 8600724e5aa2a02f3f07:62)
    at bootstrap 8600724e5aa2a02f3f07:62
```

**Comment by Goolpe** [comment]
I added in main.js `import Typed from 'typed.js' ` and ```
new Typed('#typed', {
  	strings: ["some text","some  text"],
	typeSpeed: 10,
	backSpeed: 50,
	loop:true
})
``` in your file (for example app.vue or component.vue) you must to add <div id="typed"></div>

**Comment by mattboldt** [comment]
Yes, it cannot find the HTML element. Make sure you have it in your HTML.

**Comment by mrpinkcat** [comment]
If anyone have this error too, try to put the creation of the instance in the vuejs mounted method like this :
```javascript
new Vue({
	created: function () {
		new Typed('#typed',  { strings: ["test1", "test2"] }
	}
});
```

**Comment by vozille** [comment]
> If anyone using vuejs and have this error too, try to put the creation of the instance in the vuejs mounted method like this :
> 
> ```js
> new Vue({
> 	mounted: function () {
> 		new Typed('#typed',  { strings: ["test1", "test2"] }
> 	}
> });
> ```

@mrpinkcat the example has created instead of mounted. Declaring on created method wont work, as the template isn't complied
