### ISSUE TITLE
Type.js works fine in one page. It affects other pages not using it.

### ISSUE THREAD

**Issue by surendrapathak01** [mattboldt/typed.js#374]
### Description

I have two static HTML pages. Both of them use a single javascript file. I have initialized typed.js in that js file. One of HTML pages uses typed.js. It works perfectly as I expect and there is no error in the console. On the other page I have not used Typed.js. But there is this error in console in this particular page: 
Uncaught TypeError: Cannot read property 'tagName' of null
    at t.value (typed.min.js:10)
    at new t (typed.min.js:10)
    at HTMLDocument.<anonymous> (script.js:102)
    at fire (jquery.min.js:3077)
    at Object.fireWith [as resolveWith] (jquery.min.js:3189)
    at Function.ready (jquery.min.js:433)
    at HTMLDocument.completed (jquery.min.js:104)

**Expected behavior:** I think this is happpening because typed.js cannot find the targetted element on the second page. Is there a way to fix this issue by writing all javascript code in a single file itself? How can I do it?

**Comment by mattboldt** [comment]
Looks like it's being triggered from your script file (`script.js`). In that file, I'd check to make sure the HTML element exists before doing a `new Typed()`
