### ISSUE TITLE
Can we remove the erasing effect?

### ISSUE THREAD

**Issue by partolepaurnima** [mattboldt/typed.js#383]
### Description

Don't want to erase the text which is appending into the structure.

### Steps to Reproduce: NA

**Expected behavior:** Expecting only typing effect not erasing

**Actual behavior:** It is removing string after typing effect

**Reproduces how often:** NA

**Comment by teefan** [comment]
Just learned that you could use `fadeOut: true` option to hide the sentence, instead of backspacing, then append the completed typing sentence into a previous list container via `onStringTyped`.

Check https://mattboldt.com/typed.js/ for examples.
