### ISSUE TITLE
Uncaught TypeError on array with 3 or more elements

### ISSUE THREAD

**Issue by Gunsway** [mattboldt/typed.js#386]
**### Description**

Passing arrays to typed var with more than 3 elements throws an error:

`typed.js:231 Uncaught TypeError: Cannot read property 'substr' of undefined
    at typed.js:231`

**### Demo**
Create new Typed...

`var typed = new Typed("#typed", {
	strings: ['Loading: ........','Loading ........','Loading ........'],
	smartBackspace: true,
	typeSpeed: 30,
	startDelay: 1200,
	backSpeed: 70,
	backDelay: 2000,
	loop: true,
	showCursor: false,
	contentType: 'text'
});
`

Get data from text file...

`
function getLabelText(path)
{
	var streamLabelOutput = [""];

	jQuery.get(path, function(data) {
		var inputText = (data).split("\n");
		for (index = 0; index < inputText.length; ++index)
		{
			if (typeof inputText[index] === 'string')
			{
				var titleAndResponse = labelTitle.concat(inputText[index]);
				streamLabelOutput.push(titleAndResponse);
			}
		}
	 });

	return streamLabelOutput;
}
`

Update typed with new strings[]...

`function typewriter()
{
	var labelInfoPath = rotateStreamLabel();
	typed.strings = getLabelText(labelInfoPath);
	typed.reset();
}`

**Expected behavior:** I expect typed to step through each element of the array.

**Actual behavior:** Typed throws an error on 3rd element of the array.

**Reproduces how often:** 100%

**Comment by aaronware** [comment]
I know this is an older issues but.. random thought as I just happened to click on this. Is it due to you incrementing your index of your for loop using ++index vs using index++ (which is typically more traditional)
