### ISSUE TITLE
Carriage return support to simulate terminal style carriage return.

### ISSUE THREAD

**Issue by athakwani** [mattboldt/typed.js#388]
### Description
Provide carriage return support to simulate terminal style carriage return. This is very useful to simulate terminal based progress bars. 

### Example
var typed = new Typed('#typed', {
                   strings: ['\
$ ^1000docker pull mongodb^1000\n\
`Using default tag: latest\n\
latest: Pulling from library/mongo`\n\
`e42838071bcb: Downloading [===>                                                                 ]  10MB/100MB`^500\r\
`e42838071bcb: Downloading [========>                                                     ]  20MB/100MB`^500\r\
`e42838071bcb: Downloading [============>                                           ]  30MB/100MB`^500\r\
`e42838071bcb: Downloading [================>                                 ]  45MB/100MB`^500\r\
`e42838071bcb: Downloading [====================>                       ]  55MB/100MB`^500\r\
`e42838071bcb: Downloading [========================>             ]  70MB/100MB`^500\r\
`e42838071bcb: Downloading [============================>   ]  85MB/100MB`^500\r\
`e42838071bcb: Downloading [=============================>]  100MB/100MB`^500\r\
`e42838071bcb: Download complete`\n\
'], 
                 typeSpeed:30, 
                 loop:false,
                 cursorChar: "█",
                 onTypingPaused: function(pos, self) { $('#content').scrollTop($('#content')[0].scrollHeight); },
                 onTypingResumed: function(pos, self) {  $('#content').scrollTop($('#content')[0].scrollHeight); }
});

**Comment by athakwani** [comment]
@mattboldt Could you please implement or suggest an alternate way to implement terminal style progress bar?

**Comment by mattboldt** [comment]
I'm not sure what you want here, but you removed the entire issue template, your code isn't formatted, and you didn't provide any link to a demo.

If you want something very custom to your needs, I'd suggest forking the code or building it separately.

**Comment by athakwani** [comment]
Apologies for not being clear. In Linux style terminals we have the carriage return (\r) and line feed (\n) characters. The purpose of \r is to move the cursor back to the start of the line and \n is to move the cursor to the next line. \r is frequently used to mimic the terminal based progress bar by continuously writing on the same line with updated values. Typed.js support \n to move the cursor on next line, but I am looking for a way to move the cursor at the start of the line. This way I can simulate terminal based progress bar as I mentioned in the example above. Please let me know how much effort will be required to make this work, also any pointers on how to implement would be really helpful.

**Comment by athakwani** [comment]
Nevermind I figured an alternative way to do it.
