### ISSUE TITLE
Initialize with existing text.

### ISSUE THREAD

**Issue by ardoramor** [mattboldt/typed.js#39]
It would be great if the plugin could have an option to initialize with an existing text. For example, if the following element would be blessed with typed.js plugin, it would notice that the `attr` option is not specified and the element contains text. 

```
<span class="typed-text">This text will not be typed!</span>

$('.typed-text').typed({
    strings: ['This text will be typed'],
    attr: null,
    ...
});
```

As such, it would jump to the backspace timeout and the first action would be is to erase the default text and type out the text specified in the `strings` array.

**Comment by daattali** [comment]
Similar suggestion: I was hoping there'd be a way to allow the text to be specified within the HTML, something like this 

`<span class="typed-text" data-typed="['One', 'Two']"></span>`

And then all you have to do in JS is initialize the typed plugin, without having to have excessive text in the JS

**Comment by jeremypbeasley** [comment]
+100 for this one.

At minimum, if I can set a var to be the string of text in the element, can you show how I would set the option to match that var?

**Comment by ChristofferJoergensen** [comment]
Any updates on getting the pull request from @jlukic ready for merge?

**Comment by x43x61x69** [comment]
I think this will do, at least if you just wanted to get the value then type. Save the trouble for `<noscript>` situation:

```javascript
    $(function(){
        var str = $( ".class-to-typed" ).text();
        $( ".class-to-typed" ).empty();
        $(".class-to-typed").typed({
    			strings: [str],
    			typeSpeed: 60,
    			showCursor: true,
    			startDelay: 600
        });
    });
```

**Comment by KyleMit** [comment]
Still not sure if this is possible, but this line `this.strings.unshift(self.baseText);` in [PR#43](https://github.com/mattboldt/typed.js/pull/43/files) got me thinking.  If the trick is just to use the existing HTML as the first element in the array, you can just add that to the `strings` option, like this:

### [Demo in jsFiddle](https://jsfiddle.net/KyleMit/7vrhgq80/)

```html
<span id="existing-text">Replace Me</span>
```

```js
var typed = new Typed('#existing-text', {
  strings: ["Replace Me", "New Text"]
});
```
