### ISSUE TITLE
Constructor error in test with Angular 6 + Jest 23 + Typed.js 2.0.9

### ISSUE THREAD

**Issue by squelix** [mattboldt/typed.js#391]
### Technologies

```
    "@angular/animations": "6.1.1",
    "@angular/common": "6.1.1",
    "@angular/compiler": "6.1.1",
    "@angular/core": "6.1.1",
    "@angular/forms": "6.1.1",
    "@angular/http": "6.1.1",
    "@angular/platform-browser": "6.1.1",
    "@angular/platform-browser-dynamic": "6.1.1",
    "@angular/router": "6.1.1",
    ...
    "typed.js": "^2.0.9",
    ...
    "jest": "^23.5.0",
```

### Description

I'm using typed.js 2.0.9 in my Angular application. It works correctly with `ng serve` or `ng build`
 but when i launch my test with Jest i have this error:
```
TypeError: typed_js_1.default is not a constructor

      32 |   createTyped() {
    > 33 |     new Typed(this.elem.nativeElement, {
         |     ^
      34 |       strings: this.appTypedAnimation,
      35 |       typeSpeed: this.typeSpeed,
      36 |       backSpeed: this.backSpeed,
```
I'm importing it this way `import * as Typed from 'typed.js';`.

### Steps to Reproduce

1. Launch the test in Angular app with Jest

**Expected behavior:** Test passed

**Actual behavior:** Test failed

**Reproduces how often:** Everytime

### Additional Information

I think the `index.d.ts` has an error because when i roll back the version to 2.0.8 and imports it this way `import * as Typed from 'typed.js';` it works well.

**Comment by mattboldt** [comment]
Hrm. Yeah it must be a bug in the definition, since that was introduced in v2.0.9. https://github.com/mattboldt/typed.js/pull/380

Could you take a look at `index.d.ts` and see if there's anything amiss? I'm not very familiar with typescript definitions. It was added and tested by other contributors. Thanks for the report!

**Comment by squelix** [comment]
The `index.d.ts` is correct, the problem was on me.
So I fixed my problem using Jest mocks.
At the root of my project I created a file `/__mcoks__/typed.js.ts` and i put that inside:
```
export default class Typed {
  constructor(elementId: string, options: any) {}
  toggle(): void {}
  stop(): void {}
  start(): void {}
  destroy(): void {}
  reset(restart?: boolean): void {}
}
```

And it fixed my problem in my tests.
Thank you for your quick answer ;)

**Comment by mattboldt** [comment]
no problem! thanks

**Comment by AnshulRiyal** [comment]
@mattboldt Is this bug fixed?

**Comment by Goopher** [comment]
@mattboldt, I'm also chiming in here. Using it within Angular 9 including Server Side Rendering I also get this issue. @squelix , would you know what the issue causes maybe?
