### ISSUE TITLE
Always skip the first element if the container has string

### ISSUE THREAD

**Issue by dolphinotaku** [mattboldt/typed.js#392]
### Description
typed.js will skip the first element if the container has string, I am not sure if this is an issue or design.

### Demo
https://jsfiddle.net/03y8mtbL/

### Steps to Reproduce
open the webpage

**Expected behavior:** [What you expect to happen]
clear the text within the container before typing the text, type-in the first element in strings array first

**Actual behavior:** [What actually happens]
the first element in strings was skipped.

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by BenQuirk** [comment]
What worked for me is changing my container from a div to a span. 

original: (skips first line)
 <div class="typed-effect-container"></div>

changed to this: (yay now the first line is not skipped!)
 <span class="typed-effect-container"></span>
