### ISSUE TITLE
Multiple typed elements.

### ISSUE THREAD

**Issue by dimative** [mattboldt/typed.js#396]
Hello guys. I need some help. I want to use typed.js on one page multiple types scripts. But i can't do this. Here is my code. Sorry my poor English.

***JS

    $('.typed').each(function() {
            var typeds = {};
            var counter;
            console.log($(this).data('typed'));
            counter++;
            typeds['typed' + counter] = new Typed($(this), {
                stringsElement: '#' + $(this).data('typed'),
                typeSpeed: 0,
                backSpeed: 0,
                backDelay: 500,
                startDelay: 1000,
                loop: false,
            });
        });

***HTML
<code>&#x3C;div id=&#x22;typed2&#x22; class=&#x22;invisible display-none&#x22;&#x3E;
&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;    &#x3C;p&#x3E;Chars &#x26;times; &#x26;copy;&#x3C;/p&#x3E;
&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;    &#x3C;p&#x3E;stringsElement test&#x3C;/p&#x3E;
&#x9;&#x9;&#x9;            &#x9;&#x3C;/div&#x3E;
&#x9;&#x9;&#x9;&#x9;            &#x9;&#x3C;span class=&#x22;typed&#x22; data-typed=&#x22;typed2&#x22;&#x3E;
&#x9;&#x9;&#x9;&#x9;&#x9;            &#x3C;/span&#x3E;</code>
Is it possible?

**Comment by peterennisrda** [comment]
Maybe this will help:
https://stackoverflow.com/questions/29462305/how-to-create-a-typewriter-effect-in-javascript-that-will-take-into-account-html

**Comment by mattboldt** [comment]
please provide demos

**Comment by DeoThemes** [comment]
I'm having the same issue. Having a multiple instances on the page and they all messed up. I'm initializing it like so:

let typed = new Typed('.deo-typed__text-animated', {
    stringsElement: '.deo-typed__strings',
    loop: settings.loop,
    typeSpeed: settings.typeSpeed,
    backSpeed: settings.backSpeed,
    backDelay: settings.backDelay,
    startDelay: settings.startDelay,
});

**Comment by mattboldt** [comment]
@DeoThemes I'll need to see a demo to be able to troubleshoot. Please fork and modify this jsbin https://jsfiddle.net/mattboldt/1xs3LLmL/

**Comment by DeoThemes** [comment]
I switched to 1.1.7 version and everything works fine now. I'm using typed method now instead of instantiating a new object with new keyword. Is there any downside of using older version?

**Comment by BrunoBoehm** [comment]
Hi @mattboldt 

Im a trying to animate two divs on the page that share the same class, so far only the first occurence gets animated.

Here's a jsbin to show you what i'm trying to do. What would be the cleaner way.
https://jsfiddle.net/gcj9rv7y/

I do want to be able to use stringElements to keep the SEO benefit.
Thanks a lot for letting me know what would be the most elegant solution.
Bruno
