### ISSUE TITLE
Pass data attribute from source html

### ISSUE THREAD

**Issue by admrbsn** [mattboldt/typed.js#398]
If I'm referencing a div work data attributes, is there a way to easily pass said data attributes to the generated typed element? So something like <span id=typed" data-attribute=red">re...</span>?

**Comment by mattboldt** [comment]
If you must use data attrs to store your strings, you could grab them before typed is initialized
```js
let strings = element.dataset.strings.split('<a char to split on>')
new Typed({ strings: strings });
```
