### ISSUE TITLE
elementId / self.el becomes an array of objects : tagName is undefined

### ISSUE THREAD

**Issue by ArianeNubee** [mattboldt/typed.js#403]
**I realized I was calling the plugin wrong; there needs to be a separate container for Typed. I'm ashamed.**

### Description

I'm not sure why, but at line 606 of typed.js, instead of being a straight div, elementId is an array-like object of containing the div, which makes the .tagName check from line 617 fail.

### Demo
[If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/]

https://jsfiddle.net/sqtb46Ld/

### Steps to Reproduce

N/A

**Expected behavior:** [What you expect to happen]

I'd expect that mysterious array-like object to be handled.

**Actual behavior:** [What actually happens]

It's not handled. The code expects a straight DOM node, but even if I send it a straight DOM node in my declaration, it's converted into an array-like object at some point.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100 %

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

I tried a quick fix for the issue : I replaced line 611 from :

`self.el = elementId;`

to :

`self.el = elementId[0];`

It fixes the JS error, but Typed doesn't recognize my strings. I only get a blinking cursor.

**Comment by mattboldt** [comment]
looks like this is resolved!
