### ISSUE TITLE
How to start typing animation on event trigger.

### ISSUE THREAD

**Issue by gyenabubakar** [mattboldt/typed.js#404]
I want to make the typing animation start when an even occurs. For instance, I've designed a page where the user has to scroll down a bit before they see the typing animation; it will hence be awkward to start the animation before the element is being viewed in the viewport. So is there a way I can start the animation as a handler to the scroll event?

**Comment by bitmanic** [comment]
@gyen02 You posted this issue a long time ago. I'm not sure if you still want an answer, but the solution is found outside of this library. I would suggest using something like [Waypoints/Inview](http://imakewebthings.com/waypoints/shortcuts/inview/) to determine when the user has scrolled down to a specific part of the page, and then instantiate the Typed.js instance once that has happened.
