### ISSUE TITLE
JQuery targeting elements within Typed content not working

### ISSUE THREAD

**Issue by poastertoaster** [mattboldt/typed.js#407]
### Description

Using JQuery commands targeting the elements within the typed content does not work. Appended text does not use the typing effect.

### Steps to Reproduce

1. Create a typed sentence, with an element within for JQuery to target
2. Create a JQuery command targeting the element, using an append command will show the lack of additional typing

**Expected behavior:**

JQuery commands targeting elements within the typed effect should behave normally.

**Actual behavior:**

JQuery commands only work when targeting elements outside of the typed effect.

**Comment by mattboldt** [comment]
It's tough to externally manipulate elements actively being typed on the page. You can't just append text because Typed wouldn't be aware of the new changes made after init. Try checking out Typed's API and maybe make your changes there instead of via jquery?
