### ISSUE TITLE
Add typedjs to cdnjs

### ISSUE THREAD

**Issue by marcioAlmada** [mattboldt/typed.js#41]
Because this library is awesome and should be available at http://cdnjs.com/

https://github.com/cdnjs/cdnjs

**Comment by santosh** [comment]
You can always use rawgit.com.

https://cdn.rawgit.com/mattboldt/typed.js/master/js/typed.js

**Comment by santosh** [comment]
And this issue should be closed in favor of #49

**Comment by BrianDillingham** [comment]
+1

**Comment by santosh** [comment]
Matt is not maintaining this repo for a long time. :/

**Comment by ChaseGiunta** [comment]
Wtf Matt, c'mon.

**Comment by jbkunst** [comment]
So sad

**Comment by vishwakarma09** [comment]
this should be added in cdnjs. For almost every script I look upto cdnjs
