### ISSUE TITLE
Is there a way to continue the execution of the script if window is not on focus?

### ISSUE THREAD

**Issue by carlitoselmago** [mattboldt/typed.js#414]
I'm running an animation wich combines typed.js with other timed events and they all need to continue running even if window is not on focus. It is a 24h long animation for an art event so it is not about syncing but to be able to check the animation every certain hours.

**Comment by mattboldt** [comment]
IIRC it is a relatively new feature in chrome/FF/etc that disables running javascript when you switch tabs. I don't know of any way to circumvent this.

**Comment by carlitoselmago** [comment]
One way would be to calculate the time between last focus and the
characters that would had been animated and just print them without
animation. Just an idea if this becomes a popular feature request. On my
case i solved it using a dirty version of what i just expalined.
