### ISSUE TITLE
Uncaught ReferenceError: Typed is not defined

### ISSUE THREAD

**Issue by jmwordpress** [mattboldt/typed.js#415]
I get the following error when on looking at my wordpress website Uncaught ReferenceError: Typed is not defined.

I followed this tutorial https://oxygen4fun.supadezign.com/tutorials/animated-heading/ .
In the editor tool from oxygen builder it works just fine.

Code:

var typed = new Typed(".typefx1", {
    strings: ["awesome", "great", "beautiful", "amazing"],
    smartBackspace: true,
    typeSpeed: 50,
    backSpeed: 50,
    loop: true
});

**Comment by mattboldt** [comment]
Hm, not sure. Make sure you're importing the javascript lib on your wordpress page
