### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tagName' of null 

### ISSUE THREAD

**Issue by bestvayne** [mattboldt/typed.js#417]
### Description
Hello , I'm Chinese developer. When I use typed.js, it's wrong.

for example:
It's work in homepage ，everything's fine. But when I switch other page, for  example "about page", chrome dev tool is throw an error 

> Uncaught TypeError: Cannot read property 'tagName' of null
    at Initializer.load (app.js:1208)
    at new Typed (app.js:683

when I see it's source code
![image](https://user-images.githubusercontent.com/11917682/57154778-4652b880-6e0c-11e9-85ae-347d1f6610fd.png)

if current page is not have `<span id="typed"></span>` ,maybe throw this error, and must be important problem is that it will Influence my other javascript code running.

I want to know , how to solve this problem 

### My code framework
 Laravel 5.8

And I set route , switch page is use route

**Comment by mattboldt** [comment]
`<span id="typed"></span>` must be present on the page for the code to initialize. If you don't want to initialize it for a given page, you could first check if your element exists before calling the rest of the code. e.g.
```js
const el = document.querySelector('.element');
if (el) {
  new Typed(...)
}
```
