### ISSUE TITLE
Console generating Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by szczepkacpra** [mattboldt/typed.js#419]
Hello Matt, 

I'm building my first non-WP website and trying to take advantage of your library.

```
<head>
  ...
  <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.9"></script>
  <script>
    import Typed from 'typed.js';

    var options = {
      strings: ["String A", "String B", "String C"],
      typeSpeed: 40
    }

    var typed = new Typed(".element", options);
  </script>
</head>
```

generates console error

> Uncaught SyntaxError: Unexpected identifier

on the line

`import Typed from 'typed.js';`

I'm hoping that fixing that issue, will display strings in:

`<h2><span id="typed"></span></h2>`

I'm hitting my head against the wall for few hours now and run out of ideas on fixing it. Could you please give me a hand?

**Comment by mattboldt** [comment]
You should only need the `script` tag in this case, not the `import Typed from 'typed.js';`
