### ISSUE TITLE
Stop typing and show all text

### ISSUE THREAD

**Issue by bohdan-jdev0** [mattboldt/typed.js#421]
Have some bugs, I guess, in safari. If I have the text ( > 100 characters  ) in one time it stops typing and in a few seconds shows me all text ... This bugs I have seen only on Safari

DEMO
https://jsfiddle.net/z905jxrs/2/

**Comment by gheorghedarle** [comment]
@bohdan-jdev0 Try to put `contentType: null` in the options.
