### ISSUE TITLE
Update component when strings value changing

### ISSUE THREAD

**Issue by NmiDev** [mattboldt/typed.js#422]
### Description

Hi, 

Thanks for this job ! 

I'm using Typed.js with React.js configuration. I'm updating my application with multlingual support.

I want to know if there is a simple way to update my component Typed.js when strings are update in the application state. 

### Demo
My component : 
```
class TypedJs extends React.Component {
  static propTypes = {
    strings: PropTypes.arrayOf(PropTypes.string).isRequired,
  }

  componentDidMount() {
    const { strings } = this.props;

    const options = {
      strings,
      startDelay: 20,
      typeSpeed: 150,
      backSpeed: 100,
      shuffle: false,
      backDelay: 1000,
      loop: true,
      loopCount: Infinity,
    };

    this.typed = new Typed(this.el, options);
  }


  componentWillUnmount() {
    this.typed.destroy();
  }

  render() {
    return (
      <div className="wrap">
        <div className="type-wrap">
          <span
            className="types"
            ref={(el) => { this.el = el; }}
          />
        </div>
      </div>
    );
  }
}
```

**Expected behavior:** My strings came from the state, When I choose an other language for my app, I update my strings in the state.

**Actual behavior:**  The state change but my is not reload

I tried many way without success. 

Thank you for your support.

**Comment by okboy5555** [comment]
Similar to my situation, my string will continue to grow
