### ISSUE TITLE
Calling custom function before each new string using preStringTyped

### ISSUE THREAD

**Issue by bmessenger** [mattboldt/typed.js#424]
### Description

Trying to fire a custom function before each new string is typed.  Would like the strings to loop, use smart backspace, and be SEO friendly.  Is this possible?

jsfiddle:  https://jsfiddle.net/bmess/qcpfs4n9/1/

**HTML**
```
<h1 id="typed-strings" class="page-title">
  <span>Built to be Autonomous.</span>
  <span>Built to be Reliable.</span>
  <span>Built to be Portable.</span>
  <span>Built to Last.</span>
</h1>
<h2 class="h1 page-title">
  <span id="typed"></span>
</h2>
```

**JS**

```
var typed = new Typed("#typed", {
  stringsElement: '#typed-strings',
  typeSpeed: 50,
  backSpeed: 10,
  backDelay: 2000,
  smartBackspace: true,
  loop: true,
  loopCount: false,
  preStringTyped: function(index, self) {
    alert(index);
   // Fire custom function here
 },
});
```

**Expected behavior:** 
Code above should throw alert after every new string is beginning to start.  It loops through with smart backspacing however it's not trowing an alert before each new string is typed out.  Any ideas?

**Comment by TwistedAndy** [comment]
I'm getting the same issue when the **smartBackspace** is set to **true**.

**Comment by guidoferreyra** [comment]
Same here when, smartBackspace is set to true there is now event triggered besides the first one. Any workarounds? Thanks
