### ISSUE TITLE
Issue with shuffling strings

### ISSUE THREAD

**Issue by newtykins** [mattboldt/typed.js#427]
### Description

Every now and then, when the shuffle option is enabled and a string has just been typed, the string gets replaced with the next string and that string gets removed and a new string is written in its place.

### Steps to Reproduce

1. Create an instance of typed.js
2. Enable the shuffle option
3. Wait for it to happen

**Expected behavior:** I expect the next string to appear after the typing being emulated by typed.js

**Actual behavior:** The next string instantly appears, gets removed through backspaces, and then a new string is written.

**Reproduces how often:** I can not calculate how often this happens due to it's random nature.

**Comment by schweigert85** [comment]
having this same problem, once in a while the next string will swap in vs the previous one being deleted first

**Comment by arvathrowaway** [comment]
I'm also getting this. Anybody find a reason why it's happening?

**Comment by itsnewt** [comment]
I'll have a look into it. Not entirely sure right now.

**Comment by Recepcan** [comment]
I am still experiencing this problem. It looks like it has not been solved for the last two years.

**Comment by newtykins** [comment]
I completely forgot about this. Bumping just so the issue doesn't close - I'll actually check it out this time fsdjkhgfgjsdhk

**Comment by Bluebotlabz** [comment]
This is still a problem
