### ISSUE TITLE
Animating duplicate stringElements on the same page doesn't work

### ISSUE THREAD

**Issue by BrunoBoehm** [mattboldt/typed.js#433]
Hi @mattboldt

Im a trying to animate two divs (that use stringElements) on the page that share the same class, so far only the first occurence gets animated.

Here's a jsbin to show you what i'm trying to do. What would be the cleaner way.
https://jsfiddle.net/xbofduaz/

I do want to be able to use stringElements to keep the SEO benefit.
Thanks a lot for letting me know what would be the most elegant solution.
Bruno

**Comment by harnishdesign** [comment]
I got perfect solution for multi typed. 

**Working Demo** - https://jsfiddle.net/ebjzmLur/

You can check here - 
https://stackoverflow.com/questions/60987209/how-to-implement-multi-typed-elements-in-single-page-with-single-function/60987511
