### ISSUE TITLE
I think you need to add eventlistener to make typed.js work?

### ISSUE THREAD

**Issue by adnjoo** [mattboldt/typed.js#434]
```
<script>
  document.addEventListener('DOMContentLoaded', function() { var typed = new Typed("#typed", { stringsElement:'#typed-strings', typeSpeed: 40, }); });
</script>
```

or maybe I am missing something? but before I added the above code it wasn't working, I still get this error:
```
TypeError: Cannot read property 'tagName' of null
    at t.value (typed.js@2.0.11:10)
    at new t (typed.js@2.0.11:10)
    at index.html:6
value @ typed.js@2.0.11:10
t @ typed.js@2.0.11:10
(anonymous) @ index.html:6
```

**Comment by therealgabryx** [comment]
You should’ve replaced ’#typed’ with the target ID of the html element you were trying to animate. 

'tagName' of null = can’t find the element

also inside ’stringsElement’ you should put the text to be replaced with.. you’ll find more info on the readme of the repo!
