### ISSUE TITLE
Does not work if the initial element is not empty

### ISSUE THREAD

**Issue by alex-jitbit** [mattboldt/typed.js#435]
```html
<b id="typed">string1</b>
<b id="typed-strings" style="display:none">
    <b>string1</b> <b>string2</b>
</b>
```

The workaround is to empty it via JS before loading your plugin

**Comment by muhroots** [comment]
It would be great.

**Comment by gremo** [comment]
I second that. Any workaround? It would be great because, as the page load, the target element has a height o 0px. Then when typed start to type, the span "grows" in height, making the layout flickering (depending on the situation).

**Comment by alex-jitbit** [comment]
bump
