### ISSUE TITLE
TypeError: t.el is null

### ISSUE THREAD

**Issue by kasposten1337** [mattboldt/typed.js#438]
### Description

When I try to use the library I get an console log that says "TypeError: t.el is null". Are there any fixes this?

### Demo
This is my javascript code:
var options = {
    strings: ['<i>First</i> sentence.', '&amp; a second sentence.'],
    typeSpeed: 40
  };
var typed = new Typed('.jsTypingEffect', options);
and I load the scripts in this order:
    <script src="typed.js-2.0.11\lib\typed.min.js"></script>
    <script src="javascript.js"></script>

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
The object to log to the console
**Actual behavior:** [What actually happens]
Error message
**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by flleeppyy** [comment]
Its been a year since this issue was opened and I also have it. *insert pain and agony here*

**Comment by flleeppyy** [comment]
Okay so for me, what's causing the issue is Prism.js. Just it existing will make Typed.js not work.
