### ISSUE TITLE
[React] Problems with useState and start stop typing

### ISSUE THREAD

**Issue by BaptisteMonet** [mattboldt/typed.js#442]
### Description

Hello, here is the problem, I try  stop and start with useState
but it's look like there is some bug (just see by yourself in the following link
When onClick we modify the state (in anyway) the animation don't stop an sometimes got crazy

### Demo
[Here is the demo](https://frontarm.com/demoboard/?id=a732e7c7-5696-40b3-97c6-566067750683)

### Steps to Reproduce

1. Just click on button start an start the animation
2. Just click on button stop an nothing happen
3. Just repeat action 2 or 1 many times  and see animation got crazy

**Expected behavior:**  Just the animation should stop when we click on stop button
**Actual behavior:** look at => steps reproduce

**Reproduces how often:** well unfortunately everytime

**Comment by robschwitzer** [comment]
I think this is an issue with your code and not the library. In BubbleTalk.js useEffect, you have your state variables as part of the dependency array. Every time those variables change, you create a new instance of typed, hence the weird behaviour.

**Comment by mattboldt** [comment]
Yeah, looks like you're creating multiple instances of typed instead of playing & pausing one. Here's an example using react w/ componentDidMount and a ref, but I'm sure you can rework it to use the useRef and useEffect

https://jsfiddle.net/mattboldt/ovat9jmp/

**Comment by BaptisteMonet** [comment]
oh ok thx !
I just update the link I give in case of someone need it
