### ISSUE TITLE
Cannot install the module using npm install

### ISSUE THREAD

**Issue by janpansa** [mattboldt/typed.js#447]
### Description

Cannot install the module.

### Steps to Reproduce

1. npm install --save vue-typed-js

**Expected behavior:**

Should install like any other npm module does in my package.json

**Actual behavior:**

```
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/mattboldt/typed.js.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Reproduces how often:**

100%

### Additional Information

This only happens with this npm module on my computer. All other npm modules install fine.

I have it listed in my package.json like so:
```
...
 "dependencies": {
   ...
    "vue-typed-js": "^0.1.2"
   ...
  },
```

and have also tried to install it manually like so:

`npm install --save vue-typed-js
`

it used to install fine, however now it stopped working.

I also deleted my package-lock.json file and also cleared my npm caches.

**Comment by janpansa** [comment]
Issue was because the npm container I used with docker did not have git installed. Somehow I missed that.

**Comment by LeCoupa** [comment]
For other people: here is how you can install it in your Dockerfile.

```
RUN apk update
RUN apk add git
```

https://dockerlabs.collabnix.com/beginners/dockerfile/lab1_dockerfile_git.html
