### ISSUE TITLE
Glitch?

### ISSUE THREAD

**Issue by tex4272** [mattboldt/typed.js#448]
Has anyone seen seen this kind of behavior on mobile devices? We're getting chopped words.

https://youtu.be/T9Ujo4woOHg

All you have to do is visit the homepage to see it.

**Comment by EliasNaffaa** [comment]
I'm having the same issue, did you resolve it yet?

**Comment by tex4272** [comment]
Yes. It was our hosted web font. We switched to a standard web compatible font and the issue went away.

**Comment by EliasNaffaa** [comment]
Didnn't work with me, I'm still facing the issue, it was only chopping on 1 sentence when it was aligned left, aligned it to center, words are a mess even more now...
