### ISSUE TITLE
How to implement multi typed elements in single page ?

### ISSUE THREAD

**Issue by marwan2** [mattboldt/typed.js#449]
Handle multi typed elements in single page
Is this feature supported ?

**Comment by harnishdesign** [comment]
I am also looking for that.

**Comment by marwan2** [comment]
OK actually I did that, but adding more than 2 doesn't work !!!

**Comment by marwan2** [comment]
It seems due to adding it on a Slider, so only 2 slides only allow Typed to work

**Comment by harnishdesign** [comment]
I got perfect solution for multi typed. 

**Working Demo** - https://jsfiddle.net/ebjzmLur/

You can check here - 
https://stackoverflow.com/questions/60987209/how-to-implement-multi-typed-elements-in-single-page-with-single-function/60987511
