### ISSUE TITLE
preStringTyped not triggered on words with same beginning, when smartBackspace is true

### ISSUE THREAD

**Issue by dnlmzw** [mattboldt/typed.js#450]
### Description
Words in the strings array that start with the same letters (e.g. *en*gage and *en*tertain) doesn't trigger the `preStringTyped` since they are never completely removed.

### Steps to Reproduce
```
var typed = new Typed('.word', {
    strings: ['show','entertain','engage','play'],
    typeSpeed: 40,
    loop: true,
    loopCount: Infinity,
    backDelay: 1000,
    preStringTyped: (index) => {
    	console.log('index', index);
    },
  });
```
**Expected behavior:** 
`preStringTyped` should run every loop

**Actual behavior:**
The `preStringTyped`-event for the word 'engage' is skipped

**Reproduces how often:**
100%

**Comment by rishpandey** [comment]
I am facing this as well.

**Comment by ochen1** [comment]
I am encountering this issue also.

**Comment by ochen1** [comment]
Is this the same as #272?
