### ISSUE TITLE
shuffle:true will cause an exception to the display.

### ISSUE THREAD

**Issue by a690089735** [mattboldt/typed.js#459]
### Description
shuffle:true will cause an exception to the display.
when shuffle:true:
       Random text, but missing typing and fallback effects.

### Demo
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	</head>
	<body>
		<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
		<!-- //目标容器 -->
		<div style="text-align: center;">
			<span class="element"></span>
		</div>
		
		<script>
		    var typed = new Typed('.element', {
		      strings: ["1111纠正一个错误的方法有很多", "2222而解决一个错误的终极方法，就是不给它发生的机会。", "3333不为无益之事，何以遣有涯之生。"], //输入内容, 支持html标签
		      typeSpeed: 50, //打字速度
			  startDelay: 0, //延迟开始,没啥用,只在每组循环的第一次开始时有效
		      backSpeed: 30 , //回退速度
			  backDelay: 2500, //延迟回退
			  shuffle: true, //随机洗牌,开了会出问题,后续输入没有打字效果,在打字完突然变化.
			  loop: true , //循环
		    });
		</script>
	</body>
</html>
```

### Steps to Reproduce

1. Run

**Expected behavior:** Random text displays normally.

**Actual behavior:** Random text, but missing typing and fallback effects.

**Reproduces how often:** always.

### Additional Information

none

**Comment by mattboldt** [comment]
Try setting `smartBackspace: false`. Also, please attach a live demo like the template suggests
