### ISSUE TITLE
How Can I Hide The Cursor After The Writing Is Finished With React

### ISSUE THREAD

**Issue by programmer-mugdho** [mattboldt/typed.js#463]

**Comment by zhanyuzhang** [comment]
You can hide the cursor on complete event:
```
<body>
  <div id="root">
    <span class="typed" id="typed"></span>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.5/typed.min.js"></script>
  <script>
    const typedInstance = new Typed(document.getElementById('typed'), {
      typeSpeed: 60,
      showCursor: true,
      strings: ['Are you OK?'],
      onComplete() {
        typedInstance.cursor.remove();
      }
    })
  </script>
</body>
```

**Comment by SnowMeteors** [comment]
> You can hide the cursor on complete event:
> 
> ```
> <body>
>   <div id="root">
>     <span class="typed" id="typed"></span>
>   </div>
>   <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.5/typed.min.js"></script>
>   <script>
>     const typedInstance = new Typed(document.getElementById('typed'), {
>       typeSpeed: 60,
>       showCursor: true,
>       strings: ['Are you OK?'],
>       onComplete() {
>         typedInstance.cursor.remove();
>       }
>     })
>   </script>
> </body>
> ```

it's not working , the cursor not hide After The Writing Is Finished and the code not to the next line
this's is my code
``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
  </head>
  <body>
    <span id="typed6"></span>
    <script>
	var typed6 = new Typed('#typed6', {
	  typeSpeed: 60,
	  showCursor: true,
	  strings: ['npm install^1000\n `installing components...` ^1000\n `Fetching from source...`'],
         onComplete() {
           typedInstance.cursor.remove();
	  }
	});
    </script>
  </body>
</html>
```
this is result gif
![1](https://user-images.githubusercontent.com/47601098/104595058-f3657700-5669-11eb-8b1c-5c8ccdcb0001.gif)
Please tell me how to do it

**Comment by yangzhao28** [comment]
> > You can hide the cursor on complete event:
> > ```
> > <body>
> >   <div id="root">
> >     <span class="typed" id="typed"></span>
> >   </div>
> >   <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.5/typed.min.js"></script>
> >   <script>
> >     const typedInstance = new Typed(document.getElementById('typed'), {
> >       typeSpeed: 60,
> >       showCursor: true,
> >       strings: ['Are you OK?'],
> >       onComplete() {
> >         typedInstance.cursor.remove();
> >       }
> >     })
> >   </script>
> > </body>
> > ```
> 
> it's not working , the cursor not hide After The Writing Is Finished and the code not to the next line
> this's is my code
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="UTF-8">
>     <title>Title</title>
>     <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
>   </head>
>   <body>
>     <span id="typed6"></span>
>     <script>
> 	var typed6 = new Typed('#typed6', {
> 	  typeSpeed: 60,
> 	  showCursor: true,
> 	  strings: ['npm install^1000\n `installing components...` ^1000\n `Fetching from source...`'],
>          onComplete() {
>            typedInstance.cursor.remove();
> 	  }
> 	});
>     </script>
>   </body>
> </html>
> ```
> 
> this is result gif
> ![1](https://user-images.githubusercontent.com/47601098/104595058-f3657700-5669-11eb-8b1c-5c8ccdcb0001.gif)
> Please tell me how to do it

Try to change your onComplete function to:
```
onComplete(instance) {
  instance.cursor.remove();
}
```
