### ISSUE TITLE
How can I use diferent font-sizes?

### ISSUE THREAD

**Issue by eversonapp** [mattboldt/typed.js#465]
I want to put different sizes on the same sentences through CSS . I made a span inside of the the p and changed the font-size of the span, but it's not working. I can have two colors but not 2 sizes.

Example

<font-size='14px'>Everson</font-size='14px'>
<font-size='28px'>Web Developer</font-size='28px'>

**Comment by demiavaliani** [comment]
<font-size></font-size> is not a valid HTML tag. If you want to specify a CSS property straight from HTML tags, it's called inline style. 

**Do something like this in your HTML:**

```
<div id="typed-string-50px">
    <span>50px text!</span>
  </div>
  <span id="typed-50px" style="font-size: 50px;"></span>
</div>

<div id="typed-string-100px">
    <span>100px text!</span>
  </div>
  <span id="typed-100px" style="font-size: 100px;"></span>
</div>
```

**And create 2 separate functions for each element like this:**

```
var typed50px = new Typed('#typed-50px', {
      stringsElement: '#typed-string-50px'
    });
```
```
var typed100px = new Typed('#typed-100px', {
      stringsElement: '#typed-string-100px'
    });
```
It works perfectly for me like this.

**Comment by eversonapp** [comment]
Yeah I created one function for each element. Works like a charm.

ty.
