### ISSUE TITLE
The cursor position is not correct when typing block element

### ISSUE THREAD

**Issue by zhanyuzhang** [mattboldt/typed.js#466]
For example: 
```
<body>
  <div id="root"></div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.5/typed.min.js"></script>
  <script>
    new Typed(document.getElementById('root'), {
      typeSpeed: 60,
      strings: ['<p>Are you OK?</p>', '<p>Yes, I\'m fine.</p>', '<p>Me too!</p>']
    })
  </script>
</body>
```

So, If I want to render multiple block element , how can I set the cursor position follow the last string instead of on the next line.

**Comment by mattboldt** [comment]
The only CSS applied to `typed-cursor` by default is the blinking animation. If you need it to display differently, you could either position it absolutely, or add a class to your `<p>` tags that makes `display: inline-block;`
