### ISSUE TITLE
Something wrong with the code?

### ISSUE THREAD

**Issue by ethxrnity** [mattboldt/typed.js#467]
### Description

Hi, for some reasons i can see the typed effect in demo (https://jsfiddle.net/8Lfw1rn0/) but i cannot see the typed effect on my website (http://demo.ethxrnity.website/pihodatomas) nor on a disk. I'll be really glad if someone help me there, im really going crazy with this.

### Demo
https://jsfiddle.net/8Lfw1rn0/ + http://demo.ethxrnity.website/pihodatomas [SSL Website (https://demo.ethxrnity.codes/pihodatomas)]

**Comment by mattboldt** [comment]
![image](https://user-images.githubusercontent.com/1389818/105560727-47133880-5cda-11eb-8992-dc37b3dceff9.png)

looks like you're trying to initialize `Typed` before the script is loaded. Try moving the `<script src="http:///....` above it.
