### ISSUE TITLE
Emoji preloading (unicode issue)

### ISSUE THREAD

**Issue by IIPoliII** [mattboldt/typed.js#468]
Hey,

I have an issue when I try to load emojis it first shows a character like ? and then shows the Emoji. 

https://jsfiddle.net/IIPoliII/ws0mryex/2/

here is an example.

Note that if I set the backSpeed and the typeSpeed at 0 the issue won't show up.

I think it's due to the fact that emojis are using multiple characters.
Is is possible to fix that by detecting if it's an emoji and writing it faster when it's the case (considering it as only one character)

Thanks for your help.

**Comment by mattboldt** [comment]
Ideally emojis would work the same as html characters. If you have `&times;` in your strings, it won't print that, it will scan from `&` to `;` and then render the character. This would require additional logic to detect.

**Comment by IIPoliII** [comment]
Awesome this worked thanks.
