### ISSUE TITLE
Text artifacts appear after backspace

### ISSUE THREAD

**Issue by istirton** [mattboldt/typed.js#478]
### Description

I'm getting little text artifacts left behind after the item backspaces. It's only occurring on safari mobile devices.

### Demo
https://www.whiskeyvest.co/

### Steps to Reproduce

1. Go to safari, type in command shift r to open responsive development mode.
2. Watch home screen animation

Can anyone identify the source of this?

https://uploads-ssl.webflow.com/6065e05a8c291da8866f548f/60777651fa8ba97879895374_Screen%20Shot%202021-04-14%20at%207.07.50%20PM.png

**Comment by AureGr** [comment]
Hi! I met this problem too, and found that backspacing is truly deleting the content. That means that during a few millisecond after the backspace animation end there is no content taking vertical space anymore. So all content/components/divs just set below your animation and below each-other are moving up to take the new empty space for a very short time then come back to normal when next string start being typed. You can see that the problem does not appear when "smartBackspace: true" and you have a consecutive string starting with at least the same letter (like: "Be happy", "Be angry", "Be proud"), as so the "artifact bug" will maybe occur after backspacing the last string, when animals start new loop.

I just fixed that by setting a fixed height value to my div being animated, a "min-height" close or same than "font-size". Maybe having each content placed fix, not relative to each other, should work but that's a bit too much.
