### ISSUE TITLE
Could you (Matt) host this script on cdnjs.com?

### ISSUE THREAD

**Issue by GGJesus** [mattboldt/typed.js#49]
It'd be nice because I'm trying to build a Watch_Dogs-esk website and I wish to use the entire website with only one .html file. I'm pulling my fonts and also a jQuery library from Google but your code isn't hosted anywhere else publicly. I believe that http://cdnjs.com/ would be a good choice because it's also backed by CloudFlare and has some nice features (like automatic pulling of updates from a github repository). I'll stop now, before I sound like a advertisement but could you please upload it there? D:

Thanks in advance (if you can),
Francois.

**Comment by mattboldt** [comment]
looks like it's hosted there now! Hopefully it'll pull the most recent updates.
