### ISSUE TITLE
Is it possible (or viable to implement) to treat a group of characters as just one character?

### ISSUE THREAD

**Issue by crammag** [mattboldt/typed.js#495]
### Description

When working with emojis, you can see the multiple characters it is composed by, and it looks a bit weird, and some of the characters only render as the typical "character not found symbol".

### Demo

[Demo with emojis](https://jsfiddle.net/5f9b40eq/6/)

### Steps to Reproduce

1. Add typed.js library
2. Configure strings to contain emojis
3. Watch with horror what happens xD.

**Expected behavior:** I expect to see only the final emoji rendered on the screen.

**Actual behavior:** Each of the characters that compose the emoji are shown and finally you can see the result of the composition of the multiple characters into the final emoji, with some "character not found symbol" in between.

**Reproduces how often:** 100%

### Additional Information

**I understand that this is not exactly a problem with the library itself,** but I'm wondering if there is some way to indicate that the emoji is a group of characters that should be treated as only one when typing your strings (similar as when you add a pause "^1000" of one second for example) or if it would be viable (and acceptable as a feature for the library) to implement.

**Comment by crammag** [comment]
Checking the source code I've seen there is an option to "type now" an string adding these quotes -> `

I'm adding another JSFiddle where we can see the difference:
[Demo with emojis and type now feature](https://jsfiddle.net/5f9b40eq/12/)

But now there is another problem, on backspace it is not working and it shows the secuence of characters again, is that the expected behaviour?

**Comment by crammag** [comment]
In case is something that can't be done or is too time consuming or inappropriate for the library don't worry, I "solved" it with a backSpeed of 0, but maybe "the correct" behaviour could be added as a new flag like **bulkWriteOnBackSpace** or something like that.

Let me know if something like this could make sense for the library and I could try to implement it :)

**Comment by mattboldt** [comment]
I was able to get emoji mostly working by using their unicode value instead of the emoji characters themselves: https://jsfiddle.net/mattboldt/vL6uja0p/

Values found here: https://unicode.org/emoji/charts/full-emoji-list.html

But, as you can see, emoji with variations added (like the heart on fire) don't type correctly because it's trying to type/backspace one character at a time.

**Comment by mattboldt** [comment]
Oh and yes, it would be great to specify typing & backspacing one word (or one chunk of characters) all at once v.s. character by character. It's just not something I've gotten around to implementing.

**Comment by crammag** [comment]
I'm a bit confused now :/, I was supposing the feature of bulk typing was meant to be that or at least, from my point of view, it allows to do that. I think there should only be also considered when backspacing, similar to this (from https://github.com/mattboldt/typed.js/blob/master/src/typed.js#L152):

```javascript
// check for skip characters formatted as
// "this is a `string to print NOW` ..."
if (substr.charAt(0) === '`') {
  while (curString.substr(curStrPos + numChars).charAt(0) !== '`') {
    numChars++;
    if (curStrPos + numChars > curString.length) break;
  }
  // strip out the escape characters and append all the string in between
  const stringBeforeSkip = curString.substring(0, curStrPos);
  const stringSkipped = curString.substring(
    stringBeforeSkip.length + 1,
    curStrPos + numChars
  );
  const stringAfterSkip = curString.substring(curStrPos + numChars + 1);
  curString = stringBeforeSkip + stringSkipped + stringAfterSkip;
  numChars--;
}`

And if it's not meant to be the default behavior, maybe we could add a flag to perform this same logic when backspacing.

**Comment by crammag** [comment]
I have created a PR with what I think is a good solution, so maybe we can work from there in case you think is a viable implementation, thanks!

**Comment by crammag** [comment]
stale = false;

**Comment by mattboldt** [comment]
gonna close this in favor of your PR #496
