### ISSUE TITLE
[request]

### ISSUE THREAD

**Issue by kasperfish** [mattboldt/typed.js#5]
would like to have more options and methods:

1)destroy,pause,play, next,prev methods
2)using data attributes to set the text strings
3)load strings from json file (ajax)
4)more callback options: onbefore, onnextstring,...

**Comment by tynielsen** [comment]
@mattboldt You mentioned in a previous comment: "If you want you could fade out the 1st one in the callback function and initiate another with new strings." I am trying to do exactly this but not having anything luck. Could you possibly show me an example of how I could accomplish this? Fade Out the 1st string/current string, then give it a new string/set of strings. And then continue to fade out the current string and set a new string/set of strings.  I appreciate it!
