### ISSUE TITLE
CDN deliver broken!

### ISSUE THREAD

**Issue by hsanshine** [mattboldt/typed.js#504]
### Description
CDN delivery might be broken.

[Description of the issue]
Used to CDN to load the min.js files but got 404 error in browser.

### Demo
[If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/]

### Steps to Reproduce
Add CDN in script tag on your html page.
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>

**Expected behavior:** [What you expect to happen]
Should have loaded the js files or the cached version from the browser.

**Actual behavior:** [What actually happens]
Return 404 error.
![js-error](https://user-images.githubusercontent.com/46571439/169483408-3d225d25-dc3a-4bf4-a8ef-c3c20c75e70f.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%.
![js-error](https://user-images.githubusercontent.com/46571439/169483256-163ab096-fe4f-4cfc-8c8e-4fd452b369c5.png)

**Comment by jimaek** [comment]
That is normal behavior. map files are loaded only when you open the dev tools and in this case it doesnt work because a short URL is used. They are not needed for production use and are only useful during development.
