### ISSUE TITLE
Jittery Typing Animation 

### ISSUE THREAD

**Issue by Sed9yDataBank** [mattboldt/typed.js#505]
### Description

Typing speed randomly became jittery out of nowhere 

### Demo
[If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/]

https://user-images.githubusercontent.com/58634448/170551327-6660615c-26e3-4f3e-8f06-9b92398797db.mov

### Steps to Reproduce

1. `yarn add typed.js` in `Next.js v12.1.6` & `React v17.0.2` & `TypeScript v4.6.4`
2. 
```typescript

  useEffect(() => {
    const typed = new Typed("#typed", {
      strings: HEADLINE_DATA.map(({ text }) => text),
      startDelay: 100,
      typeSpeed: 100,
      backSpeed: 100,
      backDelay: 300,
      smartBackspace: true,
      loop: true,
      showCursor: false,
      onStringTyped: (index) => {
        .
        .
        .
      },
    });
    .
    .
    .
    <span className="break-normal" id="typed"></span>
```
3. As I said this  started happening out of nowhere, it used to work as normal

**Expected behavior:** Smooth typing animation

**Actual behavior:** Jittery typing Animation

**Reproduces how often:** Two weeks ago nothing unusual, starting this week everyone reported that the animation is jittery 

### Additional Information

All I have is the demo video above.

**Comment by xididri** [comment]
same issue when starting the animation manually (`start()`) after it was paused (stopped). works most of the time but sometimes 2 sentences are being typed simultaneously resulting in jittery animation.
