### ISSUE TITLE
use emojis

### ISSUE THREAD

**Issue by GermanYoshi** [mattboldt/typed.js#506]
when using emojis like "&#128013" they are displayed very weird

**Comment by shaunroselt** [comment]
Same for me. Emojis doesn't work well. I'm trying to use 😏

**Comment by shaunroselt** [comment]
@stale (bot)
![image](https://user-images.githubusercontent.com/5418178/188594942-6353b71b-7c52-43cd-8c99-e657231a8782.png)

How/Where is this completed?

I'm using the latest v2.0.12 and it's not completed there.
