### ISSUE TITLE
Accessibility issue with display:none for static html strings

### ISSUE THREAD

**Issue by audunmb** [mattboldt/typed.js#508]
### Description

Using static html strings as described [here](https://github.com/mattboldt/typed.js#strings-from-static-html-seo-friendly) adds display:none to the div where the strings are collected. 

As far as I know, this will hide the text from screen readers. The animated text is obviously difficult to read for people with sight issues, but screen readers doesn't necessarily turn off javascript. If it really is SEO-friendly is also up for discussion, as hidden text may be ignored by crawlers. It also hides the text in Reader mode and from print, which may be an issue.

A more accessibility friendly solution would be good, though that probably means you have to add som custom CSS. 

This seems to be the best solution for hiding content in an accessible way :

`.element-invisible {
  position: absolute !important;
  height: 1px; width: 1px; 
  overflow: hidden;
  clip: rect(1px 1px 1px 1px); /* IE6, IE7 */
  clip: rect(1px, 1px, 1px, 1px);
}`

(from [this guide](https://snook.ca/archives/html_and_css/hiding-content-for-accessibility))

**Comment by mattboldt** [comment]
Thanks for opening this, and sorry it hasn't been fixed yet. I'll get it fixed on the `main` branch where I have a new build process set up

**Comment by mattboldt** [comment]
This should be fixed on the latest release! Now, the "typed strings" div get the CSS you mentioned here to hide them without using display:none
