### ISSUE TITLE
ESM build and add exports field to package.json

### ISSUE THREAD

**Issue by CxRes** [mattboldt/typed.js#509]
### Description

Please provide an ESM version. At the very least add `src/typed.js` to an exports field.

### Additional Information

With only CJS files, project bundlers cannot see opportunities for tree-shaking.

**Comment by CxRes** [comment]
Go away bot! Just because the author is not around, you should not be closing the issue!

**Comment by CxRes** [comment]
Stale Bot! You are evil!

**Comment by mattboldt** [comment]
Working on getting the build fixed. All the dependencies are old and config files are deprecated, so I'm trying to switch to rollup or vite or something to get all the build targets.

**Comment by mattboldt** [comment]
Could you try out the `main` branch and see if the exports look right? This commit includes builds via rollup https://github.com/mattboldt/typed.js/commit/c2c6d77d00bde39500095467239ef024d546d6a7
