### ISSUE TITLE
Documentation: vue-typed-js obsolete / a jsfiddle would make things easier than a library on top of typed.js

### ISSUE THREAD

**Issue by maieulChevalier** [mattboldt/typed.js#510]
### Description

vue-typed-js hasn't been updated since 2019 and vue is now in version 3 since january 2022.

### Solution

Using the composition api, the code is pretty simple:

```vue
<script setup>
import { ref, onMounted } from "vue";
import Typed from "typed.js";

const options = {
  strings: [
    "Hello",
    "World !"
  ]
};

const welcomeMessage = ref(null);

onMounted(() => {
  const typed = new Typed(welcomeMessage.value, options);
});
</script>

<template>
  <p><span ref="welcomeMessage"></span></p>
</template>
```

### Additional information
I'm pretty new to vue.js and I had a hard time figuring this out but the code actually seems quite simple. I think it would be nice to create a jsfiddle (although I'm not sure vue v3 can be used on it) and serve it as a demo. At least, a git repo showing users how to do it would be nice. What do you think?

**Comment by mattboldt** [comment]
Do you know how to get the composition API working in a jsfiddle demo? I wasn't able to
