### ISSUE TITLE
Smart backspace not working with last string in a loop

### ISSUE THREAD

**Issue by joulev** [mattboldt/typed.js#512]
### Description

When `loop: true` and `smartBackspace: true`, after the final string has been typed, smart backspace doesn't work when backspacing to type the first string (again, in a loop).

### Demo

https://codepen.io/joulev/pen/OJjjGjX

### Steps to Reproduce

1. Use `loop: true` (`smartBackspace` is `true` by default).
2. Use some strings such that the last and the first one has a common prefix (in the Codepen, it is `Hello world `)

**Expected behavior:** `Hello world ` shouldn't be retyped when going from the third string to the first (in the Codepen).

**Actual behavior:** Smart backspace simply doesn't work at all.

**Reproduces how often:** If I follow the above steps correctly I'm confident I'll get the bug 100% of the time.

### Additional Information

N/A

**Comment by GramThanos** [comment]
This bug still exists.

**Comment by selim13** [comment]
Have this problem too

**Comment by ConduciveMammal** [comment]
@mattboldt This issue seems quite old, but is still present in the current build Is Typed.js still maintained?
