### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'tagName')

### ISSUE THREAD

**Issue by stasiekkk** [mattboldt/typed.js#513]
### Description

Normally trying to use typed.js

### Demo
[If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/]

### Steps to Reproduce

1.             var typed = new Typed("#test", {
                     stringsElement: '#test-strings',
                     typeSpeed: 0,
                     backSpeed: 0,
                     backDelay: 500,
                     startDelay: 1000
                });
2. Load site
3. Error

**Expected behavior:** Work

**Actual behavior:** Getting error

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by water-bai** [comment]
Have you found the cause of this problem and how did you solve it

**Comment by waiz3ple** [comment]
The typing speed is too fast. it needs to look human.

**Comment by TaylorDurden** [comment]
@stasiekkk Have you resolved this issue? If so, please tell me. Thanks!

**Comment by TaylorDurden** [comment]
> Have you found the cause of this problem and how did you solve it

The issue is that the typed element was not used in html.
