### ISSUE TITLE
MS Edge "efficiency mode" ruins animation

### ISSUE THREAD

**Issue by alex-jitbit** [mattboldt/typed.js#517]
### Animation stops working with MS Edge "Efficiency mode" enabled

Enabling "battery saver" on a Windows laptop automatically enables MS Edge efficiency mode. That. in turn, ruins the animation (I think it is limiting `setTimeout` minimum delay

### Steps to Reproduce

1. Enable "battery saver" mode on ANY Windows laptop. Or - enable efficiency mode in MS Edge (Menu - Settings - System and performance - Turn on efficiency mode dropdown)
2. Open your demo page

**Comment by mattboldt** [comment]
Huh, strange. I don't have a windows machine to test on, so this may be tricky to reproduce, but I wonder if I could resolve it by using `window.requestanimationframe` instead of `settimeout`
