### ISSUE TITLE
How can I wrap a typed string?

### ISSUE THREAD

**Issue by amissine** [mattboldt/typed.js#523]
### Description

First of all, tons of thanks for the great work! Just started using  it today, https://shex.pages.dev/shex-join - works like charm for a short string. Was unable to wrap a longer string though. Would appreciate any help.

And thanks again!

Дід Alik

**Comment by mattboldt** [comment]
I'm not sure what you mean by "wrap a longer string" -- could you include an example of what's going wrong?

**Comment by mattboldt** [comment]
Closing until I get more info

**Comment by amissine** [comment]
When a long string is being typed, it doesn’t get wrapped to the next line. So I thought it would be nice to have a mode when it does. Thanks again. 


Sent from Yahoo Mail for iPhone


On Saturday, December 10, 2022, 4:04 PM, Matt Boldt ***@***.***> wrote:




I'm not sure what you mean by "wrap a longer string" -- could you include an example of what's going wrong?
