### ISSUE TITLE
typed.js not working 

### ISSUE THREAD

**Issue by NoobPlayZ8991** [mattboldt/typed.js#527]
![Screenshot_2022-12-21-13-43-03-229_com rhmsoft edit](https://user-images.githubusercontent.com/100742385/208848599-bef80ecb-d8ac-492a-a66a-96b150db38ac.jpg)
I tried everything, even from other issues but it's not working

Code(GitHub getting glitched if I upload it in text so I had to zip it):
[code.zip](https://github.com/mattboldt/typed.js/files/10275609/code.zip)

**Comment by mattboldt** [comment]
Looks like you're trying to use `import` directly in the browser, not inside of an ES module. If you're loading the code via `<script>` tag, you don't need to `import` it, it should just be available globally.
