### ISSUE TITLE
Entities are not recognized until complete sequence is typed (ex. &amp; or &nbsp;)

### ISSUE THREAD

**Issue by ghost** [mattboldt/typed.js#53]
Try using the string "Non-breaking&nbsp;Space" - it will show "& n b s p" then change ito a non-breaking space.

**Comment by chodorowicz** [comment]
same problem here

**Comment by cauerego** [comment]
This is still a problem, at very least, in my usage case:

`<span>bar&nbsp;<strong>foo</strong> zoo^2000</span>`

If I use it without `$nbsp;` it works fine.
