### ISSUE TITLE
Can't able to update strings array from browser console.

### ISSUE THREAD

**Issue by Irshad4711** [mattboldt/typed.js#533]
### Description

I have a site where typed.js is already been implemented as shown below.

`var options = {
  strings: ["Restaurants near me","Resturants with Wifi", "FAQs","What if my guests have deitary restrictions?"],
  showCursor: true,
  cursorChar: "|",
  typeSpeed: 45,
  backSpeed: 20,
  smartBackspace: true,
  loop: true,
  startDelay: 500,
  backDelay: 2000,
  attr: "placeholder",
};
var typed = new Typed(".js-yext-query", options);`

Now I want to add a new string at the beginning. Is there any way to do it via browser console.

New strings: [**"Enter you City and State or ZIP Code"**,"Restaurants near me","Resturants with Wifi", "FAQs","What if my guests have deitary restrictions?"]

### Demo
Kindly refer the following link https://jsfiddle.net/Irshad4711/wqrx2n9y/1/

### Steps Tired
1. tried to stop in console, it doesn't work. It shows default content and then when I remove It been again loading the same.
[Show default content.webm](https://user-images.githubusercontent.com/122806078/212874117-04bfb4d3-0701-451e-a732-a8cd680b8a7b.webm)

2. when I tried to destroy, it gives me "not defined" error.
![image](https://user-images.githubusercontent.com/122806078/212873707-3c58f7f3-b170-439b-a738-493ce9f77631.png)

**Comment by Irshad4711** [comment]
Can any one suggest any solution on it please.

**Comment by vishalkumar2806** [comment]
you got any solution

**Comment by mattboldt** [comment]
I'm not sure what your use-case is here. I see in the console you're initializing a new instance of `Typed`, which will not affect the current one on the page. To change the existing one, you'd need to be able to access it via a variable.

The only way this will work from the console is if the original instance is set to a variable at the global `window` level, e.g.

```js
// create first instance
window.myTypedJsInstance = new Typed(".el", {})

// later, in the console
window.myTypedJsInstance // should be able to add things to this instance
```
