### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by tabish-amiri** [mattboldt/typed.js#534]
It gives an error in the console that could not load content for https//........
And 404 error .

**Comment by mattboldt** [comment]
Can't reproduce locally, please include an example

**Comment by christianeaton** [comment]
The final line of the CDN version ([https://cdn.jsdelivr.net/npm/typed.js@2.0.12](https://cdn.jsdelivr.net/npm/typed.js@2.0.12)) is:

//# sourceMappingURL=typed.min.js.map

But there is no [https://cdn.jsdelivr.net/npm/typed.min.js.map](https://cdn.jsdelivr.net/npm/typed.min.js.map), so you get a 404 in dev tools when using the CDN as it tries to reconstruct the source map.

**Comment by mattboldt** [comment]
Give this a try with a different CDN; I've updated the readme to use unpkg
```
<script src="https://unpkg.com/typed.js@2.0.132/dist/typed.umd.js"></script>
```

**Comment by tabish-amiri** [comment]
Thank you for your response !
I appreciate your help. 😊
