### ISSUE TITLE
[HELP] With multiple instances of typed.js

### ISSUE THREAD

**Issue by vishalkumar2806** [mattboldt/typed.js#535]
Suppose I have two div both are in one after other in coloumn
I will write two strings like in div1,
Hey hello
How is your day going...

Now i want to start typing in div2 after finishing of div1 but dont know
What your job today?
--------------------------Alternative approach------------------------
Suppose We cant have two elements but if we have one element
then I want to remove the previous lines before new lines
like this 
strings = ['hey hello^1000(wait for 1 sec)\nHow is your day going on?^2000(wait for 2 sec)\n^( ?? : <- some function like ^b or ^del which will backspace all char)Whats your job today?']
I would recommend you to please use array than strings like this its very hard to manage... so that we can also modify string in live mode. Please have a look at immer library which we use in redux toolkit

**Comment by mattboldt** [comment]
You could use the `onComplete` callback to listen for when div1 is done, and then start another animation on div2
