### ISSUE TITLE
About typescript type definition

### ISSUE THREAD

**Issue by Alfred-Skyblue** [mattboldt/typed.js#537]
### Description

I found that the type definition for TypedOptions was removed in the latest commit, but I need to use it and I wonder why it was removed.

**Comment by mattboldt** [comment]
Sorry about that, I'm not sure how that got deleted. Should be fixed with the latest release!

**Comment by omermecitoglu** [comment]
`Could not find a declaration file for module 'typed.js'. '.../node_modules/typed.js/dist/typed.module.js' implicitly has an 'any' type.`

`There are types at '.../node_modules/typed.js/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'typed.js' library may need to update its package.json or typings.ts(7016)`

**Comment by TaylorFacen** [comment]
Hi, I'm running into the issue above as well.

**Comment by mattboldt** [comment]
reopening to investigate this one.

**Comment by TaylorFacen** [comment]
@mattboldt i believe this PR fixes the problem: #589

**Comment by mattboldt** [comment]
@TaylorFacen thank you, just merged. Could you install the package from main and confirm it's working? Then I'll push a new version tag & release to npm

**Comment by TaylorFacen** [comment]
<img width="226" alt="CleanShot 2023-10-16 at 10 42 37@2x" src="https://github.com/mattboldt/typed.js/assets/44216029/4f41a367-6270-4e91-8866-16fb51325233">

It works! The error message is gone and the `Typed` object has the right typescript type.

**Comment by simbo** [comment]
@mattboldt Anything still missing for releasing this to npm? 😬

**Comment by mattboldt** [comment]
Nope, I just need to push a release. Sorry, haven't had a moment to work on this.

**Comment by mattboldt** [comment]
fixed in latest version v2.1.0!
