### ISSUE TITLE
The typespeed and backspeed slows down after every loop in a loop condition 

### ISSUE THREAD

**Issue by sahilljangra** [mattboldt/typed.js#539]
**Expected behavior:** [What you expect to happen]
The type speed and back speed should remain same at all the time

**Actual behavior:** [What actually happens]
The type speed and back speed starts as the set speed but then keeps declining while working in a loop.

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by mattboldt** [comment]
Please provide a demo
