### ISSUE TITLE
Problems using requirejs

### ISSUE THREAD

**Issue by jorgelainfiesta** [mattboldt/typed.js#54]
Hi,

I noticed there is a problem with the plugin when you're using require.js because the wrapper function tries to access a jQuery instance from the window (which does not exist in this case). I think it'd be better to keep it AMD compatible. I fixed the issue by changing the wrapper function, a simple thing.

Thanks,
Jorge L

**Comment by mattboldt** [comment]
Does this keep it compatible with non-requirejs apps? If so I'd love to see a pull request.
