### ISSUE TITLE
It writes className as classname

### ISSUE THREAD

**Issue by Chibuife** [mattboldt/typed.js#540]
const el = useRef(null);

  useEffect(() => {
    const typed = new Typed(el.current, {
      strings: ['Welcome to my Portifolio', `I develop user interfaces <br className='sm: block hidden' /> and web applications with React. I use FireBase to develop my back-ends.  I am currently learning express js.<br className='sm: block hidden' /> Am ready to migrate to any framework for development.Looking some some who can build and provide solution for your client site? <a href='#contact' className='mt-5'>DROP A MESSAGE</a>`],
      typeSpeed: 50,
    });

    return () => {
      // Destroy Typed instance during cleanup to stop animation
      typed.destroy();
    };
  }, []);

            <span ref={el} />

it skipped my classes

**Comment by mattboldt** [comment]
since the html in the strings aren't jsx, they're inserted as plain html, you'll need to use `class` instead.

**Comment by Chibuife** [comment]
Thanks a lot for your help
