### ISSUE TITLE
还未实现动态新增文本么？

### ISSUE THREAD

**Issue by five6seven** [mattboldt/typed.js#542]
### Description
我想通过在流式处理中不断的往div里加数据，可是这个js只能覆盖之间的重新打字，请问有什么api可以实现吗？
[Description of the issue]

### Demo
[If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Armito** [comment]
same question 同问
