### ISSUE TITLE
Request!

### ISSUE THREAD

**Issue by ChheavBunHeng** [mattboldt/typed.js#544]
### Description

[want to display the text from user instead]

### Demo
[If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/]

### Steps to Reproduce

1. [After display the animation there will be a input number or values in the box ]
2. [After it will display the typing animation of the text that use input]

**Comment by Chibuife** [comment]
For React something like this: 
import React, { useEffect } from 'react'
  useEffect(() => {
    const typed = new Typed(el.current, {
      strings: [`<div>If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/</div>, <div>After display the animation there will be a input number or values in the box </div>,<input value={'After it will display the typing animation of the text that use input'}/>,`]
      typeSpeed: 50,
      showCursor: false
    });
    return () => {
      typed.destroy();
    };
  }, [type]);

Haven't tested it😏

**Comment by Chibuife** [comment]
<div id="typed-strings">
 <div>If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/</div> <div>After display the animation there will be a input number or values in the box </div><input value={'After it will display the typing animation of the text that use input'}/>
<span id="typed"></span>

<script>
  var typed = new Typed('#typed', {
    stringsElement: '#typed-strings'
  });'
</script>

Haven't tested it too😏. I think it is self-explanatory. It read js classes and ES6 module to understand it more. I really don't what to take this to my editor 🤣🤣.

**Comment by Chibuife** [comment]
<span id="element"></span>
  <script src="https://unpkg.com/typed.js@2.0.15/dist/typed.umd.js"></script>  
<script>
    var typed = new Typed('#element', {
      strings:  [<div>If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/</div>, <div>After display the animation there will be a input number or values in the box </div>,<input value={'After it will display the typing animation of the text that use input'}/>],
      typeSpeed: 50,
    });
  </script>

Haven't tested it too😏 but i really really don't what to take this to my editor. check out JS classes u will understand how it works more. And possible ES6 modules.

**Comment by Chibuife** [comment]
<script src="https://unpkg.com/typed.js@2.0.15/dist/typed.umd.js"></script>
 

 
  <span id="element"></span>

  
  <script src="https://unpkg.com/typed.js@2.0.15/dist/typed.umd.js"></script>

  
  <script>
    var typed = new Typed('#element', {
      strings: [<div>If possible, include a demo of your issue in a fork of this JSFiddle: 
        https://jsfiddle.net/mattboldt/1xs3LLmL/</div>, <div>After display the animation there will be a input number or 
        values in the box </div>,<input value={'After it will display the typing animation of the text that use input'}/>],
      typeSpeed: 50,
    });
  </script>
</body>


Haven't tested it too😏. Check out JS classes to understand how it works and ES6 modules

**Comment by mattboldt** [comment]
have a look at this fiddle https://jsfiddle.net/mattboldt/8ozj6tcs/

**Comment by ChheavBunHeng** [comment]
Thanks for answer the request!
