### ISSUE TITLE
`preStringTyped` is not called if string begins with HTML tag

### ISSUE THREAD

**Issue by steponas** [mattboldt/typed.js#546]
### Description

`preStringTyped` is not called when the strings start with HTML tags.

### Demo

Demo with counts (expected and actual): https://jsfiddle.net/s8rdLnmt/

### Additional Information

This occurs because the HTML tags are "skipped" when rendering but the curIndex is increased, and the "start index" of the render string is > 0. Yet https://github.com/mattboldt/typed.js/blob/main/src/typed.js#L200 expects the index to be 0 to call `preStringTyped` - thus it does not work.

**Comment by TooTallNate** [comment]
I am running in to this as well. Is there a fix / workaround?
