### ISSUE TITLE
Issue : Refused to execute script

### ISSUE THREAD

**Issue by maximeMBP** [mattboldt/typed.js#547]
### Description

Hello, the title on this page was using typedjs for a while without any issues but it stopped very recently.

it should be typing a string of caracters after the cibfinance title.

![image](https://github.com/mattboldt/typed.js/assets/135132072/f79b7d9f-8b1d-4413-a000-ab9866711ad6)

I have this error in the console but can't find my way around :

Refused to execute script from 'https://cdn.jsdelivr.net/npm/typed.js' because its MIME type ('application/node') is not executable, and strict MIME type checking is enabled.

(index):382 Uncaught ReferenceError: Typed is not defined
    at (index):382:15 

thanks

**Comment by mattboldt** [comment]
I recommend switching to another CDN, like `https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js`
