### ISSUE TITLE
single < or > in strings with contenttype: html crashes browser

### ISSUE THREAD

**Issue by Laosing** [mattboldt/typed.js#55]
Hey I just discovered that when you type a single < or > sign with contentType: 'html' in one of your strings it crashes the browser (makes it freeze and makes your computer go into overdrive like the usual infinite loop bugs do). Not a big deal, just thought it would've been nice if this was stated on the README.md until it gets fixed.

**Comment by mattboldt** [comment]
Ah. Yeah it must be looking for the ending `>` and never does, so it's an infinite loop. Kind of an edge case. I suppose I could stop the loop past a certain amount of times, since HTML tags are never over like 20 chars.

**Comment by saviourofdp** [comment]
it seems to be the case with single ampersands (`&`) too

**Comment by alkrauss48** [comment]
Just ran into this issue too with the ampersand, and I found two ways to get around it:

1. Add the setting `contentType: 'text'` to your typed options so it doesn't try to render as html
2. Do something like:

```javascript
      // Assuming the text you want to type is in the data attribute of a field:
      var text = $(".your_field").data('title').replace('&', 'and');
      $(".subpage h1").typed({
        strings:    [text],
        typeSpeed:  15,
      });

```

**Comment by gbissland** [comment]
Still can't sort the (&) issue, where abouts did you add the above (2). Appreciate the help.

**Comment by CaptainHypertext** [comment]
Why don't you just use html entities?  Instead of &,  use &amp; and instead of <, use &gt;
That worked just fine for me.

**Comment by tuthanh82** [comment]
Add the setting contentType: 'text' works for me.
