### ISSUE TITLE
Text blinking after translation

### ISSUE THREAD

**Issue by AlkoKod** [mattboldt/typed.js#550]
### Description

Hello, I have tried to implement this awesome script on hero section of my company website. It works very nice! However, I am using automatic translation via DeepL API and when I switch the language, the animated text starts to blinking. Can I repair this behavior somehow?

### Demo
It can be seen here: https://www.complianceteam.cz/en/ 

This is my config file: 
![image](https://github.com/mattboldt/typed.js/assets/52713604/78846703-a478-4658-b7f5-82d10c28bcaf)

### Steps to Reproduce
1. Embed script to WordPress theme
2. Make it working
3. Install Translatepress plugin with DeepL integration
4. Open translation

**Expected behavior:** Should work normally like on Czech version https://www.complianceteam.cz/
**Actual behavior:** Text blinking https://www.complianceteam.cz/en/
**Reproduces how often:** 100%

**Comment by mattboldt** [comment]
Since the translation library alters content on the page, including the typed.js content, I'm not really sure how to integrate it and keep control of the typing animation. If you have some kind of hook that fires after the translation finishes, you may be able to reset it like `typed.reset()`
