### ISSUE TITLE
The cursor display is abnormal during use, how to solve it

### ISSUE THREAD

**Issue by better-pz** [mattboldt/typed.js#551]
### Description

The cursor display is abnormal during use, how to solve it,See the demo below for detail 
Hope it helps, thank you very much

### Demo

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Typed.js Example</title>
  <script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>
</head>
<body>

  <div id="typed"></div>

  <script>

      var typed =  new Typed("#typed", {
       strings: ["<ol><li><p>test<b>https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js</b>https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js,801，<span style='color: #00A873;'>https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js%</span>312321<b>321312312</b>https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js；</p></li><li><p>https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js</p></li></ol>"],
        typeSpeed: 30,
        backSpeed: 30,
        backDelay: 1000,
        showCursor: true,
        cursorChar: '|',
        loop: false
      });

  </script>
</body>
</html>
<img width="1292" alt="image" src="https://github.com/mattboldt/typed.js/assets/68367439/9b78f58d-bf3e-439d-a750-4a740d696c16">

**Comment by jaythegeek** [comment]
Give the wrapper a flex class :)
