### ISSUE TITLE
Finish sentences on click?

### ISSUE THREAD

**Issue by IntellectProductions** [mattboldt/typed.js#57]
So say the user doesn't feel like reading through all of it and wants the text to display on click. Kind of like when you play a game, you can press X/A or click to have all the text in the box at once. Is there anything like this implemented? I'm not sure if there is a callback function I can implement or not to have it complete on click.

Thank you!

**Comment by IntellectProductions** [comment]
Nevermind. I reprogrammed a lot of this plugin to fit this in and my other needs :) Thanks! Here is the code that I did: http://pastebin.com/yPbYSqi6 If anybody knows how to fit it into the current structure, great :P

**Comment by mattboldt** [comment]
If you can get this to work with the existing plugin, a pull request would be great!
