### ISSUE TITLE
Version 2.0.132 overrides all newer version

### ISSUE THREAD

**Issue by 2-5** [mattboldt/typed.js#591]
### Description

With `"typed.js": "^2.0.16"` in `package.json` old version `2.0.132` is installed because 132 is bigger than 16.

Version `2.0.132` is here: https://www.npmjs.com/package/typed.js/v/2.0.132

### Steps to Reproduce

Couldn't get a reliable one, some combination of `yarn install typed.js`, deletion of `node_modules` and `yarn.lock` and then reinstalling with `yarn`.

A `^2.1.0` release would prevent such errors.

**Comment by mattboldt** [comment]
thanks for catching this! fixed in the latest release
