### ISSUE TITLE
How can i display back quote ('`')

### ISSUE THREAD

**Issue by liwuyi27** [mattboldt/typed.js#602]
### Description

I can not display back quote ('`')

### Demo
[[If possible, include a demo of your issue in a fork of this JSFiddle: https://jsfiddle.net/mattboldt/1xs3LLmL/]](https://jsfiddle.net/5L7tducs/1/)

### Steps to Reproduce

1. open the demo link and see the result

**Expected behavior:** Dispaly as `` const a = `timestamp-${Date.now()}` ``

**Actual behavior:** Dispaly as ``const a = timestamp-${Date.now()}``

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Nevvees** [comment]
Have you been able to solve this problem?

**Comment by mattboldt** [comment]
You'll have to use the hexadecimal character code `&#96;` instead https://jsfiddle.net/ox4zv0nw/
