### ISSUE TITLE
Problem typing emojis

### ISSUE THREAD

**Issue by isaacbatst** [mattboldt/typed.js#603]
### Description

Emojis are typed code by code so that they are not rendered correctly for a while, showing a "?"

### Demo
https://jsfiddle.net/2oufqe0v/9/

### Steps to Reproduce

1. Use an emoji on typed string
2. Put a speed like 40
3. Se emoji be "?" for an instant

**Expected behavior:**  Emoji be written atomically

**Actual behavior:** Emoji is written code by code

**Reproduces how often:** Always, but it's more noticeable on slower speeds

**Comment by mattboldt** [comment]
You'll have to use the hexadecimal value to get them to display properly: https://jsfiddle.net/dut16zbc/

Table of all emoji hex values: https://www.quackit.com/character_sets/emoji/emoji_v3.0/unicode_emoji_v3.0_characters_all.cfm

**Comment by cph2117** [comment]
The same issue persists for emojis with compound hex characters like flags (e.g. &#x1F1E9; &#x1F1EA;). I tried this approach and rendering the strings themselves as spans (e.g. `'<span class="emoji">Deutsch 🇩🇪</span>'`) and setting contentType to html, but no luck. Is there any way to accomplish this with compound emojis?

**Comment by cph2117** [comment]
My solution is janky, but working. Use `contentType: 'html'` and set the strings in the following format: `<div>Deutsch <img src="" alt="🇩🇪" onerror="this.replaceWith(this.alt);"/></div>`

**Comment by Astro-Simon** [comment]
Hi, I still do not get this working. Could you please show some example of the code that makes it work? Thanks.
