### ISSUE TITLE
Working issue

### ISSUE THREAD

**Issue by Himanshu12866** [mattboldt/typed.js#607]
### Description

Typed.js is not working in my code. Before pushing the code in GitHub its working properly but when I pushed the code in GitHub, it is not working I tried so many times but result remained same.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [Typing Behaviour ]

**Actual behavior:** [Not working]

**Reproduces how often:** [Every time]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by praval-mishra** [comment]
Same problem

**Comment by mattboldt** [comment]
Hello! Please include a demo of the problem you're seeing https://jsfiddle.net/1qeph94u/
