### ISSUE TITLE
Is there a way to skip the anim of the first string, and then start with backspacing?

### ISSUE THREAD

**Issue by highvoltaged** [mattboldt/typed.js#610]
I'd like to skip the first round of typing anim, and already start with the first string fully displayed.
Is it possible?

Thanks

**Comment by mattboldt** [comment]
Yep! The text already in the element will get backspaced. Demo: https://jsfiddle.net/4bt8g9wa/1/

**Comment by highvoltaged** [comment]
Awesome! Thanks very much!
