### ISSUE TITLE
Minimized version?

### ISSUE THREAD

**Issue by BtM909** [mattboldt/typed.js#63]
Is it possible to include a minification in your build process as well?

Thanks :smile:

**Comment by kimolalekan** [comment]
You can use online minify tool to do that. e.g http://marijnhaverbeke.nl/uglifyjs

**Comment by BtM909** [comment]
Yes, I know, but

1. that breaks your script
2. it's better to incorporate in bower and other tools to just import your minified version.

Anyway, I'll figure out a way to get it sorted myself.

Thanks
