### ISSUE TITLE
Help how to hide the cursor when the sentence finishes?

### ISSUE THREAD

**Issue by pedrotheninja** [mattboldt/typed.js#64]

**Comment by lhfaria** [comment]
Same thing here. Any ideas? Thanks.

**Comment by ziazek** [comment]
I got it to hide with this:
```
var elem;

elem = $('.typed');

$('.typed').typed({
  strings: ['some string'],
  contentType: 'text',
  onStringTyped: function() {
    return elem.siblings('.typed-cursor').remove();
  }
});
```

**Comment by Dom-Mc** [comment]
I was looking at the same thing but realized if you're doing multiple things to the string(s), calling `onStringType: function()` may remove the cursor earlier than you may have intended.  Replacing it with `callback: function()` worked perfectly for me.

**Comment by dejwne** [comment]
Your solution doesn't work for me. I used this:
`callback: function() { 
                  $( "span" ).siblings( ".typed-cursor" ).css( "animation", "none" );
                  $( "span" ).siblings( ".typed-cursor" ).css( "opacity", "0" );                    
                } `

**Comment by adonismedia** [comment]
You can do it like this:
`var typed = $('.typed').typed({

callback: function() {          
                           return typed.siblings('.typed-cursor').fadeOut('slow', function({typed.siblings('.typed-cursor').remove()});
                    }

 });`

**Comment by mattboldt** [comment]
you could use the `onComplete` callback

**Comment by darmenise** [comment]
Actually, it's easier without jQuery:

```
onComplete: function(self) {
      return self.cursor.remove();
}
```

**Comment by davlawrence** [comment]
@duarme best solution

**Comment by enangsubang** [comment]
var typed = new Typed('#target', {
	 strings: ["Please Visit","https://esistemindo.com"],
	 typeSpeed: 70,
	 loop: false,
	 onComplete: function(self) { self.cursor.remove() },
});

**Comment by enangsubang** [comment]
var typed = new Typed('#hhh', {
			 strings: ["Teks Pertama","Teks Kedua"],
			 typeSpeed: 70,
			 loop:false,
			 onComplete: function(self) { self.cursor.remove() },
			});
