### ISSUE TITLE
Blinking cursor is on a new line when the typed element is `p` (paragraph)

### ISSUE THREAD

**Issue by daattali** [mattboldt/typed.js#66]
If I'm initializing the plugin on a \<p> element, the blinking cursor is always on a line below the text

`<p id="a"></p>`
`$("#a").typed({ strings : ["test"] });`

**Comment by deepak90** [comment]
I Have this problem too, The '.typed-cursor' seems to appear on the next line.

**Comment by cmarucco** [comment]
I'm having this problem too, regardless of the element.  Tried on <h2> and <div>, Moves down to next line.  Is there a css fix?

**Comment by ChristofferJoergensen** [comment]
I managed to remove the line break by adding

   display: inline;

to the <h2> header that is being animated.

**Comment by renestalder** [comment]
Either set to `display: inline` or `display: inline-block`. The cursor have to follow the text, which is not possible with a block element, since it renders full with by default.

**Comment by tgaeta** [comment]
Tried setting the display to both inline and inline-block as suggested by @renestalder with no luck.

**Comment by renestalder** [comment]
@tgaeta Check that your element has no set width or force set it to `width: auto;`

**Comment by cauerego** [comment]
@renestalder this could actually be fixed in typed.js if instead of making the `.typed-cursor` come after the original element you actually used the CSS `::after` like [allison is doing](http://allison.house/404) (but she had to recreate the cursor, probably because she wanted a custom one):

```
#story:after {
  visibility: visible;
  content: '';
  background-color: #d4f8e3;
  display: inline-block;
  position: relative;
  width: 0.5em;
  height: 1em;
  top: 5px;
  margin-left: 0;
  -moz-box-shadow: -2px 0 0px rgba(0, 0, 225, 0.4), -1px 0 3px rgba(103, 171, 236, 0.6), 1px 0 4px rgba(69, 112, 204, 0.5);
  -webkit-box-shadow: -2px 0 0px rgba(0, 0, 225, 0.4), -1px 0 3px rgba(103, 171, 236, 0.6), 1px 0 4px rgba(69, 112, 204, 0.5);
  box-shadow: -2px 0 0px rgba(0, 0, 225, 0.4), -1px 0 3px rgba(103, 171, 236, 0.6), 1px 0 4px rgba(69, 112, 204, 0.5);
  -moz-animation: flicker 0.1s steps(2, start) infinite, ready 1s steps(2, start) 25s infinite;
  -webkit-animation: flicker 0.1s steps(2, start) infinite, ready 1s steps(2, start) 25s infinite;
  animation: flicker 0.1s steps(2, start) infinite, ready 1s steps(2, start) 25s infinite;
}
```

**Comment by renestalder** [comment]
@cauerego That's what I did in my projects. It's even the better solution because this does not cause unsemantic code.

**Comment by cauerego** [comment]
I don't know what you mean, and I still don't get why this couldn't go inside `typed.js`. :(

But if you say so, at least there it is another reference to whomever might stumble here in the future. ;)

**Comment by daattali** [comment]
@cauerego @renestalder I haven't tried that solution, but I'm assuming you tested it with different element types and different settings, and it doesn't break anything?

If so, why don't one of you contact @mattboldt directly (email?) to ask to fix this or submit a pull request :)

**Comment by cauerego** [comment]
Nah, I haven't tested it at all within typed different settings. Just tried on a few different browsers and devices. I doubt it would give any issues, though. It's a very short and straight forward code, except I know nothing about the animation part, but it's not too different from what's already being suggested on typed's main site anyway.

And since I can use it as it is for myself, it doesn't bother me too much. Not enough to email him, anyway. ;P

**Comment by mattboldt** [comment]
The element being used with Typed has to be `inline-block` for the cursor to sit inline with it. If you want a paragraph, wrap a `<span>` (the typed element) in a `<p>`.

It'd be nice to just have it in a CSS `:after`, though. I may add that soon!

**Comment by renestalder** [comment]
Here is the project where I've used the ::after technique to accomplish this. The other cursor is just set on display: none. So don't bother if you can see it in the DOM.

This works without any problems for our audience. Based on the current browser support of typed.js, you just have to check if a ::after or :after pseudo element will decrease the range of browsers.

http://campaigning.farner.ch/

**Comment by wenweih** [comment]
#100 👏

**Comment by canelasa** [comment]
the element needs to be inside span

**Comment by GTCrais** [comment]
setting element to display inline block doesn't work if text spans into multiple rows. For one-row text it's fine, but as soon as it breaks into the second row, the cursors moves beneath the text. Why can't the cursor span just be put inside the element which the text is being typed in? That would solve everything.

**Comment by Diego-Gnoatto** [comment]
white-space: nowrap;

**Comment by GastonPerez97** [comment]
I had a similar problem, I fixed it by adding a div and then a display: inline-block to the nested element:

HTML: <div><h2 id="a" class="something"></h2></div>
CSS: .something { display: inline-block; }

**Comment by LoneisCode** [comment]
@GastonPerez97  This Worked great for me !
