### ISSUE TITLE
Is it SEO friendly ?

### ISSUE THREAD

**Issue by chiragshah1309** [mattboldt/typed.js#69]
Will the sentence be recognised correctly by google

**Comment by davidavz** [comment]
Good question.
If you use a bot simulator (like http://www.botsimulator.com) the text is not indexed.

**Comment by andypillip** [comment]
A simple library like this should not use an empty HTML tag. With deactivated JS I want my users to still read the text.

So in my opinion the library should take the text or HTML from the element, instead of only injection some?

That would be totally search-engine-friendly.
