### ISSUE TITLE
Typed and CSS Animation performance conflicts

### ISSUE THREAD

**Issue by lmorgan-yozu** [mattboldt/typed.js#70]
We've got a background that uses CSS3 transitions and keyframes to infinitely scroll it, but when we add Typed JS to the page both the Typed animation and the CSS3 animation begin to stutter. There are occasional moments where the effects are smooth, but the majority of the time the animation suffers.

I was hoping someone might have had a similar issue and found a way to overcome it?

Thanks!

**Comment by Saboteur777** [comment]
Have you enabled blinking effect with CSS on cursorChar? If yes, try to disable it, it just solved a similar performance issue here.

**Comment by mattboldt** [comment]
There might just be too much animation going on at one time. I'd try the above.
