### ISSUE TITLE
unable to run twice on same element

### ISSUE THREAD

**Issue by edwilliams** [mattboldt/typed.js#78]
Hi,

Running the follow code only results in one animation:

```
$('p').typed({
    strings: ['first string']
});

$('p').typed({
    strings: ['second string']
});
```

Any ideas?

Cheers

Ed

**Comment by zettam** [comment]
I'm having the same issue.

**Comment by kyptov** [comment]
In https://github.com/mattboldt/typed.js/issues/25 thread there is some solutions.

For example above:

    $('p').typed({
        strings: ['first string']
    });
    
    $('p').typed('reset');
    
    $('p').typed({
        strings: ['second string']
    });

But it throw an error if you are using showCursor: false

Another way is remove typed data from element, after first calling or before second (thx @saviourofdp)
`$('p').removeData('typed');`

**Comment by ethanclevenger91** [comment]
+ 1

Thanks @kyptov for the `removeData('typed')` - great solution.

**Comment by meteormanaged** [comment]
Just ran into this issue myself.  The use case was as follows:

When typed completed (on callback), we run a function that destroys the data in the typed element and replaces it with a logo.  Then, after a timeout, initializes typed anew.  

I was able to subvert it pretty easily with whatever various bugfixes required in dom (cursor being recreated):

https://github.com/mattboldt/typed.js/blob/master/js/typed.js#L393

Swapped out the original code for the following:

```if (!data) {
			  $this.data('typed', (data = new Typed(this, options)));
		  } else {
			  $this.data('typed', (data = new Typed(this, options)));
		  }```

dirty but it worked for getting something out the door.

**Comment by tonystaark** [comment]
@kyptov, however this solution will return double typed-cursors. Anyway to solve it?
