### ISSUE TITLE
Very choppy after html tag

### ISSUE THREAD

**Issue by ekaitzht** [mattboldt/typed.js#88]
Hi all!

I have the next problem, when the typed.js library is typing, everything works except when  it has to type the next span block tag. It then stops for some miliseconds which makes the typing flow very choppy. Is there a way to fix this problem?

```
 <h2>               
                               <span class="spring-green">  first  </span>
                               <span class="hot-magenta"> second </span> 
                               <span class="spring-bud"> third. </span> 
 </h2>
```

Thanks!!!

**Comment by myasseen** [comment]
yeah me too.. is there any solution??
