### ISSUE TITLE
tag version

### ISSUE THREAD

**Issue by dotnetCarpenter** [mattboldt/typed.js#89]
[bower](http://bower.io/) works by using `git tag v1.1.1 -am "your tag message here"`. Where the versioning is compatible with [semver (Semantic Versioning)](http://semver.org/). Currently _typed.js_ does not have any any semver compatible [tags/releases](https://github.com/mattboldt/typed.js/releases).

Please tag _typed.js_ with a proper semver version and `git push origin master --tags` to github.com, so bower can work :+1:

**Comment by dotnetCarpenter** [comment]
Guess I need to fork this project in order to use bower versioning :-1:

**Comment by iDev0urer** [comment]
+1 on this issue. I am trying to use it with [rails assets](http://www.rails-assets.org) and it's not working because it can't figure out a version number. I'll see if I can fix it and put a pull request up

**Comment by iDev0urer** [comment]
@mattboldt It seems as though we just need to do a `git tag` so as to set a Git endpoint. It seems as though the versioning on both your package.json and bower.json files are correct

**Comment by dotnetCarpenter** [comment]
@iDev0urer yeah the real issue is that we can't make a PR to fix this. Would be nice if @mattboldt did a `git tag v1.1.1 -am "version 1.1.1" && git push --tag`

**Comment by rstacruz** [comment]
:+1: Please! Also came across this while trying to use it with rails-assets.

**Comment by dotnetCarpenter** [comment]
@mattboldt is there anything you are unsure of with the [semver](http://semver.org/) version numbers? In short they **MUST** be 3 digit seperated by a dot (.), e.i. `1.1.1` is a semver version number - `1.1` is **not** a semver version number.
bower and other package managers **only** works with semver version numbers.

The only person(s) who can do this in this repository is you and other maintainers who as equal access to this repository (push access).
The commands for correctly tagging a release is: `git tag v1.1.1 -am "version 1.1.1" && git push --tag`

**Comment by mattboldt** [comment]
I'll push this change tonight outside of my work hours :wink:
