### ISSUE TITLE
Vary the typespeed

### ISSUE THREAD

**Issue by edborden** [mattboldt/typed.js#91]
Anyone have any ideas on how to vary the typespeed over the course of typing the content? I want it to feel more like a person is typing it, and it would be cool to be able to have it randomly generate a new typespeed for each word.

**Comment by mattboldt** [comment]
The typing speed per character is already randomized, but if you'd like more customization of this you could try and work with the `preStringTyped` and `onStringTyped` callbacks. I don't feel like this is enough of a feature to add in, so if you'd like to fork and customize then go for it!
