### ISSUE TITLE
preStringTyped callback with passed array of html doesn't fireup

### ISSUE THREAD

**Issue by keebOo** [mattboldt/typed.js#96]
Try this: with array `var items` doesn't call preStringTyped, only with `var items2`

``` javascript
// This don't call preStringTyped  
var items = ["<span>first</span>","<span>second</span>","<span>third</span>"]; 

// This call preStringTyped  
var items2 = ["first","second","third"]; 

$("#element").typed({
                strings: items,
                // typing speed
                typeSpeed: 3,
                // time before typing starts
                startDelay: 5,
                // backspacing speed
                backSpeed: 0,
                // time before backspacing
                backDelay: 500,
                // loop
                loop: false,
                // false = infinite
                loopCount: false,
                // show cursor
                showCursor: false,
                // character for cursor
                cursorChar: "|",
                // attribute to type (null == text)
                attr: null,
                // either html or text
                contentType: 'html',
                // call when done callback function
                callback: function() {},
                // starting callback function before each string
                preStringTyped: function() {
                    console.log("PRE");
                },
                //callback for every typed string
                onStringTyped: function() {
                    console.log("POST");
                },
                // callback for reset
                resetCallback: function() {}
            });
```

I try also mixing, and if you try `var items = ["<span>first</span>","second","<span>third</span>"];` you'll see 'PRE' on console one time.

**Comment by keebOo** [comment]
probably the bug is about the counting chars (currentPos) around lines 210: if is an html sentence, doesn't reach zero.... so probably need counting chars of open tag, if present at the start of sentence.

```javascript
/* call before functions if applicable */
                        if (curStrPos === 0)
                            self.options.preStringTyped(self.arrayPos);
```

**Comment by root91** [comment]
I found a solution that works for me. Simply changed keepTyping function to this: 
`function keepTyping(curString, curStrPos, numChars) {
	      var firstChar = curString.charAt(0);
	      var tmpStrPos = 0;

	      if (firstChar === '<' || firstChar === '&') {
	        var endTag = '';
	        if (firstChar === '<') {
	          endTag = '>';
	        } else {
	          endTag = ';';
	        }

	        while (curString.substr(tmpStrPos + 1).charAt(0) !== endTag) {
	          tmpStrPos++;
	          if (tmpStrPos + 1 > curString.length) {
	            break;
	          }
	        }
	        tmpStrPos++;
	      }

	      // call before functions if applicable
	      if (curStrPos === 0 || curStrPos === tmpStrPos) {
	        this.toggleBlinking(false)
	        this.options.preStringTyped(this.arrayPos, this);
	      }
	      // start typing each new char into existing string
	      // curString: arg, this.el.html: original text inside element
	      curStrPos += numChars;
	      var nextString = curString.substr(0, curStrPos);
	      this.replaceText(nextString);
	      // loop the function
	      this.typewrite(curString, curStrPos);
	    }`

**Comment by marabesi** [comment]
A final solution to that might be https://github.com/mattboldt/typed.js/pull/337

**Comment by CreativeDive** [comment]
@root91 Your fix ist working well for me and solves the described issue. Why this is not a part of the latest version?
