### ISSUE TITLE
Typed with pjax

### ISSUE THREAD

**Issue by theamnesic** [mattboldt/typed.js#98]
Hi !

With [pjax](https://github.com/defunkt/jquery-pjax), the cursor duplicate each time you use browser back/forward navigation.

My temporary fix : 

```javascript
    if $('.typed-cursor').length > 1
        $('.typed-cursor').not(':first').remove() 
```

Thanks !

— G

**Comment by mattboldt** [comment]
Ah. This is because of the way the `build` method works. It inserts the element after the typed tag, and with your setup the element is still there from before. I think your fix is good for now and if it comes up again in the future I'll further into a proper fix.
